// Code generated by plugins/d2r/tools/datagen. DO NOT EDIT.

package data

// ItemRatios contains quality determination parameters from itemratio.txt.
// Only version 1 (LoD/D2R) rows are included.
var ItemRatios = []ItemRatioEntry{
	{Unique: QualityModifiers{400, 1, 6400}, Set: QualityModifiers{160, 2, 5600}, Rare: QualityModifiers{100, 2, 3200}, Magic: QualityModifiers{34, 3, 192}},
	{IsUber: true, Unique: QualityModifiers{400, 1, 6400}, Set: QualityModifiers{160, 2, 5600}, Rare: QualityModifiers{100, 2, 3200}, Magic: QualityModifiers{34, 3, 192}},
	{IsClassSpecific: true, Unique: QualityModifiers{240, 3, 6400}, Set: QualityModifiers{120, 3, 5600}, Rare: QualityModifiers{80, 3, 3200}, Magic: QualityModifiers{17, 6, 192}},
	{IsUber: true, IsClassSpecific: true, Unique: QualityModifiers{240, 3, 6400}, Set: QualityModifiers{120, 3, 5600}, Rare: QualityModifiers{80, 3, 3200}, Magic: QualityModifiers{17, 6, 192}},
}
