// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: savecraft/v1/protocol.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseErrorType int32

const (
	ParseErrorType_PARSE_ERROR_TYPE_UNSPECIFIED         ParseErrorType = 0
	ParseErrorType_PARSE_ERROR_TYPE_UNSUPPORTED_VERSION ParseErrorType = 1
	ParseErrorType_PARSE_ERROR_TYPE_CORRUPT_FILE        ParseErrorType = 2
	ParseErrorType_PARSE_ERROR_TYPE_PARSE_ERROR         ParseErrorType = 3
)

// Enum value maps for ParseErrorType.
var (
	ParseErrorType_name = map[int32]string{
		0: "PARSE_ERROR_TYPE_UNSPECIFIED",
		1: "PARSE_ERROR_TYPE_UNSUPPORTED_VERSION",
		2: "PARSE_ERROR_TYPE_CORRUPT_FILE",
		3: "PARSE_ERROR_TYPE_PARSE_ERROR",
	}
	ParseErrorType_value = map[string]int32{
		"PARSE_ERROR_TYPE_UNSPECIFIED":         0,
		"PARSE_ERROR_TYPE_UNSUPPORTED_VERSION": 1,
		"PARSE_ERROR_TYPE_CORRUPT_FILE":        2,
		"PARSE_ERROR_TYPE_PARSE_ERROR":         3,
	}
)

func (x ParseErrorType) Enum() *ParseErrorType {
	p := new(ParseErrorType)
	*p = x
	return p
}

func (x ParseErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParseErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_savecraft_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (ParseErrorType) Type() protoreflect.EnumType {
	return &file_savecraft_v1_protocol_proto_enumTypes[0]
}

func (x ParseErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParseErrorType.Descriptor instead.
func (ParseErrorType) EnumDescriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{0}
}

type GameStatusEnum int32

const (
	GameStatusEnum_GAME_STATUS_ENUM_UNSPECIFIED GameStatusEnum = 0
	GameStatusEnum_GAME_STATUS_ENUM_DETECTED    GameStatusEnum = 1
	GameStatusEnum_GAME_STATUS_ENUM_WATCHING    GameStatusEnum = 2
	GameStatusEnum_GAME_STATUS_ENUM_ERROR       GameStatusEnum = 3
	GameStatusEnum_GAME_STATUS_ENUM_NOT_FOUND   GameStatusEnum = 4
)

// Enum value maps for GameStatusEnum.
var (
	GameStatusEnum_name = map[int32]string{
		0: "GAME_STATUS_ENUM_UNSPECIFIED",
		1: "GAME_STATUS_ENUM_DETECTED",
		2: "GAME_STATUS_ENUM_WATCHING",
		3: "GAME_STATUS_ENUM_ERROR",
		4: "GAME_STATUS_ENUM_NOT_FOUND",
	}
	GameStatusEnum_value = map[string]int32{
		"GAME_STATUS_ENUM_UNSPECIFIED": 0,
		"GAME_STATUS_ENUM_DETECTED":    1,
		"GAME_STATUS_ENUM_WATCHING":    2,
		"GAME_STATUS_ENUM_ERROR":       3,
		"GAME_STATUS_ENUM_NOT_FOUND":   4,
	}
)

func (x GameStatusEnum) Enum() *GameStatusEnum {
	p := new(GameStatusEnum)
	*p = x
	return p
}

func (x GameStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_savecraft_v1_protocol_proto_enumTypes[1].Descriptor()
}

func (GameStatusEnum) Type() protoreflect.EnumType {
	return &file_savecraft_v1_protocol_proto_enumTypes[1]
}

func (x GameStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatusEnum.Descriptor instead.
func (GameStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{1}
}

// Message is the top-level WebSocket envelope.
// All messages on the daemon↔server↔UI channel use this wrapper.
// The oneof field numbers are grouped by category with gaps for future additions.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_DaemonOnline
	//	*Message_DaemonOffline
	//	*Message_ScanStarted
	//	*Message_ScanCompleted
	//	*Message_GameDetected
	//	*Message_GameNotFound
	//	*Message_Watching
	//	*Message_ParseStarted
	//	*Message_PluginStatus
	//	*Message_ParseCompleted
	//	*Message_ParseFailed
	//	*Message_PushStarted
	//	*Message_PushCompleted
	//	*Message_PushFailed
	//	*Message_PluginUpdated
	//	*Message_ConfigUpdate
	//	*Message_RescanGame
	//	*Message_PluginAvailable
	//	*Message_DeviceState
	//	*Message_TestPath
	//	*Message_TestPathResult
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetDaemonOnline() *DaemonOnline {
	if x != nil {
		if x, ok := x.Payload.(*Message_DaemonOnline); ok {
			return x.DaemonOnline
		}
	}
	return nil
}

func (x *Message) GetDaemonOffline() *DaemonOffline {
	if x != nil {
		if x, ok := x.Payload.(*Message_DaemonOffline); ok {
			return x.DaemonOffline
		}
	}
	return nil
}

func (x *Message) GetScanStarted() *ScanStarted {
	if x != nil {
		if x, ok := x.Payload.(*Message_ScanStarted); ok {
			return x.ScanStarted
		}
	}
	return nil
}

func (x *Message) GetScanCompleted() *ScanCompleted {
	if x != nil {
		if x, ok := x.Payload.(*Message_ScanCompleted); ok {
			return x.ScanCompleted
		}
	}
	return nil
}

func (x *Message) GetGameDetected() *GameDetected {
	if x != nil {
		if x, ok := x.Payload.(*Message_GameDetected); ok {
			return x.GameDetected
		}
	}
	return nil
}

func (x *Message) GetGameNotFound() *GameNotFound {
	if x != nil {
		if x, ok := x.Payload.(*Message_GameNotFound); ok {
			return x.GameNotFound
		}
	}
	return nil
}

func (x *Message) GetWatching() *Watching {
	if x != nil {
		if x, ok := x.Payload.(*Message_Watching); ok {
			return x.Watching
		}
	}
	return nil
}

func (x *Message) GetParseStarted() *ParseStarted {
	if x != nil {
		if x, ok := x.Payload.(*Message_ParseStarted); ok {
			return x.ParseStarted
		}
	}
	return nil
}

func (x *Message) GetPluginStatus() *PluginStatus {
	if x != nil {
		if x, ok := x.Payload.(*Message_PluginStatus); ok {
			return x.PluginStatus
		}
	}
	return nil
}

func (x *Message) GetParseCompleted() *ParseCompleted {
	if x != nil {
		if x, ok := x.Payload.(*Message_ParseCompleted); ok {
			return x.ParseCompleted
		}
	}
	return nil
}

func (x *Message) GetParseFailed() *ParseFailed {
	if x != nil {
		if x, ok := x.Payload.(*Message_ParseFailed); ok {
			return x.ParseFailed
		}
	}
	return nil
}

func (x *Message) GetPushStarted() *PushStarted {
	if x != nil {
		if x, ok := x.Payload.(*Message_PushStarted); ok {
			return x.PushStarted
		}
	}
	return nil
}

func (x *Message) GetPushCompleted() *PushCompleted {
	if x != nil {
		if x, ok := x.Payload.(*Message_PushCompleted); ok {
			return x.PushCompleted
		}
	}
	return nil
}

func (x *Message) GetPushFailed() *PushFailed {
	if x != nil {
		if x, ok := x.Payload.(*Message_PushFailed); ok {
			return x.PushFailed
		}
	}
	return nil
}

func (x *Message) GetPluginUpdated() *PluginUpdated {
	if x != nil {
		if x, ok := x.Payload.(*Message_PluginUpdated); ok {
			return x.PluginUpdated
		}
	}
	return nil
}

func (x *Message) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Message_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

func (x *Message) GetRescanGame() *RescanGame {
	if x != nil {
		if x, ok := x.Payload.(*Message_RescanGame); ok {
			return x.RescanGame
		}
	}
	return nil
}

func (x *Message) GetPluginAvailable() *PluginAvailable {
	if x != nil {
		if x, ok := x.Payload.(*Message_PluginAvailable); ok {
			return x.PluginAvailable
		}
	}
	return nil
}

func (x *Message) GetDeviceState() *DeviceState {
	if x != nil {
		if x, ok := x.Payload.(*Message_DeviceState); ok {
			return x.DeviceState
		}
	}
	return nil
}

func (x *Message) GetTestPath() *TestPath {
	if x != nil {
		if x, ok := x.Payload.(*Message_TestPath); ok {
			return x.TestPath
		}
	}
	return nil
}

func (x *Message) GetTestPathResult() *TestPathResult {
	if x != nil {
		if x, ok := x.Payload.(*Message_TestPathResult); ok {
			return x.TestPathResult
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_DaemonOnline struct {
	// Daemon lifecycle (1-9)
	DaemonOnline *DaemonOnline `protobuf:"bytes,1,opt,name=daemon_online,json=daemonOnline,proto3,oneof"`
}

type Message_DaemonOffline struct {
	DaemonOffline *DaemonOffline `protobuf:"bytes,2,opt,name=daemon_offline,json=daemonOffline,proto3,oneof"`
}

type Message_ScanStarted struct {
	// Game discovery (10-19)
	ScanStarted *ScanStarted `protobuf:"bytes,10,opt,name=scan_started,json=scanStarted,proto3,oneof"`
}

type Message_ScanCompleted struct {
	ScanCompleted *ScanCompleted `protobuf:"bytes,11,opt,name=scan_completed,json=scanCompleted,proto3,oneof"`
}

type Message_GameDetected struct {
	GameDetected *GameDetected `protobuf:"bytes,12,opt,name=game_detected,json=gameDetected,proto3,oneof"`
}

type Message_GameNotFound struct {
	GameNotFound *GameNotFound `protobuf:"bytes,13,opt,name=game_not_found,json=gameNotFound,proto3,oneof"`
}

type Message_Watching struct {
	Watching *Watching `protobuf:"bytes,14,opt,name=watching,proto3,oneof"`
}

type Message_ParseStarted struct {
	// Parse lifecycle (20-29)
	ParseStarted *ParseStarted `protobuf:"bytes,20,opt,name=parse_started,json=parseStarted,proto3,oneof"`
}

type Message_PluginStatus struct {
	PluginStatus *PluginStatus `protobuf:"bytes,21,opt,name=plugin_status,json=pluginStatus,proto3,oneof"`
}

type Message_ParseCompleted struct {
	ParseCompleted *ParseCompleted `protobuf:"bytes,22,opt,name=parse_completed,json=parseCompleted,proto3,oneof"`
}

type Message_ParseFailed struct {
	ParseFailed *ParseFailed `protobuf:"bytes,23,opt,name=parse_failed,json=parseFailed,proto3,oneof"`
}

type Message_PushStarted struct {
	// Push lifecycle (30-39)
	PushStarted *PushStarted `protobuf:"bytes,30,opt,name=push_started,json=pushStarted,proto3,oneof"`
}

type Message_PushCompleted struct {
	PushCompleted *PushCompleted `protobuf:"bytes,31,opt,name=push_completed,json=pushCompleted,proto3,oneof"`
}

type Message_PushFailed struct {
	PushFailed *PushFailed `protobuf:"bytes,32,opt,name=push_failed,json=pushFailed,proto3,oneof"`
}

type Message_PluginUpdated struct {
	// Plugin management (40-49)
	PluginUpdated *PluginUpdated `protobuf:"bytes,40,opt,name=plugin_updated,json=pluginUpdated,proto3,oneof"`
}

type Message_ConfigUpdate struct {
	// Commands: server → daemon (50-59)
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,50,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

type Message_RescanGame struct {
	RescanGame *RescanGame `protobuf:"bytes,51,opt,name=rescan_game,json=rescanGame,proto3,oneof"`
}

type Message_PluginAvailable struct {
	PluginAvailable *PluginAvailable `protobuf:"bytes,52,opt,name=plugin_available,json=pluginAvailable,proto3,oneof"`
}

type Message_DeviceState struct {
	// State: server → UI (60-69)
	DeviceState *DeviceState `protobuf:"bytes,60,opt,name=device_state,json=deviceState,proto3,oneof"`
}

type Message_TestPath struct {
	// User actions: UI → server → daemon (70-79)
	TestPath *TestPath `protobuf:"bytes,70,opt,name=test_path,json=testPath,proto3,oneof"`
}

type Message_TestPathResult struct {
	TestPathResult *TestPathResult `protobuf:"bytes,71,opt,name=test_path_result,json=testPathResult,proto3,oneof"`
}

func (*Message_DaemonOnline) isMessage_Payload() {}

func (*Message_DaemonOffline) isMessage_Payload() {}

func (*Message_ScanStarted) isMessage_Payload() {}

func (*Message_ScanCompleted) isMessage_Payload() {}

func (*Message_GameDetected) isMessage_Payload() {}

func (*Message_GameNotFound) isMessage_Payload() {}

func (*Message_Watching) isMessage_Payload() {}

func (*Message_ParseStarted) isMessage_Payload() {}

func (*Message_PluginStatus) isMessage_Payload() {}

func (*Message_ParseCompleted) isMessage_Payload() {}

func (*Message_ParseFailed) isMessage_Payload() {}

func (*Message_PushStarted) isMessage_Payload() {}

func (*Message_PushCompleted) isMessage_Payload() {}

func (*Message_PushFailed) isMessage_Payload() {}

func (*Message_PluginUpdated) isMessage_Payload() {}

func (*Message_ConfigUpdate) isMessage_Payload() {}

func (*Message_RescanGame) isMessage_Payload() {}

func (*Message_PluginAvailable) isMessage_Payload() {}

func (*Message_DeviceState) isMessage_Payload() {}

func (*Message_TestPath) isMessage_Payload() {}

func (*Message_TestPathResult) isMessage_Payload() {}

// Daemon process started and connected to the server.
type DaemonOnline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonOnline) Reset() {
	*x = DaemonOnline{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonOnline) ProtoMessage() {}

func (x *DaemonOnline) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonOnline.ProtoReflect.Descriptor instead.
func (*DaemonOnline) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *DaemonOnline) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DaemonOnline) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DaemonOnline) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Daemon shutting down gracefully (SIGTERM).
type DaemonOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonOffline) Reset() {
	*x = DaemonOffline{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonOffline) ProtoMessage() {}

func (x *DaemonOffline) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonOffline.ProtoReflect.Descriptor instead.
func (*DaemonOffline) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *DaemonOffline) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DaemonOffline) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Daemon is scanning a directory for save files.
type ScanStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanStarted) Reset() {
	*x = ScanStarted{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanStarted) ProtoMessage() {}

func (x *ScanStarted) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanStarted.ProtoReflect.Descriptor instead.
func (*ScanStarted) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *ScanStarted) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ScanStarted) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Scan finished. Reports what was found.
type ScanCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	FilesFound    int32                  `protobuf:"varint,3,opt,name=files_found,json=filesFound,proto3" json:"files_found,omitempty"`
	FileNames     []string               `protobuf:"bytes,4,rep,name=file_names,json=fileNames,proto3" json:"file_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanCompleted) Reset() {
	*x = ScanCompleted{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanCompleted) ProtoMessage() {}

func (x *ScanCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanCompleted.ProtoReflect.Descriptor instead.
func (*ScanCompleted) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *ScanCompleted) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ScanCompleted) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ScanCompleted) GetFilesFound() int32 {
	if x != nil {
		return x.FilesFound
	}
	return 0
}

func (x *ScanCompleted) GetFileNames() []string {
	if x != nil {
		return x.FileNames
	}
	return nil
}

// A game's save directory exists and contains saves.
type GameDetected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	SaveCount     int32                  `protobuf:"varint,3,opt,name=save_count,json=saveCount,proto3" json:"save_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameDetected) Reset() {
	*x = GameDetected{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDetected) ProtoMessage() {}

func (x *GameDetected) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDetected.ProtoReflect.Descriptor instead.
func (*GameDetected) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *GameDetected) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameDetected) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GameDetected) GetSaveCount() int32 {
	if x != nil {
		return x.SaveCount
	}
	return 0
}

// None of the expected save paths exist for this game.
type GameNotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PathsChecked  []string               `protobuf:"bytes,2,rep,name=paths_checked,json=pathsChecked,proto3" json:"paths_checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameNotFound) Reset() {
	*x = GameNotFound{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameNotFound) ProtoMessage() {}

func (x *GameNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameNotFound.ProtoReflect.Descriptor instead.
func (*GameNotFound) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *GameNotFound) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameNotFound) GetPathsChecked() []string {
	if x != nil {
		return x.PathsChecked
	}
	return nil
}

// Daemon is actively watching a directory for changes.
type Watching struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GameId         string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	FilesMonitored int32                  `protobuf:"varint,3,opt,name=files_monitored,json=filesMonitored,proto3" json:"files_monitored,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Watching) Reset() {
	*x = Watching{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Watching) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watching) ProtoMessage() {}

func (x *Watching) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watching.ProtoReflect.Descriptor instead.
func (*Watching) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *Watching) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Watching) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Watching) GetFilesMonitored() int32 {
	if x != nil {
		return x.FilesMonitored
	}
	return 0
}

// Daemon detected a file change and is feeding it to the WASM plugin.
type ParseStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseStarted) Reset() {
	*x = ParseStarted{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseStarted) ProtoMessage() {}

func (x *ParseStarted) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseStarted.ProtoReflect.Descriptor instead.
func (*ParseStarted) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *ParseStarted) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ParseStarted) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// Forwarded from plugin stdout status lines during parsing.
// Plugin authors emit these for long-running or multi-step parses.
type PluginStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatus) Reset() {
	*x = PluginStatus{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatus) ProtoMessage() {}

func (x *PluginStatus) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatus.ProtoReflect.Descriptor instead.
func (*PluginStatus) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *PluginStatus) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PluginStatus) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PluginStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Plugin finished successfully. Identity and summary extracted from plugin output.
type ParseCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Identity      *SaveIdentity          `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	SectionsCount int32                  `protobuf:"varint,5,opt,name=sections_count,json=sectionsCount,proto3" json:"sections_count,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseCompleted) Reset() {
	*x = ParseCompleted{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseCompleted) ProtoMessage() {}

func (x *ParseCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseCompleted.ProtoReflect.Descriptor instead.
func (*ParseCompleted) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *ParseCompleted) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ParseCompleted) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ParseCompleted) GetIdentity() *SaveIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ParseCompleted) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ParseCompleted) GetSectionsCount() int32 {
	if x != nil {
		return x.SectionsCount
	}
	return 0
}

func (x *ParseCompleted) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// Plugin failed to parse the file.
type ParseFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ErrorType     ParseErrorType         `protobuf:"varint,3,opt,name=error_type,json=errorType,proto3,enum=savecraft.v1.ParseErrorType" json:"error_type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseFailed) Reset() {
	*x = ParseFailed{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseFailed) ProtoMessage() {}

func (x *ParseFailed) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseFailed.ProtoReflect.Descriptor instead.
func (*ParseFailed) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *ParseFailed) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ParseFailed) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ParseFailed) GetErrorType() ParseErrorType {
	if x != nil {
		return x.ErrorType
	}
	return ParseErrorType_PARSE_ERROR_TYPE_UNSPECIFIED
}

func (x *ParseFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Daemon is uploading parsed game state to the server via HTTP POST.
type PushStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushStarted) Reset() {
	*x = PushStarted{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStarted) ProtoMessage() {}

func (x *PushStarted) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStarted.ProtoReflect.Descriptor instead.
func (*PushStarted) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *PushStarted) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PushStarted) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PushStarted) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// Upload succeeded. Server assigned/resolved the save UUID.
type PushCompleted struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GameId            string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	SaveUuid          string                 `protobuf:"bytes,2,opt,name=save_uuid,json=saveUuid,proto3" json:"save_uuid,omitempty"`
	Summary           string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	SnapshotSizeBytes int64                  `protobuf:"varint,4,opt,name=snapshot_size_bytes,json=snapshotSizeBytes,proto3" json:"snapshot_size_bytes,omitempty"`
	DurationMs        int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PushCompleted) Reset() {
	*x = PushCompleted{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCompleted) ProtoMessage() {}

func (x *PushCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCompleted.ProtoReflect.Descriptor instead.
func (*PushCompleted) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *PushCompleted) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PushCompleted) GetSaveUuid() string {
	if x != nil {
		return x.SaveUuid
	}
	return ""
}

func (x *PushCompleted) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PushCompleted) GetSnapshotSizeBytes() int64 {
	if x != nil {
		return x.SnapshotSizeBytes
	}
	return 0
}

func (x *PushCompleted) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Upload failed. will_retry indicates if the daemon will retry automatically.
type PushFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WillRetry     bool                   `protobuf:"varint,3,opt,name=will_retry,json=willRetry,proto3" json:"will_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFailed) Reset() {
	*x = PushFailed{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFailed) ProtoMessage() {}

func (x *PushFailed) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFailed.ProtoReflect.Descriptor instead.
func (*PushFailed) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *PushFailed) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PushFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PushFailed) GetWillRetry() bool {
	if x != nil {
		return x.WillRetry
	}
	return false
}

// Daemon successfully updated a plugin to a new version.
type PluginUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginUpdated) Reset() {
	*x = PluginUpdated{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginUpdated) ProtoMessage() {}

func (x *PluginUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginUpdated.ProtoReflect.Descriptor instead.
func (*PluginUpdated) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *PluginUpdated) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PluginUpdated) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Full config push. Sent when user changes settings in the web UI.
type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         map[string]*GameConfig `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigUpdate) GetGames() map[string]*GameConfig {
	if x != nil {
		return x.Games
	}
	return nil
}

type GameConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SavePath       string                 `protobuf:"bytes,1,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	Enabled        bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	FileExtensions []string               `protobuf:"bytes,3,rep,name=file_extensions,json=fileExtensions,proto3" json:"file_extensions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GameConfig) Reset() {
	*x = GameConfig{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfig) ProtoMessage() {}

func (x *GameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfig.ProtoReflect.Descriptor instead.
func (*GameConfig) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *GameConfig) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *GameConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GameConfig) GetFileExtensions() []string {
	if x != nil {
		return x.FileExtensions
	}
	return nil
}

// Request the daemon to rescan a game's save directory.
type RescanGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescanGame) Reset() {
	*x = RescanGame{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanGame) ProtoMessage() {}

func (x *RescanGame) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanGame.ProtoReflect.Descriptor instead.
func (*RescanGame) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{18}
}

func (x *RescanGame) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

// Notify daemon that a plugin update is available for download.
type PluginAvailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginAvailable) Reset() {
	*x = PluginAvailable{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginAvailable) ProtoMessage() {}

func (x *PluginAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginAvailable.ProtoReflect.Descriptor instead.
func (*PluginAvailable) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{19}
}

func (x *PluginAvailable) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PluginAvailable) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginAvailable) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Full device state snapshot. Sent to UI on WebSocket connect for cold start.
// Constructed from D1 persisted events so the page isn't blank.
type DeviceState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceState) Reset() {
	*x = DeviceState{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceState) ProtoMessage() {}

func (x *DeviceState) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceState.ProtoReflect.Descriptor instead.
func (*DeviceState) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{20}
}

func (x *DeviceState) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Games         []*GameInfo            `protobuf:"bytes,4,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{21}
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *DeviceInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *DeviceInfo) GetGames() []*GameInfo {
	if x != nil {
		return x.Games
	}
	return nil
}

type GameInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameName      string                 `protobuf:"bytes,2,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	Status        GameStatusEnum         `protobuf:"varint,3,opt,name=status,proto3,enum=savecraft.v1.GameStatusEnum" json:"status,omitempty"`
	Saves         []*SaveInfo            `protobuf:"bytes,4,rep,name=saves,proto3" json:"saves,omitempty"`
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{22}
}

func (x *GameInfo) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameInfo) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *GameInfo) GetStatus() GameStatusEnum {
	if x != nil {
		return x.Status
	}
	return GameStatusEnum_GAME_STATUS_ENUM_UNSPECIFIED
}

func (x *GameInfo) GetSaves() []*SaveInfo {
	if x != nil {
		return x.Saves
	}
	return nil
}

func (x *GameInfo) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

type SaveInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaveUuid      string                 `protobuf:"bytes,1,opt,name=save_uuid,json=saveUuid,proto3" json:"save_uuid,omitempty"`
	Identity      *SaveIdentity          `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveInfo) Reset() {
	*x = SaveInfo{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveInfo) ProtoMessage() {}

func (x *SaveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveInfo.ProtoReflect.Descriptor instead.
func (*SaveInfo) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{23}
}

func (x *SaveInfo) GetSaveUuid() string {
	if x != nil {
		return x.SaveUuid
	}
	return ""
}

func (x *SaveInfo) GetIdentity() *SaveIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *SaveInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SaveInfo) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// User entered a custom save path in the web UI. Test if it's valid.
type TestPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPath) Reset() {
	*x = TestPath{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPath) ProtoMessage() {}

func (x *TestPath) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPath.ProtoReflect.Descriptor instead.
func (*TestPath) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{24}
}

func (x *TestPath) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *TestPath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Result of a TestPath request.
type TestPathResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	FilesFound    int32                  `protobuf:"varint,4,opt,name=files_found,json=filesFound,proto3" json:"files_found,omitempty"`
	FileNames     []string               `protobuf:"bytes,5,rep,name=file_names,json=fileNames,proto3" json:"file_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPathResult) Reset() {
	*x = TestPathResult{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPathResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPathResult) ProtoMessage() {}

func (x *TestPathResult) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPathResult.ProtoReflect.Descriptor instead.
func (*TestPathResult) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{25}
}

func (x *TestPathResult) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *TestPathResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TestPathResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *TestPathResult) GetFilesFound() int32 {
	if x != nil {
		return x.FilesFound
	}
	return 0
}

func (x *TestPathResult) GetFileNames() []string {
	if x != nil {
		return x.FileNames
	}
	return nil
}

// Compact save identity for display in status events and UI.
// Derived from the full GameState identity emitted by the plugin.
type SaveIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Game-specific display metadata. e.g. {"class": "Paladin", "level": 89}
	// Uses Struct to preserve value types (numbers, strings, bools).
	Extra         *structpb.Struct `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveIdentity) Reset() {
	*x = SaveIdentity{}
	mi := &file_savecraft_v1_protocol_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveIdentity) ProtoMessage() {}

func (x *SaveIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_savecraft_v1_protocol_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveIdentity.ProtoReflect.Descriptor instead.
func (*SaveIdentity) Descriptor() ([]byte, []int) {
	return file_savecraft_v1_protocol_proto_rawDescGZIP(), []int{26}
}

func (x *SaveIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveIdentity) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_savecraft_v1_protocol_proto protoreflect.FileDescriptor

const file_savecraft_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1bsavecraft/v1/protocol.proto\x12\fsavecraft.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x85\v\n" +
	"\aMessage\x12A\n" +
	"\rdaemon_online\x18\x01 \x01(\v2\x1a.savecraft.v1.DaemonOnlineH\x00R\fdaemonOnline\x12D\n" +
	"\x0edaemon_offline\x18\x02 \x01(\v2\x1b.savecraft.v1.DaemonOfflineH\x00R\rdaemonOffline\x12>\n" +
	"\fscan_started\x18\n" +
	" \x01(\v2\x19.savecraft.v1.ScanStartedH\x00R\vscanStarted\x12D\n" +
	"\x0escan_completed\x18\v \x01(\v2\x1b.savecraft.v1.ScanCompletedH\x00R\rscanCompleted\x12A\n" +
	"\rgame_detected\x18\f \x01(\v2\x1a.savecraft.v1.GameDetectedH\x00R\fgameDetected\x12B\n" +
	"\x0egame_not_found\x18\r \x01(\v2\x1a.savecraft.v1.GameNotFoundH\x00R\fgameNotFound\x124\n" +
	"\bwatching\x18\x0e \x01(\v2\x16.savecraft.v1.WatchingH\x00R\bwatching\x12A\n" +
	"\rparse_started\x18\x14 \x01(\v2\x1a.savecraft.v1.ParseStartedH\x00R\fparseStarted\x12A\n" +
	"\rplugin_status\x18\x15 \x01(\v2\x1a.savecraft.v1.PluginStatusH\x00R\fpluginStatus\x12G\n" +
	"\x0fparse_completed\x18\x16 \x01(\v2\x1c.savecraft.v1.ParseCompletedH\x00R\x0eparseCompleted\x12>\n" +
	"\fparse_failed\x18\x17 \x01(\v2\x19.savecraft.v1.ParseFailedH\x00R\vparseFailed\x12>\n" +
	"\fpush_started\x18\x1e \x01(\v2\x19.savecraft.v1.PushStartedH\x00R\vpushStarted\x12D\n" +
	"\x0epush_completed\x18\x1f \x01(\v2\x1b.savecraft.v1.PushCompletedH\x00R\rpushCompleted\x12;\n" +
	"\vpush_failed\x18  \x01(\v2\x18.savecraft.v1.PushFailedH\x00R\n" +
	"pushFailed\x12D\n" +
	"\x0eplugin_updated\x18( \x01(\v2\x1b.savecraft.v1.PluginUpdatedH\x00R\rpluginUpdated\x12A\n" +
	"\rconfig_update\x182 \x01(\v2\x1a.savecraft.v1.ConfigUpdateH\x00R\fconfigUpdate\x12;\n" +
	"\vrescan_game\x183 \x01(\v2\x18.savecraft.v1.RescanGameH\x00R\n" +
	"rescanGame\x12J\n" +
	"\x10plugin_available\x184 \x01(\v2\x1d.savecraft.v1.PluginAvailableH\x00R\x0fpluginAvailable\x12>\n" +
	"\fdevice_state\x18< \x01(\v2\x19.savecraft.v1.DeviceStateH\x00R\vdeviceState\x125\n" +
	"\ttest_path\x18F \x01(\v2\x16.savecraft.v1.TestPathH\x00R\btestPath\x12H\n" +
	"\x10test_path_result\x18G \x01(\v2\x1c.savecraft.v1.TestPathResultH\x00R\x0etestPathResultB\t\n" +
	"\apayload\"\x7f\n" +
	"\fDaemonOnline\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"f\n" +
	"\rDaemonOffline\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\":\n" +
	"\vScanStarted\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"|\n" +
	"\rScanCompleted\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vfiles_found\x18\x03 \x01(\x05R\n" +
	"filesFound\x12\x1d\n" +
	"\n" +
	"file_names\x18\x04 \x03(\tR\tfileNames\"Z\n" +
	"\fGameDetected\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"save_count\x18\x03 \x01(\x05R\tsaveCount\"L\n" +
	"\fGameNotFound\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12#\n" +
	"\rpaths_checked\x18\x02 \x03(\tR\fpathsChecked\"`\n" +
	"\bWatching\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12'\n" +
	"\x0ffiles_monitored\x18\x03 \x01(\x05R\x0efilesMonitored\"D\n" +
	"\fParseStarted\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"^\n" +
	"\fPluginStatus\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xde\x01\n" +
	"\x0eParseCompleted\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x126\n" +
	"\bidentity\x18\x03 \x01(\v2\x1a.savecraft.v1.SaveIdentityR\bidentity\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12%\n" +
	"\x0esections_count\x18\x05 \x01(\x05R\rsectionsCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\"\x9a\x01\n" +
	"\vParseFailed\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12;\n" +
	"\n" +
	"error_type\x18\x03 \x01(\x0e2\x1c.savecraft.v1.ParseErrorTypeR\terrorType\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"_\n" +
	"\vPushStarted\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"\xb0\x01\n" +
	"\rPushCompleted\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tsave_uuid\x18\x02 \x01(\tR\bsaveUuid\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12.\n" +
	"\x13snapshot_size_bytes\x18\x04 \x01(\x03R\x11snapshotSizeBytes\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\"^\n" +
	"\n" +
	"PushFailed\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"will_retry\x18\x03 \x01(\bR\twillRetry\"B\n" +
	"\rPluginUpdated\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x9f\x01\n" +
	"\fConfigUpdate\x12;\n" +
	"\x05games\x18\x01 \x03(\v2%.savecraft.v1.ConfigUpdate.GamesEntryR\x05games\x1aR\n" +
	"\n" +
	"GamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.savecraft.v1.GameConfigR\x05value:\x028\x01\"l\n" +
	"\n" +
	"GameConfig\x12\x1b\n" +
	"\tsave_path\x18\x01 \x01(\tR\bsavePath\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12'\n" +
	"\x0ffile_extensions\x18\x03 \x03(\tR\x0efileExtensions\"%\n" +
	"\n" +
	"RescanGame\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"V\n" +
	"\x0fPluginAvailable\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"A\n" +
	"\vDeviceState\x122\n" +
	"\adevices\x18\x01 \x03(\v2\x18.savecraft.v1.DeviceInfoR\adevices\"\xa8\x01\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x127\n" +
	"\tlast_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12,\n" +
	"\x05games\x18\x04 \x03(\v2\x16.savecraft.v1.GameInfoR\x05games\"\xe5\x01\n" +
	"\bGameInfo\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tgame_name\x18\x02 \x01(\tR\bgameName\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.savecraft.v1.GameStatusEnumR\x06status\x12,\n" +
	"\x05saves\x18\x04 \x03(\v2\x16.savecraft.v1.SaveInfoR\x05saves\x12?\n" +
	"\rlast_activity\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\"\xb8\x01\n" +
	"\bSaveInfo\x12\x1b\n" +
	"\tsave_uuid\x18\x01 \x01(\tR\bsaveUuid\x126\n" +
	"\bidentity\x18\x02 \x01(\v2\x1a.savecraft.v1.SaveIdentityR\bidentity\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12=\n" +
	"\flast_updated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"7\n" +
	"\bTestPath\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x93\x01\n" +
	"\x0eTestPathResult\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\x12\x1f\n" +
	"\vfiles_found\x18\x04 \x01(\x05R\n" +
	"filesFound\x12\x1d\n" +
	"\n" +
	"file_names\x18\x05 \x03(\tR\tfileNames\"Q\n" +
	"\fSaveIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x05extra\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05extra*\xa1\x01\n" +
	"\x0eParseErrorType\x12 \n" +
	"\x1cPARSE_ERROR_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$PARSE_ERROR_TYPE_UNSUPPORTED_VERSION\x10\x01\x12!\n" +
	"\x1dPARSE_ERROR_TYPE_CORRUPT_FILE\x10\x02\x12 \n" +
	"\x1cPARSE_ERROR_TYPE_PARSE_ERROR\x10\x03*\xac\x01\n" +
	"\x0eGameStatusEnum\x12 \n" +
	"\x1cGAME_STATUS_ENUM_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GAME_STATUS_ENUM_DETECTED\x10\x01\x12\x1d\n" +
	"\x19GAME_STATUS_ENUM_WATCHING\x10\x02\x12\x1a\n" +
	"\x16GAME_STATUS_ENUM_ERROR\x10\x03\x12\x1e\n" +
	"\x1aGAME_STATUS_ENUM_NOT_FOUND\x10\x04B4Z2github.com/joshsymonds/savecraft.gg/internal/protob\x06proto3"

var (
	file_savecraft_v1_protocol_proto_rawDescOnce sync.Once
	file_savecraft_v1_protocol_proto_rawDescData []byte
)

func file_savecraft_v1_protocol_proto_rawDescGZIP() []byte {
	file_savecraft_v1_protocol_proto_rawDescOnce.Do(func() {
		file_savecraft_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_savecraft_v1_protocol_proto_rawDesc), len(file_savecraft_v1_protocol_proto_rawDesc)))
	})
	return file_savecraft_v1_protocol_proto_rawDescData
}

var file_savecraft_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_savecraft_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_savecraft_v1_protocol_proto_goTypes = []any{
	(ParseErrorType)(0),           // 0: savecraft.v1.ParseErrorType
	(GameStatusEnum)(0),           // 1: savecraft.v1.GameStatusEnum
	(*Message)(nil),               // 2: savecraft.v1.Message
	(*DaemonOnline)(nil),          // 3: savecraft.v1.DaemonOnline
	(*DaemonOffline)(nil),         // 4: savecraft.v1.DaemonOffline
	(*ScanStarted)(nil),           // 5: savecraft.v1.ScanStarted
	(*ScanCompleted)(nil),         // 6: savecraft.v1.ScanCompleted
	(*GameDetected)(nil),          // 7: savecraft.v1.GameDetected
	(*GameNotFound)(nil),          // 8: savecraft.v1.GameNotFound
	(*Watching)(nil),              // 9: savecraft.v1.Watching
	(*ParseStarted)(nil),          // 10: savecraft.v1.ParseStarted
	(*PluginStatus)(nil),          // 11: savecraft.v1.PluginStatus
	(*ParseCompleted)(nil),        // 12: savecraft.v1.ParseCompleted
	(*ParseFailed)(nil),           // 13: savecraft.v1.ParseFailed
	(*PushStarted)(nil),           // 14: savecraft.v1.PushStarted
	(*PushCompleted)(nil),         // 15: savecraft.v1.PushCompleted
	(*PushFailed)(nil),            // 16: savecraft.v1.PushFailed
	(*PluginUpdated)(nil),         // 17: savecraft.v1.PluginUpdated
	(*ConfigUpdate)(nil),          // 18: savecraft.v1.ConfigUpdate
	(*GameConfig)(nil),            // 19: savecraft.v1.GameConfig
	(*RescanGame)(nil),            // 20: savecraft.v1.RescanGame
	(*PluginAvailable)(nil),       // 21: savecraft.v1.PluginAvailable
	(*DeviceState)(nil),           // 22: savecraft.v1.DeviceState
	(*DeviceInfo)(nil),            // 23: savecraft.v1.DeviceInfo
	(*GameInfo)(nil),              // 24: savecraft.v1.GameInfo
	(*SaveInfo)(nil),              // 25: savecraft.v1.SaveInfo
	(*TestPath)(nil),              // 26: savecraft.v1.TestPath
	(*TestPathResult)(nil),        // 27: savecraft.v1.TestPathResult
	(*SaveIdentity)(nil),          // 28: savecraft.v1.SaveIdentity
	nil,                           // 29: savecraft.v1.ConfigUpdate.GamesEntry
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 31: google.protobuf.Struct
}
var file_savecraft_v1_protocol_proto_depIdxs = []int32{
	3,  // 0: savecraft.v1.Message.daemon_online:type_name -> savecraft.v1.DaemonOnline
	4,  // 1: savecraft.v1.Message.daemon_offline:type_name -> savecraft.v1.DaemonOffline
	5,  // 2: savecraft.v1.Message.scan_started:type_name -> savecraft.v1.ScanStarted
	6,  // 3: savecraft.v1.Message.scan_completed:type_name -> savecraft.v1.ScanCompleted
	7,  // 4: savecraft.v1.Message.game_detected:type_name -> savecraft.v1.GameDetected
	8,  // 5: savecraft.v1.Message.game_not_found:type_name -> savecraft.v1.GameNotFound
	9,  // 6: savecraft.v1.Message.watching:type_name -> savecraft.v1.Watching
	10, // 7: savecraft.v1.Message.parse_started:type_name -> savecraft.v1.ParseStarted
	11, // 8: savecraft.v1.Message.plugin_status:type_name -> savecraft.v1.PluginStatus
	12, // 9: savecraft.v1.Message.parse_completed:type_name -> savecraft.v1.ParseCompleted
	13, // 10: savecraft.v1.Message.parse_failed:type_name -> savecraft.v1.ParseFailed
	14, // 11: savecraft.v1.Message.push_started:type_name -> savecraft.v1.PushStarted
	15, // 12: savecraft.v1.Message.push_completed:type_name -> savecraft.v1.PushCompleted
	16, // 13: savecraft.v1.Message.push_failed:type_name -> savecraft.v1.PushFailed
	17, // 14: savecraft.v1.Message.plugin_updated:type_name -> savecraft.v1.PluginUpdated
	18, // 15: savecraft.v1.Message.config_update:type_name -> savecraft.v1.ConfigUpdate
	20, // 16: savecraft.v1.Message.rescan_game:type_name -> savecraft.v1.RescanGame
	21, // 17: savecraft.v1.Message.plugin_available:type_name -> savecraft.v1.PluginAvailable
	22, // 18: savecraft.v1.Message.device_state:type_name -> savecraft.v1.DeviceState
	26, // 19: savecraft.v1.Message.test_path:type_name -> savecraft.v1.TestPath
	27, // 20: savecraft.v1.Message.test_path_result:type_name -> savecraft.v1.TestPathResult
	30, // 21: savecraft.v1.DaemonOnline.timestamp:type_name -> google.protobuf.Timestamp
	30, // 22: savecraft.v1.DaemonOffline.timestamp:type_name -> google.protobuf.Timestamp
	28, // 23: savecraft.v1.ParseCompleted.identity:type_name -> savecraft.v1.SaveIdentity
	0,  // 24: savecraft.v1.ParseFailed.error_type:type_name -> savecraft.v1.ParseErrorType
	29, // 25: savecraft.v1.ConfigUpdate.games:type_name -> savecraft.v1.ConfigUpdate.GamesEntry
	23, // 26: savecraft.v1.DeviceState.devices:type_name -> savecraft.v1.DeviceInfo
	30, // 27: savecraft.v1.DeviceInfo.last_seen:type_name -> google.protobuf.Timestamp
	24, // 28: savecraft.v1.DeviceInfo.games:type_name -> savecraft.v1.GameInfo
	1,  // 29: savecraft.v1.GameInfo.status:type_name -> savecraft.v1.GameStatusEnum
	25, // 30: savecraft.v1.GameInfo.saves:type_name -> savecraft.v1.SaveInfo
	30, // 31: savecraft.v1.GameInfo.last_activity:type_name -> google.protobuf.Timestamp
	28, // 32: savecraft.v1.SaveInfo.identity:type_name -> savecraft.v1.SaveIdentity
	30, // 33: savecraft.v1.SaveInfo.last_updated:type_name -> google.protobuf.Timestamp
	31, // 34: savecraft.v1.SaveIdentity.extra:type_name -> google.protobuf.Struct
	19, // 35: savecraft.v1.ConfigUpdate.GamesEntry.value:type_name -> savecraft.v1.GameConfig
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_savecraft_v1_protocol_proto_init() }
func file_savecraft_v1_protocol_proto_init() {
	if File_savecraft_v1_protocol_proto != nil {
		return
	}
	file_savecraft_v1_protocol_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_DaemonOnline)(nil),
		(*Message_DaemonOffline)(nil),
		(*Message_ScanStarted)(nil),
		(*Message_ScanCompleted)(nil),
		(*Message_GameDetected)(nil),
		(*Message_GameNotFound)(nil),
		(*Message_Watching)(nil),
		(*Message_ParseStarted)(nil),
		(*Message_PluginStatus)(nil),
		(*Message_ParseCompleted)(nil),
		(*Message_ParseFailed)(nil),
		(*Message_PushStarted)(nil),
		(*Message_PushCompleted)(nil),
		(*Message_PushFailed)(nil),
		(*Message_PluginUpdated)(nil),
		(*Message_ConfigUpdate)(nil),
		(*Message_RescanGame)(nil),
		(*Message_PluginAvailable)(nil),
		(*Message_DeviceState)(nil),
		(*Message_TestPath)(nil),
		(*Message_TestPathResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_savecraft_v1_protocol_proto_rawDesc), len(file_savecraft_v1_protocol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_savecraft_v1_protocol_proto_goTypes,
		DependencyIndexes: file_savecraft_v1_protocol_proto_depIdxs,
		EnumInfos:         file_savecraft_v1_protocol_proto_enumTypes,
		MessageInfos:      file_savecraft_v1_protocol_proto_msgTypes,
	}.Build()
	File_savecraft_v1_protocol_proto = out.File
	file_savecraft_v1_protocol_proto_goTypes = nil
	file_savecraft_v1_protocol_proto_depIdxs = nil
}
