// Code generated by plugins/mtga/tools/scryfall-fetch. DO NOT EDIT.
// Source: Scryfall Oracle Cards (scryfall.com)
// Card data copyright Wizards of the Coast, LLC.
// Generated: 2026-03-23T17:04:05Z

package data

import (
	_ "embed"
	"encoding/json"
	"strconv"
)

// Card contains full Scryfall card data for reference module queries.
type Card struct {
	ArenaID       int               `json:"arenaId"`
	OracleID      string            `json:"oracleId"`
	Name          string            `json:"name"`
	ManaCost      string            `json:"manaCost"`
	CMC           float64           `json:"cmc"`
	TypeLine      string            `json:"typeLine"`
	OracleText    string            `json:"oracleText"`
	Colors        []string          `json:"colors"`
	ColorIdentity []string          `json:"colorIdentity"`
	Legalities    map[string]string `json:"legalities"`
	Rarity        string            `json:"rarity"`
	Set           string            `json:"set"`
	Keywords      []string          `json:"keywords"`
}

//go:embed cards.json
var cardsJSON []byte

// Cards contains all Arena cards indexed by arena_id.
// Decoded from embedded JSON at init time to avoid WASM "function too big" on map literals.
var Cards map[int]Card

func init() {
	var raw map[string]Card
	if err := json.Unmarshal(cardsJSON, &raw); err != nil {
		panic("failed to decode Scryfall cards: " + err.Error())
	}
	Cards = make(map[int]Card, len(raw))
	for k, v := range raw {
		id, _ := strconv.Atoi(k)
		Cards[id] = v
	}
}
