// Code generated by plugins/mtga/tools/17lands-fetch. DO NOT EDIT.
// Source: 17Lands (17lands.com), licensed CC BY 4.0

package data

import (
	_ "embed"
	"encoding/json"

	"github.com/joshsymonds/savecraft.gg/plugins/mtga/reference/draftratings"
)

//go:embed draft_ratings_mkm.json
var draftRatingsJSONMKM []byte

func init() {
	var ratings draftratings.SetRatings
	if err := json.Unmarshal(draftRatingsJSONMKM, &ratings); err != nil {
		panic("failed to decode MKM draft ratings: " + err.Error())
	}
	DraftRatings["MKM"] = ratings
}
