// Code generated by plugins/mtga/tools/17lands-fetch. DO NOT EDIT.
// Source: 17Lands (17lands.com), licensed CC BY 4.0

package data

import (
	_ "embed"
	"encoding/json"

	"github.com/joshsymonds/savecraft.gg/plugins/mtga/reference/draftratings"
)

//go:embed draft_ratings_fdn.json
var draftRatingsJSONFDN []byte

func init() {
	var ratings draftratings.SetRatings
	if err := json.Unmarshal(draftRatingsJSONFDN, &ratings); err != nil {
		panic("failed to decode FDN draft ratings: " + err.Error())
	}
	DraftRatings["FDN"] = ratings
}
