// Code generated by plugins/mtga/tools/17lands-fetch. DO NOT EDIT.
// Source: 17Lands (17lands.com), licensed CC BY 4.0
// Generated: 2026-03-23T08:05:33Z

package data

import "github.com/joshsymonds/savecraft.gg/plugins/mtga/reference/draftratings"

// DraftRatings contains pre-computed draft statistics for all available sets.
// 18 sets from 17Lands public datasets.
// Populated by per-set init() functions in draft_ratings_*_gen.go files.
var DraftRatings = make(map[string]draftratings.SetRatings, 18)
