// Code generated by plugins/mtga/tools/rules-fetch. DO NOT EDIT.
// Source: MTG Comprehensive Rules (Wizards of the Coast) + Scryfall Rulings
// Generated: 2026-03-23T18:31:19Z

package data

import (
	_ "embed"
	"encoding/json"

	"github.com/joshsymonds/savecraft.gg/plugins/mtga/reference/rulessearch"
)

//go:embed rules.json
var rulesJSON []byte

var RulesData rulessearch.RulesData

func init() {
	if err := json.Unmarshal(rulesJSON, &RulesData); err != nil {
		panic("failed to decode rules data: " + err.Error())
	}
}
