name = "savecraft-install"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
INSTALL_URL = "https://install.savecraft.gg"
SERVER_URL = "https://api.savecraft.gg"
REDIRECT_URL = "https://my.savecraft.gg"
APP_NAME = "savecraft"
STATUS_PORT = "9182"

[[r2_buckets]]
binding = "INSTALL"
bucket_name = "savecraft-install"

# ── Production ─────────────────────────────────────────
[env.production]
name = "savecraft-install"
routes = [
  { pattern = "install.savecraft.gg/*", zone_name = "savecraft.gg" },
]

[env.production.vars]
INSTALL_URL = "https://install.savecraft.gg"
SERVER_URL = "https://api.savecraft.gg"
REDIRECT_URL = "https://my.savecraft.gg"
APP_NAME = "savecraft"
STATUS_PORT = "9182"

[[env.production.r2_buckets]]
binding = "INSTALL"
bucket_name = "savecraft-install"

# ── Staging ────────────────────────────────────────────
[env.staging]
name = "savecraft-install-staging"
routes = [
  { pattern = "staging-install.savecraft.gg/*", zone_name = "savecraft.gg" },
]

[env.staging.vars]
INSTALL_URL = "https://staging-install.savecraft.gg"
SERVER_URL = "https://staging-api.savecraft.gg"
REDIRECT_URL = "https://staging-my.savecraft.gg"
APP_NAME = "savecraft-staging"
STATUS_PORT = "9183"

[[env.staging.r2_buckets]]
binding = "INSTALL"
bucket_name = "savecraft-install-staging"
