// Auto-generated by scripts/build-manifests.ts. Do not edit.
// prettier-ignore

export interface ManifestReferenceModule {
  name: string;
  description: string;
  parameters?: Record<string, unknown>;
  section_mappings?: Record<string, string>;
  attribution?: unknown;
  view_default?: string;
}

export interface ManifestData {
  game_id: string;
  name?: string;
  icon?: string;
  sources?: string[];
  description?: string;
  channel?: string;
  coverage?: string;
  limitations?: string[];
  reference?: {
    modules?: Record<string, ManifestReferenceModule>;
  };
}

const DATA: ManifestData[] = [
  {
    "game_id": "clair-obscur",
    "sources": [
      "wasm"
    ],
    "name": "Clair Obscur: Expedition 33",
    "description": "Parses .sav save files from Clair Obscur: Expedition 33",
    "channel": "alpha",
    "coverage": "partial"
  },
  {
    "game_id": "d2r",
    "sources": [
      "wasm"
    ],
    "icon": "icon.png",
    "name": "Diablo II: Resurrected",
    "description": "Parses .d2s character saves and .d2i shared stash from Reign of the Warlock (v105)",
    "channel": "beta",
    "coverage": "partial",
    "limitations": [
      "Only Reign of the Warlock (v105) saves — classic LoD not supported"
    ],
    "reference": {
      "modules": {
        "drop_calc": {
          "name": "Drop Calculator",
          "description": "Compute drop probabilities for any item from any farmable source, accounting for Magic Find, player count, and treasure class mechanics.",
          "attribution": {
            "author": "Josh Symonds",
            "dataSources": [
              {
                "name": "TreasureClassEx.txt",
                "origin": "Diablo II game data tables"
              },
              {
                "name": "ItemRatio.txt",
                "origin": "Diablo II game data tables"
              }
            ]
          },
          "parameters": {
            "area": {
              "description": "Filter to specific area (e.g. 'Pit Level 1', 'Drifter Cavern').",
              "type": "string"
            },
            "boss_only": {
              "default": false,
              "description": "Item mode only: filter to boss monsters.",
              "type": "boolean"
            },
            "difficulty": {
              "default": "hell",
              "description": "Difficulty: 'normal', 'nightmare', 'hell', or 'all'. Default 'hell' for monster mode, 'all' for item mode.",
              "type": "string"
            },
            "item": {
              "description": "Item code or name for reverse lookup (e.g. 'r13', 'Shael', 'xea', 'Serpentskin Armor'). Mutually exclusive with 'monster'.",
              "type": "string"
            },
            "mf": {
              "default": 0,
              "type": "integer"
            },
            "module": {
              "description": "Must be 'drop_calc'",
              "required": true,
              "type": "string"
            },
            "monster": {
              "description": "Monster ID for forward lookup (e.g. 'mephisto', 'andariel'). Mutually exclusive with 'item'.",
              "type": "string"
            },
            "party_size": {
              "default": 1,
              "type": "integer"
            },
            "players": {
              "default": 1,
              "type": "integer"
            },
            "tc_type": {
              "default": -1,
              "description": "Item mode only: 0=regular, 1=champion, 2=unique, 3=quest. -1 for all.",
              "type": "integer"
            }
          },
          "view_default": "visible"
        }
      }
    }
  },
  {
    "game_id": "factorio",
    "sources": [
      "wasm",
      "mod"
    ],
    "icon": "icon.png",
    "name": "Factorio",
    "description": "Lua mod exports game state to JSON; daemon watches script-output and pushes structured save data",
    "channel": "alpha",
    "coverage": "partial",
    "limitations": [
      "Requires the Savecraft Export mod installed in Factorio",
      "Modded recipes and items not yet reflected in reference modules — vanilla data only",
      "Space Age content (planets, platforms, quality) tracked in sections but reference modules are base-game only"
    ],
    "reference": {
      "modules": {
        "blueprint_analyzer": {
          "name": "Blueprint Analyzer",
          "description": "Decode a Factorio blueprint string (version byte + base64 + zlib + JSON), extract the entity list, and evaluate production ratios, belt throughput, module usage, and inserter adequacy against baked-in recipe data."
        },
        "evolution_tracker": {
          "name": "Evolution & Threat Tracker",
          "description": "Analyze biter evolution and defense posture from save data. Returns evolution factor with source breakdown, enemy tier prediction, spawn weight distribution, and defense summary including turret counts, walls, and nearby enemy bases.",
          "view_default": "visible",
          "section_mappings": {
            "defenses": "defenses"
          }
        },
        "module_optimizer": {
          "name": "Module & Beacon Optimizer",
          "description": "Given a machine type, recipe, and production target, recommend optimal module and beacon configuration. Compares speed, productivity, and efficiency module combinations with beacon count trade-offs."
        },
        "oil_balancer": {
          "name": "Oil Processing Balancer",
          "description": "Given target fluid products and rates, compute optimal refinery and cracking plant counts for basic, advanced, or coal liquefaction processing. Returns machine counts, water and crude input rates, and surplus byproducts. Pass save_id to compare against your actual factory and identify bottlenecks.",
          "section_mappings": {
            "actual_flow": "production_flow",
            "existing_setup": "machines"
          }
        },
        "power_calculator": {
          "name": "Power Generation Calculator",
          "description": "Given power demand in MW, compute optimal generation setup for steam (boiler/engine ratios), solar (panel/accumulator ratios), or nuclear (reactor neighbor bonuses, heat exchanger and turbine counts, fuel cell consumption)."
        },
        "quality_calculator": {
          "name": "Quality Tier Calculator",
          "description": "Compute quality tier probability distributions from module setup, including geometric re-roll chains. Calculate expected materials per legendary output and recycler loop efficiency for Space Age quality mechanics."
        },
        "ratio_calculator": {
          "name": "Production Ratio Calculator",
          "description": "Given a target item and production rate, compute the full dependency tree: machine counts by tier, belt lane requirements, raw material input rates. Accounts for module effects, beacon transmission (distribution_efficiency / sqrt(n)), and productivity bonuses. Pass save_id to compare against your actual factory and identify bottlenecks.",
          "parameters": {
            "assembler_tier": {
              "default": "assembling-machine-2",
              "description": "Preferred assembler (e.g. 'assembling-machine-3')",
              "type": "string"
            },
            "beacon_count": {
              "default": 0,
              "description": "Number of beacons affecting each machine",
              "type": "integer"
            },
            "beacon_modules": {
              "description": "Module names in each beacon (e.g. ['speed-module-3', 'speed-module-3'])",
              "type": "array"
            },
            "modules": {
              "description": "Module names in machine slots (e.g. ['productivity-module-3', 'productivity-module-3'])",
              "type": "array"
            },
            "recipe": {
              "description": "Explicit recipe name for the target item. Required when multiple recipes produce the same item (e.g. 'solid-fuel-from-light-oil'). Use recipe_lookup with product query to find options.",
              "type": "string"
            },
            "recipe_overrides": {
              "description": "Map of item → recipe name for intermediate products with multiple recipes (e.g. {\"solid-fuel\": \"solid-fuel-from-light-oil\", \"copper-plate\": \"casting-copper\"})",
              "type": "object"
            },
            "target_item": {
              "description": "Item to produce (e.g. 'electronic-circuit')",
              "required": true,
              "type": "string"
            },
            "target_rate": {
              "default": 60,
              "description": "Target production rate in items per minute",
              "type": "number"
            }
          },
          "view_default": "visible",
          "section_mappings": {
            "actual_flow": "production_flow",
            "existing_machines": "machines"
          }
        },
        "recipe_lookup": {
          "name": "Recipe & Item Lookup",
          "description": "Look up any item, recipe, entity, or technology by exact name. Supports reverse lookups (what uses X, what produces Y). Returns exact ingredients, products, craft time, machine category, and allowed modules. Prevents hallucination on recipe data.",
          "parameters": {
            "machine": {
              "description": "Look up a crafting machine's stats and categories (e.g. 'assembling-machine-3')",
              "type": "string"
            },
            "name": {
              "description": "Recipe or item name to look up (e.g. 'electronic-circuit')",
              "type": "string"
            },
            "product": {
              "description": "Find all recipes that produce this item (e.g. 'plastic-bar')",
              "type": "string"
            },
            "tech": {
              "description": "Look up a technology's prerequisites, costs, and unlocked recipes (e.g. 'advanced-oil-processing')",
              "type": "string"
            },
            "usage": {
              "description": "Find all recipes that use this item as an ingredient (e.g. 'copper-cable')",
              "type": "string"
            }
          }
        },
        "tech_tree_navigator": {
          "name": "Tech Tree Navigator",
          "description": "Traverse technology prerequisite chains with total science pack costs. Given a target technology and completed research, compute the optimal research path and total cost by pack type."
        },
        "train_throughput": {
          "name": "Train Throughput Calculator",
          "description": "Compute train network throughput between stations given train composition, fuel type, distance, inserter configuration, and signal spacing. Returns round-trip time breakdown and bottleneck identification."
        }
      }
    }
  },
  {
    "game_id": "mtga",
    "sources": [
      "wasm"
    ],
    "icon": "icon.png",
    "name": "Magic: The Gathering Arena",
    "description": "Parses Player.log for collection, decks, match history, play-by-play game logs, drafts, rank, and inventory",
    "channel": "beta",
    "coverage": "partial",
    "limitations": [
      "Requires 'Detailed Logs' enabled in MTGA settings",
      "Log clears on game restart — only current session data available",
      "Card names require Scryfall data update after new set releases"
    ],
    "reference": {
      "modules": {
        "card_search": {
          "name": "Card Search",
          "description": "Search Magic: The Gathering cards by name, color, type, mana cost, oracle text, and format legality using Scryfall data.",
          "attribution": {
            "author": "Josh Symonds",
            "dataSources": [
              {
                "name": "Scryfall Oracle Cards",
                "origin": "Scryfall bulk data (scryfall.com), card data copyright Wizards of the Coast"
              }
            ]
          },
          "parameters": {
            "cmc": {
              "description": "Mana value",
              "type": "integer"
            },
            "cmc_op": {
              "description": "Comparison operator: '<=', '=', '>=' (default '=')",
              "type": "string"
            },
            "colors": {
              "description": "Color identity filter (e.g., 'BR' for black-red, 'C' for colorless)",
              "type": "string"
            },
            "format": {
              "description": "Format legality (e.g., 'standard', 'historic', 'modern')",
              "type": "string"
            },
            "limit": {
              "description": "Max results (default 20)",
              "type": "integer"
            },
            "name": {
              "description": "Card name (substring, case-insensitive)",
              "type": "string"
            },
            "rarity": {
              "description": "Rarity: 'common', 'uncommon', 'rare', 'mythic'",
              "type": "string"
            },
            "set": {
              "description": "Set code (e.g., 'dmu', 'one')",
              "type": "string"
            },
            "sort": {
              "description": "'name' (default) or 'cmc'",
              "type": "string"
            },
            "text": {
              "description": "Oracle text substring",
              "type": "string"
            },
            "type": {
              "description": "Type line substring (e.g., 'creature', 'legendary')",
              "type": "string"
            }
          }
        },
        "collection_diff": {
          "name": "Collection Diff",
          "description": "Calculate the wildcard cost to complete a target decklist given a player's current collection. Returns missing cards grouped by rarity with total wildcard cost.",
          "attribution": {
            "author": "Josh Symonds"
          },
          "parameters": {
            "collection": {
              "description": "Owned cards: [{arenaId, count}]",
              "type": "array"
            },
            "target_deck": {
              "description": "Target deck: [{name, count}]",
              "type": "array"
            }
          }
        },
        "draft_ratings": {
          "name": "Draft Ratings",
          "description": "Per-card draft performance statistics from millions of real games across all available sets. Provides GIH WR, OHWR, IWD, ALSA, ATA with game counts, overall and by 2-color archetype.",
          "attribution": {
            "author": "Josh Symonds",
            "dataSources": [
              {
                "name": "17Lands Public Datasets",
                "origin": "17lands.com, licensed CC BY 4.0"
              }
            ]
          },
          "parameters": {
            "card": {
              "description": "Single card lookup (substring, case-insensitive). Returns full stats with all color breakdowns.",
              "type": "string"
            },
            "cards": {
              "description": "Compare 2-5 specific cards side-by-side: ['Card A', 'Card B']. Best for draft pick decisions.",
              "type": "array"
            },
            "colors": {
              "description": "Color pair context (e.g., 'UB' for Dimir). Filters to archetype-specific stats.",
              "type": "string"
            },
            "limit": {
              "description": "Max results for leaderboard mode. Triggers sorted table output.",
              "type": "integer"
            },
            "offset": {
              "description": "Pagination offset for leaderboard mode.",
              "type": "integer"
            },
            "set": {
              "description": "Set code (required, e.g., 'DSK'). Omit to list available sets.",
              "type": "string"
            },
            "sort": {
              "description": "'gihwr' (default), 'ohwr', 'iwd', 'alsa', 'ata'. Used with limit for leaderboards.",
              "type": "string"
            }
          }
        },
        "mana_base": {
          "name": "Mana Base",
          "description": "Analyze colored mana source requirements for a deck using Frank Karsten's methodology. Returns the number of colored sources needed per color to achieve ~89%+ on-curve consistency.",
          "attribution": {
            "author": "Josh Symonds"
          },
          "parameters": {
            "deck": {
              "description": "Deck list: [{name, count}]. Card names resolved to mana costs via Scryfall data.",
              "type": "array"
            },
            "deck_size": {
              "description": "40 (limited), 60 (standard/modern, default), 80 (Yorion), or 99 (Commander).",
              "type": "integer"
            }
          }
        },
        "rules_search": {
          "name": "Rules Search",
          "description": "Search the MTG Comprehensive Rules and official per-card rulings from Scryfall. Query by rule number, keyword, or card name.",
          "attribution": {
            "author": "Josh Symonds",
            "dataSources": [
              {
                "name": "MTG Comprehensive Rules",
                "origin": "Wizards of the Coast"
              },
              {
                "name": "Scryfall Card Rulings",
                "origin": "Scryfall (scryfall.com), rulings copyright Wizards of the Coast"
              }
            ]
          },
          "parameters": {
            "card": {
              "description": "Card name for official Scryfall rulings (e.g., 'Sheoldred').",
              "type": "string"
            },
            "keyword": {
              "description": "Keyword search across all rules (e.g., 'deathtouch', 'trample').",
              "type": "string"
            },
            "limit": {
              "description": "Max results (default 20).",
              "type": "integer"
            },
            "rule": {
              "description": "Rule number (e.g., '702.2' for deathtouch). Returns rule + subrules + cross-references.",
              "type": "string"
            },
            "topic": {
              "description": "Multi-word topic search (e.g., 'combat damage', 'state-based actions').",
              "type": "string"
            }
          }
        }
      }
    }
  },
  {
    "game_id": "rimworld",
    "sources": [
      "mod"
    ],
    "icon": "icon.png",
    "name": "RimWorld",
    "description": "In-game Harmony mod pushes full colony state on every save — colonists, resources, research, mood, health, defenses, farming, factions, and more",
    "channel": "alpha",
    "coverage": "full",
    "limitations": [
      "Modded content (added stats, custom hediffs) not yet parsed — vanilla data only",
      "Large colonies (30+ colonists) may cause brief frame hitch during data collection"
    ],
    "reference": {
      "modules": {
        "combat": {
          "name": "Weapon & Armor Combat Calculator",
          "description": "Compute ranged DPS at any distance (accuracy interpolation across 4 range breakpoints), melee true DPS via weighted verb selection, and armor damage reduction expected values.",
          "parameters": {
            "armor": {
              "default": 0,
              "description": "Target armor rating (0-2, e.g. 1.0 = flak vest)",
              "type": "number"
            },
            "range": {
              "default": 12,
              "description": "Distance in tiles for ranged DPS",
              "type": "number"
            },
            "weapon": {
              "description": "Weapon name (ranged or melee)",
              "type": "string"
            }
          },
          "view_default": "visible"
        },
        "crops": {
          "name": "Crop Production Optimizer",
          "description": "Compute nutrition/day/tile and silver/day/tile for any crop on any soil type, accounting for fertility sensitivity, temperature growth curves, and rest periods. Includes tiles-per-colonist estimates.",
          "parameters": {
            "colonists": {
              "default": 1,
              "description": "Number of colonists to feed (for tiles calculation)",
              "type": "integer"
            },
            "crop": {
              "description": "Crop name (e.g. rice, potato, corn, strawberry, devilstrand)",
              "type": "string"
            },
            "soil": {
              "default": "soil",
              "description": "Soil type (e.g. soil, rich soil, gravel, hydroponics)",
              "type": "string"
            },
            "temperature": {
              "default": 20,
              "description": "Average temperature in C",
              "type": "number"
            }
          },
          "view_default": "visible"
        },
        "drugs": {
          "name": "Drug Economy & Addiction Analyzer",
          "description": "Compute silver/day for drug production chains (crop to processed drug), silver per raw material, and addiction risk data including tolerance thresholds and safe dose intervals.",
          "parameters": {
            "drug": {
              "description": "Drug name (e.g. flake, yayo, beer, smokeleaf joint). Omit to list all.",
              "type": "string"
            },
            "soil": {
              "description": "Soil type for production chain (e.g. soil, rich soil, gravel)",
              "type": "string"
            },
            "temperature": {
              "description": "Average temperature for production chain calculation",
              "type": "number"
            }
          },
          "view_default": "visible"
        },
        "genes": {
          "name": "Gene Metabolism & Xenotype Builder",
          "description": "Validate xenogerm builds against complexity and metabolism budgets, detect gene conflicts via exclusion tags, and tally archite capsule requirements.",
          "parameters": {
            "category": {
              "description": "Filter genes by category",
              "type": "string"
            },
            "genes": {
              "description": "Array of gene names to validate as a build",
              "type": "array"
            },
            "max_complexity": {
              "default": 6,
              "description": "Maximum allowed complexity",
              "type": "integer"
            },
            "min_metabolism": {
              "default": -5,
              "description": "Minimum allowed metabolism",
              "type": "integer"
            },
            "search": {
              "description": "Search genes by name or description substring",
              "type": "string"
            }
          },
          "view_default": "visible"
        },
        "materials": {
          "name": "Material & Item Stat Lookup",
          "description": "Look up final stats for any item-material-quality combination using the three-layer multiplication: base stat, material factor, and quality multiplier.",
          "parameters": {
            "material": {
              "description": "Material name (e.g. steel, plasteel, hyperweave). Omit to list all.",
              "type": "string"
            },
            "quality": {
              "default": "normal",
              "description": "Quality level: awful, poor, normal, good, excellent, masterwork, legendary",
              "type": "string"
            }
          },
          "view_default": "visible"
        },
        "raids": {
          "name": "Colony Wealth & Raid Threat Estimator",
          "description": "Convert colony wealth to expected raid points using the piecewise wealth curve from StorytellerUtility, with per-colonist point scaling and building wealth at 50% factor.",
          "parameters": {
            "building_wealth": {
              "default": 0,
              "description": "Total building wealth (counted at 50%)",
              "type": "number"
            },
            "colonists": {
              "default": 1,
              "description": "Number of colonists",
              "type": "integer"
            },
            "item_wealth": {
              "description": "Total item/silver wealth",
              "type": "number"
            }
          },
          "view_default": "visible"
        },
        "research": {
          "name": "Research Tree & Crafting Chain Navigator",
          "description": "Traverse research prerequisite chains with total costs, applying tech level multipliers for tribal starts. Includes research speed estimation.",
          "parameters": {
            "colony_tech": {
              "default": "Industrial",
              "description": "Colony tech level for cost multipliers",
              "type": "string"
            },
            "project": {
              "description": "Research project name. Omit to list all.",
              "type": "string"
            }
          },
          "view_default": "visible"
        },
        "surgery": {
          "name": "Surgery Success Calculator",
          "description": "Calculate true surgery success probability from surgeon skill, bed type, quality, room cleanliness, medicine, and operation difficulty. Implements the exact formula from Recipe_Surgery.CheckSurgeryFail.",
          "parameters": {
            "bed": {
              "description": "Bed type: sleeping spot, bed, hospital bed, ancient bed, rusted bed",
              "type": "string"
            },
            "bed_factor": {
              "description": "Direct bed factor override (alternative to bed name)",
              "type": "number"
            },
            "cleanliness": {
              "default": 0,
              "description": "Room cleanliness stat (-5 to +5, 0 = clean)",
              "type": "number"
            },
            "difficulty": {
              "default": 1,
              "description": "Operation's surgerySuccessChanceFactor (1.0 = standard)",
              "type": "number"
            },
            "glow": {
              "default": 1,
              "description": "Light level (0 = dark, 1 = fully lit)",
              "type": "number"
            },
            "inspired": {
              "default": false,
              "description": "Whether the surgeon has Inspired Surgery",
              "type": "boolean"
            },
            "manipulation": {
              "default": 1,
              "description": "Surgeon's Manipulation capacity (0-1+, 1.0 = healthy)",
              "type": "number"
            },
            "medicine": {
              "description": "Medicine type: none, herbal, industrial/medicine, glitterworld",
              "type": "string"
            },
            "medicine_potency": {
              "description": "Direct medicine potency override (0=none, 0.6=herbal, 1.0=industrial, 1.6=glitterworld)",
              "type": "number"
            },
            "outdoors": {
              "default": false,
              "description": "Whether surgery is performed outdoors",
              "type": "boolean"
            },
            "quality": {
              "default": "normal",
              "description": "Bed quality: awful, poor, normal, good, excellent, masterwork, legendary",
              "type": "string"
            },
            "sight": {
              "default": 1,
              "description": "Surgeon's Sight capacity (0-1+, 1.0 = healthy)",
              "type": "number"
            },
            "skill": {
              "default": 10,
              "description": "Surgeon's Medicine skill level (0-20)",
              "type": "integer"
            }
          },
          "view_default": "visible"
        }
      }
    }
  },
  {
    "game_id": "sdv",
    "sources": [
      "wasm"
    ],
    "icon": "icon.png",
    "name": "Stardew Valley",
    "description": "Parses Stardew Valley 1.6 save files into structured game state",
    "channel": "beta",
    "coverage": "partial",
    "limitations": [
      "Only Stardew Valley 1.6+ saves supported",
      "Directory-based save discovery requires daemon enhancement (pending)"
    ],
    "reference": {
      "modules": {
        "crop_planner": {
          "name": "Crop Planner",
          "description": "Look up crop growth data, profitability, fertilizer effects, and artisan goods values. Use 'crop' for a specific crop's full analysis, or 'season' for all crops ranked by gold/day.",
          "attribution": {
            "author": "Josh Symonds",
            "dataSources": [
              {
                "name": "Crop_data",
                "origin": "Stardew Valley 1.6 game data via wiki"
              },
              {
                "name": "Objects",
                "origin": "Stardew Valley game data via aftonsteps/stardewdata (MIT)"
              }
            ]
          },
          "parameters": {
            "crop": {
              "description": "Crop name for forward lookup (e.g. 'Pumpkin', 'Starfruit'). Returns growth time, seasons, sell prices, gold/day, and artisan goods values.",
              "type": "string"
            },
            "season": {
              "description": "Season name for reverse lookup ('Spring', 'Summer', 'Fall', 'Winter'). Returns all crops for that season ranked by gold/day.",
              "type": "string"
            }
          }
        },
        "gift_preferences": {
          "name": "Gift Preferences",
          "description": "Look up NPC gift preferences by villager name or item name. Includes universal and personal taste data from Stardew Valley 1.6.",
          "attribution": {
            "author": "Josh Symonds",
            "dataSources": [
              {
                "name": "NPCGiftTastes",
                "origin": "Stardew Valley 1.6 game data via wiki"
              },
              {
                "name": "Objects",
                "origin": "Stardew Valley game data via aftonsteps/stardewdata (MIT)"
              }
            ]
          },
          "parameters": {
            "item": {
              "description": "Item name for reverse lookup (e.g. 'Diamond', 'Pumpkin', 'Prismatic Shard'). Returns which NPCs love/like/dislike/hate it.",
              "type": "string"
            },
            "npc": {
              "description": "NPC name for forward lookup (e.g. 'Abigail', 'Sebastian'). Returns loved/liked/disliked/hated items.",
              "type": "string"
            }
          }
        }
      }
    }
  },
  {
    "game_id": "wow",
    "sources": [
      "api"
    ],
    "icon": "icon.png",
    "name": "World of Warcraft",
    "description": "Character profiles via Battle.net API with Raider.io ranking enrichment",
    "channel": "beta",
    "coverage": "partial",
    "limitations": [
      "Character data updates on logout, not in real-time",
      "Bag and bank inventory not available (API limitation)",
      "Combat performance data not included (see Warcraft Logs integration roadmap)"
    ]
  }
];

/** All game manifests indexed by game_id. O(1) lookup. */
export const MANIFESTS: ReadonlyMap<string, ManifestData> = new Map(
  DATA.map((m) => [m.game_id, m] as const),
);

/** All game manifests as an array, for iteration. */
export const MANIFEST_LIST: readonly ManifestData[] = DATA;
