// AUTO-GENERATED by stellaris-datagen — do not edit.

/// A Stellaris technology definition.
#[derive(Debug, Clone)]
pub struct Tech {
    pub key: &'static str,
    pub area: &'static str,
    pub tier: i32,
    pub cost: i32,
    pub category: &'static str,
    pub prerequisites: &'static [&'static str],
    pub is_start_tech: bool,
    pub is_repeatable: bool,
    pub weight: i32,
}

/// A Stellaris building definition.
#[derive(Debug, Clone)]
pub struct Building {
    pub key: &'static str,
    pub category: &'static str,
    pub base_buildtime: i32,
    pub is_capital: bool,
}
