package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func genMedical(r *Resolver, outputDir string) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by datagen; DO NOT EDIT.\n\n")
	buf.WriteString("package data\n\n")

	// Generate medicines
	buf.WriteString("// Medicines is all medicine items with their medical potency.\n")
	buf.WriteString("var Medicines = []Medicine{\n")
	r.IterateDefs("ThingDef", func(defName string, el *Element) {
		statBases := findChildElement(el, "statBases")
		if statBases == nil {
			return
		}
		potencyVal := floatOf(statBases, "MedicalPotency", 0)
		if potencyVal == 0 {
			return
		}
		label := ""
		if l := findChildElement(el, "label"); l != nil {
			label = strings.TrimSpace(l.Text)
		}
		fmt.Fprintf(&buf, "\t{DefName: %q, Label: %q, MedicalPotency: %s},\n",
			defName, label, fmtFloat(potencyVal))
	})
	buf.WriteString("}\n\n")

	// Generate beds with surgery success chance factor
	buf.WriteString("// Beds is all bed/sleeping items with their surgery success chance factor.\n")
	buf.WriteString("var Beds = []Bed{\n")
	r.IterateDefs("ThingDef", func(defName string, el *Element) {
		statBases := findChildElement(el, "statBases")
		if statBases == nil {
			return
		}
		factorVal := floatOf(statBases, "SurgerySuccessChanceFactor", 0)
		if factorVal == 0 {
			return
		}
		label := ""
		if l := findChildElement(el, "label"); l != nil {
			label = strings.TrimSpace(l.Text)
		}
		fmt.Fprintf(&buf, "\t{DefName: %q, Label: %q, SurgerySuccessChanceFactor: %s},\n",
			defName, label, fmtFloat(factorVal))
	})
	buf.WriteString("}\n")

	return os.WriteFile(filepath.Join(outputDir, "medical_gen.go"), []byte(buf.String()), 0644)
}
