package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func genGenes(r *Resolver, outputDir string) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by datagen; DO NOT EDIT.\n\n")
	buf.WriteString("package data\n\n")

	buf.WriteString("// Genes is all gene definitions with build-relevant properties.\n")
	buf.WriteString("var Genes = []Gene{\n")

	r.IterateDefs("GeneDef", func(defName string, el *Element) {
		label := textOf(el, "label")
		cpx := intOf(el, "biostatCpx", 0)
		met := intOf(el, "biostatMet", 0)
		arc := intOf(el, "biostatArc", 0)
		category := textOf(el, "displayCategory")
		desc := textOf(el, "description")
		if len(desc) > 200 {
			desc = desc[:200] + "..."
		}

		// Exclusion tags
		var tags []string
		tagsEl := findChildElement(el, "exclusionTags")
		if tagsEl != nil {
			for _, li := range findChildren(tagsEl, "li") {
				tags = append(tags, strings.TrimSpace(li.Text))
			}
		}

		tagsStr := "nil"
		if len(tags) > 0 {
			var parts []string
			for _, t := range tags {
				parts = append(parts, fmt.Sprintf("%q", t))
			}
			tagsStr = "[]string{" + strings.Join(parts, ", ") + "}"
		}

		fmt.Fprintf(&buf, "\t{DefName: %q, Label: %q, Description: %q, Complexity: %d, MetabolismOffset: %d, ArchiteCost: %d, Category: %q, ExclusionTags: %s},\n",
			defName, label, desc, cpx, met, arc, category, tagsStr)
	})
	buf.WriteString("}\n")

	return os.WriteFile(filepath.Join(outputDir, "genes_gen.go"), []byte(buf.String()), 0644)
}
