package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func genCombat(r *Resolver, outputDir string) error {
	// First pass: build projectile damage map (defName → damage, AP)
	type projData struct {
		damage float64
		ap     float64
	}
	projectiles := make(map[string]projData)
	r.IterateDefs("ThingDef", func(defName string, el *Element) {
		proj := findChildElement(el, "projectile")
		if proj == nil {
			return
		}
		damage := floatOf(proj, "damageAmountBase", 0)
		ap := floatOf(proj, "armorPenetrationBase", 0)
		if damage > 0 {
			projectiles[defName] = projData{damage: damage, ap: ap}
		}
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by datagen; DO NOT EDIT.\n\n")
	buf.WriteString("package data\n\n")

	// Generate ranged weapons
	buf.WriteString("// RangedWeapons is all ranged weapons with combat-relevant stats.\n")
	buf.WriteString("var RangedWeapons = []RangedWeapon{\n")
	r.IterateDefs("ThingDef", func(defName string, el *Element) {
		verbs := findChildElement(el, "verbs")
		if verbs == nil {
			return
		}
		// Find the first Verb_Shoot verb
		var verb *Element
		for _, li := range findChildren(verbs, "li") {
			vc := findChildElement(li, "verbClass")
			if vc != nil && strings.Contains(strings.TrimSpace(vc.Text), "Verb_Shoot") {
				verb = li
				break
			}
		}
		if verb == nil {
			return
		}

		projDef := textOf(verb, "defaultProjectile")
		proj, ok := projectiles[projDef]
		if !ok || proj.damage <= 0 {
			return
		}

		statBases := findChildElement(el, "statBases")
		if statBases == nil {
			return
		}

		label := textOf(el, "label")
		accTouch := floatOf(statBases, "AccuracyTouch", 0)
		accShort := floatOf(statBases, "AccuracyShort", 0)
		accMed := floatOf(statBases, "AccuracyMedium", 0)
		accLong := floatOf(statBases, "AccuracyLong", 0)
		cooldown := floatOf(statBases, "RangedWeapon_Cooldown", 0)
		warmup := floatOf(verb, "warmupTime", 0)
		burstCount := intOf(verb, "burstShotCount", 1)
		ticksBetween := intOf(verb, "ticksBetweenBurstShots", 0)
		rng := floatOf(verb, "range", 0)

		fmt.Fprintf(&buf, "\t{DefName: %q, Label: %q, DamagePerShot: %s, ArmorPenetration: %s, BurstShotCount: %d, WarmupTime: %s, Cooldown: %s, TicksBetweenBurstShots: %d, Range: %s, AccuracyTouch: %s, AccuracyShort: %s, AccuracyMedium: %s, AccuracyLong: %s},\n",
			defName, label, fmtFloat(proj.damage), fmtFloat(proj.ap),
			burstCount, fmtFloat(warmup), fmtFloat(cooldown), ticksBetween, fmtFloat(rng),
			fmtFloat(accTouch), fmtFloat(accShort), fmtFloat(accMed), fmtFloat(accLong))
	})
	buf.WriteString("}\n\n")

	// Generate melee weapons (things with tools but no ranged verbs, or dedicated melee weapons)
	buf.WriteString("// MeleeWeapons is all melee weapons with their tool/verb stats.\n")
	buf.WriteString("var MeleeWeapons = []MeleeWeapon{\n")
	r.IterateDefs("ThingDef", func(defName string, el *Element) {
		tools := findChildElement(el, "tools")
		if tools == nil {
			return
		}
		// Skip if it has Verb_Shoot (ranged weapon with melee fallback)
		verbs := findChildElement(el, "verbs")
		if verbs != nil {
			for _, li := range findChildren(verbs, "li") {
				vc := findChildElement(li, "verbClass")
				if vc != nil && strings.Contains(strings.TrimSpace(vc.Text), "Verb_Shoot") {
					return
				}
			}
		}
		// Must be tagged as a weapon (has weaponTags or weaponClasses)
		if findChildElement(el, "weaponTags") == nil && findChildElement(el, "weaponClasses") == nil {
			return
		}

		label := textOf(el, "label")
		var toolEntries []string
		for _, li := range findChildren(tools, "li") {
			toolLabel := textOf(li, "label")
			power := floatOf(li, "power", 0)
			cd := floatOf(li, "cooldownTime", 0)
			ap := floatOf(li, "armorPenetration", 0)
			if power <= 0 || cd <= 0 {
				continue
			}

			// Get damage capacities
			var caps []string
			capsEl := findChildElement(li, "capacities")
			if capsEl != nil {
				for _, capLi := range findChildren(capsEl, "li") {
					caps = append(caps, strings.TrimSpace(capLi.Text))
				}
			}

			capsStr := "nil"
			if len(caps) > 0 {
				var parts []string
				for _, c := range caps {
					parts = append(parts, fmt.Sprintf("%q", c))
				}
				capsStr = "[]string{" + strings.Join(parts, ", ") + "}"
			}

			toolEntries = append(toolEntries, fmt.Sprintf("{Label: %q, Power: %s, Cooldown: %s, ArmorPenetration: %s, Capacities: %s}",
				toolLabel, fmtFloat(power), fmtFloat(cd), fmtFloat(ap), capsStr))
		}
		if len(toolEntries) == 0 {
			return
		}

		fmt.Fprintf(&buf, "\t{DefName: %q, Label: %q, Tools: []MeleeToolData{%s}},\n",
			defName, label, strings.Join(toolEntries, ", "))
	})
	buf.WriteString("}\n")

	return os.WriteFile(filepath.Join(outputDir, "weapons_gen.go"), []byte(buf.String()), 0644)
}

func intOf(el *Element, tag string, defaultVal int) int {
	c := findChildElement(el, tag)
	if c == nil {
		return defaultVal
	}
	s := strings.TrimSpace(c.Text)
	if s == "" {
		return defaultVal
	}
	var v int
	_, err := fmt.Sscanf(s, "%d", &v)
	if err != nil {
		return defaultVal
	}
	return v
}
