package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func genResearch(r *Resolver, outputDir string) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by datagen; DO NOT EDIT.\n\n")
	buf.WriteString("package data\n\n")

	buf.WriteString("// ResearchProjects is all research projects with their costs and prerequisites.\n")
	buf.WriteString("var ResearchProjects = []ResearchProject{\n")

	r.IterateDefs("ResearchProjectDef", func(defName string, el *Element) {
		label := textOf(el, "label")
		baseCost := floatOf(el, "baseCost", 0)
		techLevel := textOf(el, "techLevel")
		reqBench := textOf(el, "requiredResearchBuilding")

		// Prerequisites
		var prereqs []string
		prereqsEl := findChildElement(el, "prerequisites")
		if prereqsEl != nil {
			for _, li := range findChildren(prereqsEl, "li") {
				prereqs = append(prereqs, strings.TrimSpace(li.Text))
			}
		}

		prereqsStr := "nil"
		if len(prereqs) > 0 {
			var parts []string
			for _, p := range prereqs {
				parts = append(parts, fmt.Sprintf("%q", p))
			}
			prereqsStr = "[]string{" + strings.Join(parts, ", ") + "}"
		}

		fmt.Fprintf(&buf, "\t{DefName: %q, Label: %q, BaseCost: %s, TechLevel: %q, RequiredBench: %q, Prerequisites: %s},\n",
			defName, label, fmtFloat(baseCost), techLevel, reqBench, prereqsStr)
	})
	buf.WriteString("}\n")

	return os.WriteFile(filepath.Join(outputDir, "research_gen.go"), []byte(buf.String()), 0644)
}
