package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func genCrops(r *Resolver, outputDir string) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by datagen; DO NOT EDIT.\n\n")
	buf.WriteString("package data\n\n")

	// Build a map of harvested item defName → nutrition and market value.
	// These come from ThingDefs that are food items (have Nutrition in statBases).
	itemNutrition := make(map[string]float64)
	itemMarketValue := make(map[string]float64)
	r.IterateDefs("ThingDef", func(defName string, el *Element) {
		statBases := findChildElement(el, "statBases")
		if statBases == nil {
			return
		}
		if n := findChildElement(statBases, "Nutrition"); n != nil {
			itemNutrition[defName] = parseFloat(n.Text, 0)
		}
		if v := findChildElement(statBases, "MarketValue"); v != nil {
			itemMarketValue[defName] = parseFloat(v.Text, 0)
		}
	})

	// Generate cultivated plants
	buf.WriteString("// Plants is all cultivated plants with their growth parameters.\n")
	buf.WriteString("var Plants = []Plant{\n")

	r.IterateDefs("ThingDef", func(defName string, el *Element) {
		plant := findChildElement(el, "plant")
		if plant == nil {
			return
		}
		// Must have sowTags to be a cultivated plant
		sowTags := findChildElement(plant, "sowTags")
		if sowTags == nil {
			return
		}

		label := textOf(el, "label")
		growDays := floatOf(plant, "growDays", 0)
		harvestYield := floatOf(plant, "harvestYield", 0)
		fertSens := floatOf(plant, "fertilitySensitivity", 1.0) // default from PlantBaseNonEdible
		harvestedItem := textOf(plant, "harvestedThingDef")

		if growDays <= 0 || harvestYield <= 0 || harvestedItem == "" {
			return
		}

		// Collect sow tags
		var tags []string
		for _, li := range findChildren(sowTags, "li") {
			tags = append(tags, strings.TrimSpace(li.Text))
		}

		nutrition := itemNutrition[harvestedItem]
		marketValue := itemMarketValue[harvestedItem]

		fmt.Fprintf(&buf, "\t{DefName: %q, Label: %q, GrowDays: %s, HarvestYield: %s, HarvestedItem: %q, FertilitySensitivity: %s, NutritionPerUnit: %s, MarketValuePerUnit: %s, SowTags: []string{",
			defName, label, fmtFloat(growDays), fmtFloat(harvestYield),
			harvestedItem, fmtFloat(fertSens), fmtFloat(nutrition), fmtFloat(marketValue))
		for i, tag := range tags {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(&buf, "%q", tag)
		}
		buf.WriteString("}},\n")
	})
	buf.WriteString("}\n\n")

	// Generate soils with fertility values
	buf.WriteString("// Soils is terrain types with non-zero fertility.\n")
	buf.WriteString("var Soils = []Soil{\n")
	r.IterateDefs("TerrainDef", func(defName string, el *Element) {
		fert := floatOf(el, "fertility", 0)
		if fert <= 0 {
			return
		}
		label := textOf(el, "label")
		fmt.Fprintf(&buf, "\t{DefName: %q, Label: %q, Fertility: %s},\n",
			defName, label, fmtFloat(fert))
	})
	buf.WriteString("}\n")

	return os.WriteFile(filepath.Join(outputDir, "crops_gen.go"), []byte(buf.String()), 0644)
}

func textOf(el *Element, tag string) string {
	c := findChildElement(el, tag)
	if c == nil {
		return ""
	}
	return strings.TrimSpace(c.Text)
}

func floatOf(el *Element, tag string, defaultVal float64) float64 {
	c := findChildElement(el, tag)
	if c == nil {
		return defaultVal
	}
	return parseFloat(c.Text, defaultVal)
}

func findChildren(el *Element, tag string) []*Element {
	var out []*Element
	for _, c := range el.Children {
		if c.Tag == tag {
			out = append(out, c)
		}
	}
	return out
}

func parseFloat(s string, defaultVal float64) float64 {
	s = strings.TrimSpace(s)
	if s == "" {
		return defaultVal
	}
	var f float64
	_, err := fmt.Sscanf(s, "%f", &f)
	if err != nil {
		return defaultVal
	}
	return f
}

func fmtFloat(f float64) string {
	s := fmt.Sprintf("%g", f)
	// Ensure it has a decimal point for Go float literals
	if !strings.Contains(s, ".") && !strings.Contains(s, "e") {
		s += ".0"
	}
	return s
}
