package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func genMaterials(r *Resolver, outputDir string) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by datagen; DO NOT EDIT.\n\n")
	buf.WriteString("package data\n\n")

	buf.WriteString("// Materials is all stuff/material types with their stat factors.\n")
	buf.WriteString("var Materials = []Material{\n")

	r.IterateDefs("ThingDef", func(defName string, el *Element) {
		stuffProps := findChildElement(el, "stuffProps")
		if stuffProps == nil {
			return
		}

		statBases := findChildElement(el, "statBases")
		if statBases == nil {
			return
		}

		label := textOf(el, "label")
		marketValue := floatOf(statBases, "MarketValue", 0)
		sharpArmor := floatOf(statBases, "StuffPower_Armor_Sharp", 0)
		bluntArmor := floatOf(statBases, "StuffPower_Armor_Blunt", 0)
		heatArmor := floatOf(statBases, "StuffPower_Armor_Heat", 0)
		coldInsul := floatOf(statBases, "StuffPower_Insulation_Cold", 0)
		heatInsul := floatOf(statBases, "StuffPower_Insulation_Heat", 0)
		sharpDmg := floatOf(statBases, "SharpDamageMultiplier", 1.0)
		bluntDmg := floatOf(statBases, "BluntDamageMultiplier", 1.0)

		// Get stuffProps stat factors and offsets
		hpFactor := 1.0
		beautyFactor := 1.0
		beautyOffset := 0.0

		statFactors := findChildElement(stuffProps, "statFactors")
		if statFactors != nil {
			hpFactor = floatOf(statFactors, "MaxHitPoints", 1.0)
			beautyFactor = floatOf(statFactors, "Beauty", 1.0)
		}
		statOffsets := findChildElement(stuffProps, "statOffsets")
		if statOffsets != nil {
			beautyOffset = floatOf(statOffsets, "Beauty", 0)
		}

		// Get stuff categories
		var cats []string
		catsEl := findChildElement(stuffProps, "categories")
		if catsEl != nil {
			for _, li := range findChildren(catsEl, "li") {
				cats = append(cats, strings.TrimSpace(li.Text))
			}
		}

		catsStr := "nil"
		if len(cats) > 0 {
			var parts []string
			for _, c := range cats {
				parts = append(parts, fmt.Sprintf("%q", c))
			}
			catsStr = "[]string{" + strings.Join(parts, ", ") + "}"
		}

		fmt.Fprintf(&buf, "\t{DefName: %q, Label: %q, MarketValue: %s, Categories: %s, SharpArmorFactor: %s, BluntArmorFactor: %s, HeatArmorFactor: %s, ColdInsulation: %s, HeatInsulation: %s, SharpDamageFactor: %s, BluntDamageFactor: %s, MaxHitPointsFactor: %s, BeautyFactor: %s, BeautyOffset: %s},\n",
			defName, label, fmtFloat(marketValue), catsStr,
			fmtFloat(sharpArmor), fmtFloat(bluntArmor), fmtFloat(heatArmor),
			fmtFloat(coldInsul), fmtFloat(heatInsul),
			fmtFloat(sharpDmg), fmtFloat(bluntDmg),
			fmtFloat(hpFactor), fmtFloat(beautyFactor), fmtFloat(beautyOffset))
	})
	buf.WriteString("}\n")

	return os.WriteFile(filepath.Join(outputDir, "materials_gen.go"), []byte(buf.String()), 0644)
}
