package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func genDrugs(r *Resolver, outputDir string) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by datagen; DO NOT EDIT.\n\n")
	buf.WriteString("package data\n\n")

	buf.WriteString("// Drugs is all drug items with their economy and addiction data.\n")
	buf.WriteString("var Drugs = []Drug{\n")

	r.IterateDefs("ThingDef", func(defName string, el *Element) {
		// Must have CompProperties_Drug in comps
		comps := findChildElement(el, "comps")
		if comps == nil {
			return
		}
		var drugComp *Element
		for _, li := range findChildren(comps, "li") {
			cls := li.Attrs["Class"]
			if cls == "CompProperties_Drug" {
				drugComp = li
				break
			}
		}
		if drugComp == nil {
			return
		}

		label := textOf(el, "label")
		statBases := findChildElement(el, "statBases")
		marketValue := 0.0
		if statBases != nil {
			marketValue = floatOf(statBases, "MarketValue", 0)
		}

		// Drug properties
		addictiveness := floatOf(drugComp, "addictiveness", 0)
		minTolToAddict := floatOf(drugComp, "minToleranceToAddict", 0)
		existingAddOffset := floatOf(drugComp, "existingAddictionSeverityOffset", 0)
		needOffset := floatOf(drugComp, "needLevelOffset", 0)

		// Overdose
		overdoseSeverityOffset := 0.0
		if oso := findChildElement(drugComp, "overdoseSeverityOffset"); oso != nil {
			// Format: min~max
			overdoseSeverityOffset = floatOf(drugComp, "overdoseSeverityOffset", 0)
		}
		largeOverdoseChance := floatOf(drugComp, "largeOverdoseChanceFactor", 0)

		// Recipe info (from recipeMaker)
		recipeMaker := findChildElement(el, "recipeMaker")
		workAmount := 0.0
		if recipeMaker != nil {
			workAmount = floatOf(recipeMaker, "workAmount", 0)
		}
		// Work can also be in statBases
		if workAmount == 0 && statBases != nil {
			workAmount = floatOf(statBases, "WorkToMake", 0)
		}

		// Ingredients (from costList)
		var ingredients []string
		costList := findChildElement(el, "costList")
		if costList != nil {
			for _, child := range costList.Children {
				count := strings.TrimSpace(child.Text)
				ingredients = append(ingredients, fmt.Sprintf("%s:%s", child.Tag, count))
			}
		}

		// Ingestible category
		drugCategory := ""
		ingestible := findChildElement(el, "ingestible")
		if ingestible != nil {
			drugCategory = textOf(ingestible, "drugCategory")
		}

		ingredStr := "nil"
		if len(ingredients) > 0 {
			var parts []string
			for _, i := range ingredients {
				parts = append(parts, fmt.Sprintf("%q", i))
			}
			ingredStr = "[]string{" + strings.Join(parts, ", ") + "}"
		}

		fmt.Fprintf(&buf, "\t{DefName: %q, Label: %q, MarketValue: %s, Category: %q, WorkAmount: %s, Ingredients: %s, Addictiveness: %s, MinToleranceToAddict: %s, ExistingAddictionOffset: %s, NeedLevelOffset: %s, OverdoseSeverity: %s, LargeOverdoseChance: %s},\n",
			defName, label, fmtFloat(marketValue), drugCategory,
			fmtFloat(workAmount), ingredStr,
			fmtFloat(addictiveness), fmtFloat(minTolToAddict),
			fmtFloat(existingAddOffset), fmtFloat(needOffset),
			fmtFloat(overdoseSeverityOffset), fmtFloat(largeOverdoseChance))
	})
	buf.WriteString("}\n")

	return os.WriteFile(filepath.Join(outputDir, "drugs_gen.go"), []byte(buf.String()), 0644)
}
