package d2s

// magicalProperties maps stat ID to its binary layout and display name.
// Generated from ItemStatCost.txt + string tables by cmd/propgen, then hand-reviewed.
var magicalProperties = map[uint64]MagicPropertyDef{
	0:   {SaveBits: 8, SaveAdd: 32, DescFunc: 19, Name: "+{0} to Strength"},
	1:   {SaveBits: 7, SaveAdd: 32, DescFunc: 19, Name: "+{0} to Energy"},
	2:   {SaveBits: 7, SaveAdd: 32, DescFunc: 19, Name: "+{0} to Dexterity"},
	3:   {SaveBits: 7, SaveAdd: 32, DescFunc: 19, Name: "+{0} to Vitality"},
	7:   {SaveBits: 9, SaveAdd: 32, DescFunc: 19, Name: "+{0} to Life"},
	9:   {SaveBits: 8, SaveAdd: 32, DescFunc: 19, Name: "+{0} to Mana"},
	11:  {SaveBits: 8, SaveAdd: 32, DescFunc: 19, Name: "+{0} Maximum Stamina"},
	16:  {SaveBits: 9, DescFunc: 19, Name: "{0}% Enhanced Defense"},
	17:  {SaveBits: 9, DescFunc: 19, NumProps: 2, Name: "{0}% Enhanced Maximum Damage"},
	18:  {SaveBits: 9, DescFunc: 19, Name: "{0}% Enhanced Minimum Damage"},
	19:  {SaveBits: 10, DescFunc: 19, Name: "+{0} to Attack Rating"},
	20:  {SaveBits: 6, DescFunc: 19, Name: "+{0} Increased Chance of Blocking"},
	21:  {SaveBits: 6, DescFunc: 19, Name: "+{0} to Minimum Damage"},
	22:  {SaveBits: 7, DescFunc: 19, Name: "+{0} to Maximum Damage"},
	23:  {SaveBits: 6, DescFunc: 19, Name: "+{0} to Minimum Damage"},
	24:  {SaveBits: 7, DescFunc: 19, Name: "+{0} to Maximum Damage"},
	25:  {SaveBits: 8, DescFunc: 19, Name: "+{0} Enhanced Damage"},
	26:  {SaveBits: 8, Name: "manarecovery"},
	27:  {SaveBits: 8, DescFunc: 19, Name: "{0}% Regenerate Mana"},
	28:  {SaveBits: 8, DescFunc: 19, Name: "+{0} Heal Stamina Plus"},
	31:  {SaveBits: 11, SaveAdd: 10, DescFunc: 19, Name: "+{0} Defense"},
	32:  {SaveBits: 9, DescFunc: 19, Name: "+{0} Defense vs. Missile"},
	33:  {SaveBits: 8, DescFunc: 19, Name: "+{0} Defense vs. Melee"},
	34:  {SaveBits: 6, DescFunc: 19, Name: "Damage Reduced by {0}"},
	35:  {SaveBits: 6, DescFunc: 19, Name: "Magic Damage Reduced by {0}"},
	36:  {SaveBits: 9, SaveAdd: 200, DescFunc: 29, Name: "Damage Reduced by {0}%"},
	37:  {SaveBits: 9, SaveAdd: 200, DescFunc: 19, Name: "Magic Resist +{0}%"},
	38:  {SaveBits: 5, DescFunc: 19, Name: "+{0} to Maximum Magic Resist"},
	39:  {SaveBits: 9, SaveAdd: 200, DescFunc: 19, Name: "Fire Resist +{0}%"},
	40:  {SaveBits: 5, DescFunc: 19, Name: "+{0} to Maximum Fire Resist"},
	41:  {SaveBits: 9, SaveAdd: 200, DescFunc: 19, Name: "Lightning Resist +{0}%"},
	42:  {SaveBits: 5, DescFunc: 19, Name: "+{0} to Maximum Lightning Resist"},
	43:  {SaveBits: 9, SaveAdd: 200, DescFunc: 19, Name: "Cold Resist +{0}%"},
	44:  {SaveBits: 5, DescFunc: 19, Name: "+{0} to Maximum Cold Resist"},
	45:  {SaveBits: 9, SaveAdd: 200, DescFunc: 19, Name: "Poison Resist +{0}%"},
	46:  {SaveBits: 5, DescFunc: 19, Name: "+{0} to Maximum Poison Resist"},
	48:  {SaveBits: 8, DescFunc: 19, NumProps: 2, Name: "Adds Fire Damage"},
	49:  {SaveBits: 9, DescFunc: 19, Name: "+{0} to Maximum Fire Damage"},
	50:  {SaveBits: 6, DescFunc: 19, NumProps: 2, Name: "Adds Lightning Damage"},
	51:  {SaveBits: 10, DescFunc: 19, Name: "+{0} to Maximum Lightning Damage"},
	52:  {SaveBits: 8, DescFunc: 19, NumProps: 2, Name: "Adds Magic Damage"},
	53:  {SaveBits: 9, DescFunc: 19, Name: "+{0} to Maximum Magic Damage"},
	54:  {SaveBits: 8, DescFunc: 19, NumProps: 3, Name: "Adds Cold Damage"},
	55:  {SaveBits: 9, DescFunc: 19, Name: "+{0} to Maximum Cold Damage"},
	56:  {SaveBits: 8, Name: "coldlength"},
	57:  {SaveBits: 10, DescFunc: 19, NumProps: 3, Name: "Adds Poison Damage"},
	58:  {SaveBits: 10, DescFunc: 19, Name: "+{0} to Maximum Poison Damage"},
	59:  {SaveBits: 9, Name: "poisonlength"},
	60:  {SaveBits: 7, DescFunc: 19, Name: "{0}% Life Stolen per Hit"},
	62:  {SaveBits: 7, DescFunc: 19, Name: "{0}% Mana Stolen per Hit"},
	67:  {SaveBits: 7, SaveAdd: 30, Name: "velocitypercent"},
	68:  {SaveBits: 7, SaveAdd: 30, Name: "attackrate"},
	71:  {SaveBits: 8, SaveAdd: 100, Name: "value"},
	72:  {SaveBits: 9, Name: "durability"},
	73:  {SaveBits: 8, Name: "maxdurability"},
	74:  {SaveBits: 6, SaveAdd: 30, DescFunc: 19, Name: "Replenish Life +{0}"},
	75:  {SaveBits: 7, SaveAdd: 20, DescFunc: 19, Name: "{0}% Increase Maximum Durability"},
	76:  {SaveBits: 6, SaveAdd: 10, DescFunc: 19, Name: "{0}% Increase Maximum Life"},
	77:  {SaveBits: 6, SaveAdd: 10, DescFunc: 19, Name: "{0}% Increase Maximum Mana"},
	78:  {SaveBits: 7, DescFunc: 19, Name: "Attacker Takes Damage of {0}"},
	79:  {SaveBits: 9, SaveAdd: 100, DescFunc: 19, Name: "{0}% Extra Gold from Monsters"},
	80:  {SaveBits: 8, SaveAdd: 100, DescFunc: 19, Name: "{0}% Better Chance of Getting Magic Items"},
	81:  {SaveBits: 7, DescFunc: 19, Name: "Knockback"},
	82:  {SaveBits: 9, SaveAdd: 20, Name: "item_timeduration"},
	83:  {SaveBits: 3, SaveParamBits: 3, DescFunc: 13, Name: "+{1} to {0} Skill Levels"},
	85:  {SaveBits: 9, SaveAdd: 50, DescFunc: 19, Name: "{0}% to Experience Gained"},
	86:  {SaveBits: 7, DescFunc: 19, Name: "+{0} Life after each Kill"},
	87:  {SaveBits: 7, DescFunc: 19, Name: "{0}% Reduces all Vendor Prices"},
	88:  {SaveBits: 1, Name: "item_doubleherbduration"},
	89:  {SaveBits: 4, SaveAdd: 4, DescFunc: 19, Name: "+{0} to Light Radius"},
	90:  {SaveBits: 24, Name: "item_lightcolor"},
	91:  {SaveBits: 8, SaveAdd: 100, DescFunc: 19, Name: "Requirements {0}%"},
	92:  {SaveBits: 7, Name: "item_levelreq"},
	93:  {SaveBits: 7, SaveAdd: 20, DescFunc: 19, Name: "{0}% Increased Attack Speed"},
	94:  {SaveBits: 7, SaveAdd: 64, Name: "item_levelreqpct"},
	96:  {SaveBits: 7, SaveAdd: 20, DescFunc: 19, Name: "{0}% Faster Run/Walk"},
	97:  {SaveBits: 6, SaveParamBits: 9, Encode: 1, DescFunc: 28, Name: "+{1} To {0}"},
	98:  {SaveBits: 1, SaveParamBits: 8, Name: "state"},
	99:  {SaveBits: 7, SaveAdd: 20, DescFunc: 19, Name: "{0}% Faster Hit Recovery"},
	102: {SaveBits: 7, SaveAdd: 20, DescFunc: 19, Name: "{0}% Faster Block Rate"},
	105: {SaveBits: 7, SaveAdd: 20, DescFunc: 19, Name: "{0}% Faster Cast Rate"},
	107: {SaveBits: 3, SaveParamBits: 9, Encode: 1, DescFunc: 27, Name: "+{1} To {0}"},
	108: {SaveBits: 1, DescFunc: 19, Name: "Slain Monsters Rest in Peace"},
	109: {SaveBits: 9, Name: "curse_resistance"},
	110: {SaveBits: 8, SaveAdd: 20, DescFunc: 19, Name: "Poison Length Reduced by {0}%"},
	111: {SaveBits: 9, SaveAdd: 20, DescFunc: 19, Name: "+{0} Damage"},
	112: {SaveBits: 7, SaveAdd: -1, DescFunc: 5, Name: "Hit Causes Monster to Flee {0}%"},
	113: {SaveBits: 7, DescFunc: 12, Name: "Hit Blinds Target +{0}"},
	114: {SaveBits: 6, DescFunc: 19, Name: "{0}% Damage Taken Goes To Mana"},
	115: {SaveBits: 1, DescFunc: 19, Name: "Ignore Target's Defense"},
	116: {SaveBits: 7, DescFunc: 19, Name: "{0}% Target Defense"},
	117: {SaveBits: 7, DescFunc: 19, Name: "Prevent Monster Heal"},
	118: {SaveBits: 1, DescFunc: 19, Name: "Half Freeze Duration"},
	119: {SaveBits: 9, SaveAdd: 20, DescFunc: 19, Name: "{0}% Bonus to Attack Rating"},
	120: {SaveBits: 7, SaveAdd: 128, DescFunc: 19, Name: "+{0} to Monster Defense Per Hit"},
	121: {SaveBits: 9, SaveAdd: 20, DescFunc: 19, Name: "{0}% Damage to Demons"},
	122: {SaveBits: 9, SaveAdd: 20, DescFunc: 19, Name: "+{0} Damage to Undead"},
	123: {SaveBits: 10, SaveAdd: 128, DescFunc: 19, Name: "+{0} to Attack Rating against Demons"},
	124: {SaveBits: 10, SaveAdd: 128, DescFunc: 19, Name: "+{0} to Attack Rating against Undead"},
	125: {SaveBits: 1, DescFunc: 19, Name: "Throwable"},
	126: {SaveBits: 3, SaveParamBits: 3, DescFunc: 19, Name: "+{0} to Fire Skills"},
	127: {SaveBits: 3, DescFunc: 19, Name: "+{0} to All Skills"},
	128: {SaveBits: 5, DescFunc: 19, Name: "Attacker Takes Lightning Damage of {0}"},
	134: {SaveBits: 5, DescFunc: 12, Name: "Freezes Target +{0}"},
	135: {SaveBits: 7, DescFunc: 19, Name: "{0}% Chance of Open Wounds"},
	136: {SaveBits: 7, DescFunc: 19, Name: "{0}% Chance of Crushing Blow"},
	137: {SaveBits: 7, DescFunc: 19, Name: "+{0} Kick Damage"},
	138: {SaveBits: 7, DescFunc: 19, Name: "+{0} to Mana after each Kill"},
	139: {SaveBits: 7, DescFunc: 19, Name: "+{0} Life after each Demon Kill"},
	140: {SaveBits: 7, Name: "item_extrablood"},
	141: {SaveBits: 7, DescFunc: 19, Name: "{0}% Deadly Strike"},
	142: {SaveBits: 7, DescFunc: 19, Name: "Fire Absorb {0}%"},
	143: {SaveBits: 7, DescFunc: 19, Name: "+{0} Fire Absorb"},
	144: {SaveBits: 7, DescFunc: 19, Name: "Lightning Absorb {0}%"},
	145: {SaveBits: 7, DescFunc: 19, Name: "+{0} Lightning Absorb"},
	146: {SaveBits: 7, DescFunc: 19, Name: "Magic Absorb {0}%"},
	147: {SaveBits: 7, DescFunc: 19, Name: "+{0} Magic Absorb"},
	148: {SaveBits: 7, DescFunc: 19, Name: "Cold Absorb {0}%"},
	149: {SaveBits: 7, DescFunc: 19, Name: "+{0} Cold Absorb"},
	150: {SaveBits: 7, DescFunc: 19, Name: "Slows Target by {0}%"},
	151: {SaveBits: 5, SaveParamBits: 9, DescFunc: 16, Name: "item_aura"},
	152: {SaveBits: 1, DescFunc: 19, Name: "Indestructible"},
	153: {SaveBits: 1, DescFunc: 19, Name: "Cannot Be Frozen"},
	154: {SaveBits: 7, SaveAdd: 20, DescFunc: 19, Name: "+{0} Slower Stamina Drain"},
	155: {SaveBits: 7, SaveParamBits: 10, DescFunc: 23, Name: "{0} Reanimate as:"},
	156: {SaveBits: 7, DescFunc: 19, Name: "Piercing Attack"},
	157: {SaveBits: 7, DescFunc: 19, Name: "Fires Magic Arrows"},
	158: {SaveBits: 7, DescFunc: 19, Name: "Fires Explosive Arrows or Bolts"},
	159: {SaveBits: 6, Name: "item_throw_mindamage"},
	160: {SaveBits: 7, Name: "item_throw_maxdamage"},
	179: {SaveBits: 9, SaveParamBits: 10, DescFunc: 22, Name: "{0}% to Attack Rating versus"},
	180: {SaveBits: 9, SaveParamBits: 10, DescFunc: 22, Name: "{0}% to Damage versus"},
	181: {SaveBits: 3, Name: "fade"},
	185: {SaveBits: 8, Name: "bonus_mindamage"},
	186: {SaveBits: 8, Name: "bonus_maxdamage"},
	187: {SaveBits: 10, DescFunc: 19, Name: "-{0}% to Enemy Cold Resistance"},
	188: {SaveBits: 3, SaveParamBits: 16, DescFunc: 14, Name: "+{2} to {0} Skills ({1} only)"},
	189: {SaveBits: 10, DescFunc: 19, Name: "-{0}% to Enemy Fire Resistance"},
	190: {SaveBits: 10, DescFunc: 19, Name: "-{0}% to Enemy Lightning Resistance"},
	191: {SaveBits: 10, DescFunc: 19, Name: "-{0}% to Enemy Poison Resistance"},
	192: {SaveBits: 10, DescFunc: 19, Name: "-{0}% to Enemy Physical Resistance"},
	193: {SaveBits: 10, DescFunc: 19, Name: "-{0}% to Enemy Magic Resistance"},
	194: {SaveBits: 4, Name: "item_numsockets"},
	195: {SaveBits: 7, SaveParamBits: 16, Encode: 2, DescFunc: 15, Name: "item_skillonattack"},
	196: {SaveBits: 7, SaveParamBits: 16, Encode: 2, DescFunc: 15, Name: "item_skillonkill"},
	197: {SaveBits: 7, SaveParamBits: 16, Encode: 2, DescFunc: 15, Name: "item_skillondeath"},
	198: {SaveBits: 7, SaveParamBits: 16, Encode: 2, DescFunc: 15, Name: "item_skillonhit"},
	199: {SaveBits: 7, SaveParamBits: 16, Encode: 2, DescFunc: 15, Name: "item_skillonlevelup"},
	200: {SaveBits: 7, DescFunc: 19, Name: "item_charge_noconsume"},
	201: {SaveBits: 7, SaveParamBits: 16, Encode: 2, DescFunc: 15, Name: "item_skillongethit"},
	204: {SaveBits: 16, SaveParamBits: 16, Encode: 3, DescFunc: 24, Name: "item_charged_skill"},
	205: {SaveBits: 7, DescFunc: 19, Name: "item_noconsume"},
	206: {SaveBits: 8, Name: "passive_mastery_noconsume"},
	207: {SaveBits: 8, Name: "passive_mastery_replenish_oncrit"},
	213: {SaveBits: 8, Name: "passive_mastery_gethit_rate"},
	214: {SaveBits: 6, DescFunc: 19, Name: "+{0} Defense (Based on Character Level)"},
	215: {SaveBits: 6, DescFunc: 19, Name: "{0}% Enhanced Defense (Based on Character Level)"},
	216: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Life (Based on Character Level)"},
	217: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Mana (Based on Character Level)"},
	218: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Maximum Damage (Based on Character Level)"},
	219: {SaveBits: 6, DescFunc: 19, Name: "{0}% Enhanced Maximum Damage (Based on Character Level)"},
	220: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Strength (Based on Character Level)"},
	221: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Dexterity (Based on Character Level)"},
	222: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Energy (Based on Character Level)"},
	223: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Vitality (Based on Character Level)"},
	224: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Attack Rating (Based on Character Level)"},
	225: {SaveBits: 6, DescFunc: 19, Name: "{0}% Bonus to Attack Rating (Based on Character Level)"},
	226: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Maximum Cold Damage (Based on Character Level)"},
	227: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Maximum Fire Damage (Based on Character Level)"},
	228: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Maximum Lightning Damage (Based on Character Level)"},
	229: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Maximum Poison Damage (Based on Character Level)"},
	230: {SaveBits: 6, DescFunc: 19, Name: "+{0} Cold Resist (Based on Character Level)"},
	231: {SaveBits: 6, DescFunc: 19, Name: "+{0} Fire Resist (Based on Character Level)"},
	232: {SaveBits: 6, DescFunc: 19, Name: "+{0} Lightning Resist (Based on Character Level)"},
	233: {SaveBits: 6, DescFunc: 19, Name: "+{0} Poison Resist (Based on Character Level)"},
	234: {SaveBits: 6, DescFunc: 19, Name: "+{0} Cold Absorb (Based on Character Level)"},
	235: {SaveBits: 6, DescFunc: 19, Name: "+{0} Fire Absorb (Based on Character Level)"},
	236: {SaveBits: 6, DescFunc: 19, Name: "+{0} Lightning Absorb (Based on Character Level)"},
	237: {SaveBits: 6, Name: "item_absorb_pois_perlevel"},
	238: {SaveBits: 5, DescFunc: 19, Name: "Attacker Takes Damage of {0} (Based on Character Level)"},
	239: {SaveBits: 6, DescFunc: 19, Name: "{0}% Extra Gold from Monsters (Based on Character Level)"},
	240: {SaveBits: 6, DescFunc: 19, Name: "{0}% Better Chance of Getting Magic Items (Based on Character Level)"},
	241: {SaveBits: 6, DescFunc: 19, Name: "+{0} Heal Stamina Plus (Based on Character Level)"},
	242: {SaveBits: 6, DescFunc: 19, Name: "+{0} Maximum Stamina (Based on Character Level)"},
	243: {SaveBits: 6, DescFunc: 19, Name: "{0}% Damage to Demons (Based on Character Level)"},
	244: {SaveBits: 6, DescFunc: 19, Name: "{0}% Damage to Undead (Based on Character Level)"},
	245: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Attack Rating against Demons (Based on Character Level)"},
	246: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Attack Rating against Undead (Based on Character Level)"},
	247: {SaveBits: 6, DescFunc: 19, Name: "{0}% Chance of Crushing Blow (Based on Character Level)"},
	248: {SaveBits: 6, DescFunc: 19, Name: "{0}% Chance of Open Wounds (Based on Character Level)"},
	249: {SaveBits: 6, DescFunc: 19, Name: "+{0} Kick Damage (Based on Character Level)"},
	250: {SaveBits: 6, DescFunc: 19, Name: "{0}% Deadly Strike (Based on Character Level)"},
	252: {SaveBits: 6, DescFunc: 11, Name: "Repairs 1 Durability in {0} Seconds"},
	253: {SaveBits: 6, DescFunc: 19, Name: "Replenishes Quantity"},
	254: {SaveBits: 8, DescFunc: 19, Name: "Increased Stack Size"},
	268: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} Defense (Increases over Time)"},
	269: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Enhanced Defense (Increases over Time)"},
	270: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Life (Increases over Time)"},
	271: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Mana (Increases over Time)"},
	272: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Maximum Damage (Increases over Time)"},
	273: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Enhanced Maximum Damage (Increases over Time)"},
	274: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Strength (Increases over Time)"},
	275: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Dexterity (Increases over Time)"},
	276: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Energy (Increases over Time)"},
	277: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Vitality (Increases over Time)"},
	278: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Attack Rating (Increases over Time)"},
	279: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Bonus to Attack Rating (Increases over Time)"},
	280: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Maximum Cold Damage (Increases over Time)"},
	281: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Maximum Fire Damage (Increases over Time)"},
	282: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Maximum Lightning Damage (Increases over Time)"},
	283: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Maximum Poison Damage (Increases over Time)"},
	284: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Cold Resist (Increases over Time)"},
	285: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Fire Resist (Increases over Time)"},
	286: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Lightning Resist (Increases over Time)"},
	287: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Poison Resist (Increases over Time)"},
	288: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Cold Absorb (Increases over Time)"},
	289: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Fire Absorb (Increases over Time)"},
	290: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Lightning Absorb (Increases over Time)"},
	291: {SaveBits: 22, Encode: 4, Name: "item_absorb_pois_bytime"},
	292: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Extra Gold from Monsters (Increases over Time)"},
	293: {
		SaveBits: 22, Encode: 4, DescFunc: 18,
		Name: "{0}% Better Chance of Getting Magic Items (Increases over Time)",
	},
	294: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Heal Stamina Plus (Increases over Time)"},
	295: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} Maximum Stamina (Increases over Time)"},
	296: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Damage to Demons (Increases over Time)"},
	297: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Damage to Undead (Increases over Time)"},
	298: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Attack Rating against Demons (Increases over Time)"},
	299: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} to Attack Rating against Undead (Increases over Time)"},
	300: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Chance of Crushing Blow (Increases over Time)"},
	301: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Chance of Open Wounds (Increases over Time)"},
	302: {SaveBits: 22, Encode: 4, DescFunc: 17, Name: "+{0} Kick Damage (Increases over Time)"},
	303: {SaveBits: 22, Encode: 4, DescFunc: 18, Name: "{0}% Deadly Strike (Increases over Time)"},
	305: {SaveBits: 8, SaveAdd: 50, DescFunc: 19, Name: "-{0}% to Enemy Cold Resistance"},
	306: {SaveBits: 8, SaveAdd: 50, DescFunc: 19, Name: "-{0}% to Enemy Fire Resistance"},
	307: {SaveBits: 8, SaveAdd: 50, DescFunc: 19, Name: "-{0}% to Enemy Lightning Resistance"},
	308: {SaveBits: 8, SaveAdd: 50, DescFunc: 19, Name: "-{0}% to Enemy Poison Resistance"},
	324: {SaveBits: 6, Name: "item_extra_charges"},
	329: {SaveBits: 9, SaveAdd: 50, DescFunc: 19, Name: "{0}% to Fire Skill Damage"},
	330: {SaveBits: 9, SaveAdd: 50, DescFunc: 19, Name: "{0}% to Lightning Skill Damage"},
	331: {SaveBits: 9, SaveAdd: 50, DescFunc: 19, Name: "{0}% to Cold Skill Damage"},
	332: {SaveBits: 9, SaveAdd: 50, DescFunc: 19, Name: "{0}% to Poison Skill Damage"},
	333: {SaveBits: 8, DescFunc: 19, Name: "-{0}% to Enemy Fire Resistance"},
	334: {SaveBits: 8, DescFunc: 19, Name: "-{0}% to Enemy Lightning Resistance"},
	335: {SaveBits: 8, DescFunc: 19, Name: "-{0}% to Enemy Cold Resistance"},
	336: {SaveBits: 8, DescFunc: 19, Name: "-{0}% to Enemy Poison Resistance"},
	337: {SaveBits: 8, Name: "passive_critical_strike"},
	338: {SaveBits: 7, Name: "passive_dodge"},
	339: {SaveBits: 7, Name: "passive_avoid"},
	340: {SaveBits: 7, Name: "passive_evade"},
	341: {SaveBits: 8, Name: "passive_warmth"},
	342: {SaveBits: 8, Name: "passive_mastery_melee_th"},
	343: {SaveBits: 8, Name: "passive_mastery_melee_dmg"},
	344: {SaveBits: 8, Name: "passive_mastery_melee_crit"},
	345: {SaveBits: 8, Name: "passive_mastery_throw_th"},
	346: {SaveBits: 8, Name: "passive_mastery_throw_dmg"},
	347: {SaveBits: 8, Name: "passive_mastery_throw_crit"},
	348: {SaveBits: 8, Name: "passive_weaponblock"},
	349: {SaveBits: 8, Name: "passive_summon_resist"},
	356: {SaveBits: 2, Name: "questitemdifficulty"},
	357: {SaveBits: 9, SaveAdd: 50, DescFunc: 19, Name: "{0}% to Magic Skill Damage"},
	358: {SaveBits: 8, DescFunc: 19, Name: "-{0}% to Enemy Magic Resistance"},
	365: {SaveBits: 6, DescFunc: 19, Name: "+{0} to Maximum Magic Damage (Based on Character Level)"},
	366: {SaveBits: 8, DescFunc: 19, Name: "{0}% Damage Pierce"},
}
