// Code generated by plugins/satisfactory/tools/datagen. DO NOT EDIT.
// Source: CommunityResources/Docs/en-US.json from the game install.

package main

// beltThroughput maps a conveyor belt/lift class (with the trailing _C) to
// its item throughput in items/min (the game's mSpeed / 2).
var beltThroughput = map[string]float64{
	"Build_ConveyorBeltMk1_C": 60,
	"Build_ConveyorBeltMk2_C": 120,
	"Build_ConveyorBeltMk3_C": 270,
	"Build_ConveyorBeltMk4_C": 480,
	"Build_ConveyorBeltMk5_C": 780,
	"Build_ConveyorBeltMk6_C": 1200,
	"Build_ConveyorLiftMk1_C": 60,
	"Build_ConveyorLiftMk2_C": 120,
	"Build_ConveyorLiftMk3_C": 270,
	"Build_ConveyorLiftMk4_C": 480,
	"Build_ConveyorLiftMk5_C": 780,
	"Build_ConveyorLiftMk6_C": 1200,
}
