// Code generated by plugins/satisfactory/tools/datagen. DO NOT EDIT.
// Source: CommunityResources/Docs/en-US.json from the game install.

package main

// milestoneTiers maps a HUB milestone schematic class (with the trailing _C)
// to its authoritative in-game tier (mTechTier). The class-name number is NOT
// a reliable tier — milestoneTier consults this table first.
var milestoneTiers = map[string]int{
	"Schematic_1-1_C": 1,
	"Schematic_1-2_C": 1,
	"Schematic_1-3_C": 1,
	"Schematic_2-1_C": 2,
	"Schematic_2-2_C": 2,
	"Schematic_2-3_C": 2,
	"Schematic_2-5_C": 2,
	"Schematic_3-1_C": 3,
	"Schematic_3-2_C": 2,
	"Schematic_3-3_C": 3,
	"Schematic_3-4_C": 3,
	"Schematic_4-1_C": 4,
	"Schematic_4-2_C": 3,
	"Schematic_4-3_C": 4,
	"Schematic_4-4_C": 4,
	"Schematic_4-5_C": 4,
	"Schematic_5-1_C": 5,
	"Schematic_5-2_C": 6,
	"Schematic_5-3_C": 4,
	"Schematic_5-4_C": 5,
	"Schematic_5-5_C": 5,
	"Schematic_6-1_C": 5,
	"Schematic_6-2_C": 5,
	"Schematic_6-3_C": 6,
	"Schematic_6-5_C": 6,
	"Schematic_6-6_C": 6,
	"Schematic_6-7_C": 6,
	"Schematic_7-1_C": 7,
	"Schematic_7-2_C": 7,
	"Schematic_7-3_C": 7,
	"Schematic_7-4_C": 8,
	"Schematic_7-5_C": 7,
	"Schematic_8-1_C": 8,
	"Schematic_8-2_C": 8,
	"Schematic_8-3_C": 7,
	"Schematic_8-4_C": 8,
	"Schematic_8-5_C": 8,
	"Schematic_9-1_C": 9,
	"Schematic_9-2_C": 9,
	"Schematic_9-3_C": 9,
	"Schematic_9-4_C": 9,
	"Schematic_9-5_C": 9,
}
