// datagen generates Go data tables for the Satisfactory reference modules
// from the game-shipped CommunityResources/Docs/en-US.json (UTF-16LE).
//
// Usage:
//
//	go run ./tools/datagen/ [-docs path] [-out dir]
//
// Acquire the input from a game install, e.g.:
//
//	scp gnomon:~/.local/share/Steam/steamapps/common/Satisfactory/CommunityResources/Docs/en-US.json .reference/satisfactory-docs/
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/text/encoding/unicode"
)

type docEntry struct {
	NativeClass string                       `json:"NativeClass"` //nolint:tagliatelle // Docs.json uses PascalCase
	Classes     []map[string]json.RawMessage `json:"Classes"`     //nolint:tagliatelle // Docs.json uses PascalCase
}

// field reads a string-typed field from a Docs class entry.
func field(c map[string]json.RawMessage, name string) string {
	raw, ok := c[name]
	if !ok {
		return ""
	}
	var s string
	if err := json.Unmarshal(raw, &s); err != nil {
		return ""
	}
	return s
}

func floatField(c map[string]json.RawMessage, name string) float64 {
	v, err := strconv.ParseFloat(field(c, name), 64)
	if err != nil {
		return 0
	}
	return v
}

func intField(c map[string]json.RawMessage, name string) int {
	v, err := strconv.Atoi(field(c, name))
	if err != nil {
		return 0
	}
	return v
}

func main() {
	docsPath := flag.String("docs", "../../.reference/satisfactory-docs/en-US.json", "path to en-US.json")
	outDir := flag.String("out", "reference/data", "output directory")
	flag.Parse()

	raw, err := os.ReadFile(*docsPath)
	if err != nil {
		log.Fatalf("read docs: %v", err)
	}
	decoded, err := unicode.UTF16(unicode.LittleEndian, unicode.UseBOM).NewDecoder().Bytes(raw)
	if err != nil {
		log.Fatalf("transcode UTF-16: %v", err)
	}
	var entries []docEntry
	if err := json.Unmarshal(decoded, &entries); err != nil {
		log.Fatalf("parse docs: %v", err)
	}

	byNative := map[string][]map[string]json.RawMessage{}
	for _, e := range entries {
		// NativeClass: "/Script/CoreUObject.Class'/Script/FactoryGame.FGRecipe'"
		name := shortClassName(e.NativeClass)
		byNative[name] = append(byNative[name], e.Classes...)
	}

	gen := &generator{byNative: byNative, outDir: *outDir}
	gen.schematics() // first: recipes need the alternate-unlock set
	gen.recipes()
	gen.items()
	gen.buildings()
	log.Printf("generated %d recipes, %d items, %d buildings, %d schematics → %s",
		gen.recipeCount, gen.itemCount, gen.buildingCount, gen.schematicCount, *outDir)
}

type generator struct {
	byNative       map[string][]map[string]json.RawMessage
	outDir         string
	alternates     map[string]bool // recipe class -> unlocked by EST_Alternate schematic
	recipeCount    int
	itemCount      int
	buildingCount  int
	schematicCount int
}

func (g *generator) write(filename, body string) {
	header := "// Code generated by plugins/satisfactory/tools/datagen. DO NOT EDIT.\n" +
		"// Source: CommunityResources/Docs/en-US.json from the game install.\n\npackage data\n\n"
	if err := os.WriteFile(g.outDir+"/"+filename, []byte(header+body), 0o644); err != nil {
		log.Fatalf("write %s: %v", filename, err)
	}
}

// sortedByClassName orders class entries deterministically.
func sortedByClassName(classes []map[string]json.RawMessage) []map[string]json.RawMessage {
	sort.Slice(classes, func(i, j int) bool {
		return field(classes[i], "ClassName") < field(classes[j], "ClassName")
	})
	return classes
}

func itemAmountsGo(pairs []pair) string {
	if len(pairs) == 0 {
		return "nil"
	}
	parts := make([]string, 0, len(pairs))
	for _, p := range pairs {
		parts = append(parts, fmt.Sprintf("{ItemClass: %q, Amount: %d}", p.class, p.amount))
	}
	return "[]ItemAmount{" + strings.Join(parts, ", ") + "}"
}

func stringsGo(list []string) string {
	if len(list) == 0 {
		return "nil"
	}
	quoted := make([]string, 0, len(list))
	for _, s := range list {
		quoted = append(quoted, strconv.Quote(s))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

type unlockEntry struct {
	Class    string `json:"Class"` //nolint:tagliatelle // Docs.json uses PascalCase
	MRecipes string `json:"mRecipes"`
}

func (g *generator) schematics() {
	g.alternates = map[string]bool{}
	var b strings.Builder
	b.WriteString("var Schematics = map[string]Schematic{\n")
	for _, c := range sortedByClassName(g.byNative["FGSchematic"]) {
		className := field(c, "ClassName")
		schematicType := field(c, "mType")

		var unlockRecipes []string
		var unlocks []unlockEntry
		if raw, ok := c["mUnlocks"]; ok {
			// mUnlocks is a real JSON array of objects; entries that fail to
			// decode (mixed unlock kinds) simply contribute no recipes.
			if err := json.Unmarshal(raw, &unlocks); err != nil {
				unlocks = nil
			}
		}
		for _, u := range unlocks {
			if u.Class == "BP_UnlockRecipe_C" {
				unlockRecipes = append(unlockRecipes, parseClassList(u.MRecipes)...)
			}
		}
		if schematicType == "EST_Alternate" {
			for _, r := range unlockRecipes {
				g.alternates[r] = true
			}
		}

		fmt.Fprintf(&b, "\t%q: {ClassName: %q, DisplayName: %q, Type: %q, Tier: %d, Cost: %s, UnlockRecipes: %s},\n",
			className, className, field(c, "mDisplayName"), schematicType,
			intField(c, "mTechTier"), itemAmountsGo(parseItemAmounts(field(c, "mCost"))),
			stringsGo(unlockRecipes))
		g.schematicCount++
	}
	b.WriteString("}\n")
	g.write("schematics_gen.go", b.String())
}

func (g *generator) recipes() {
	var b strings.Builder
	b.WriteString("var Recipes = map[string]Recipe{\n")
	for _, c := range sortedByClassName(g.byNative["FGRecipe"]) {
		className := field(c, "ClassName")
		fmt.Fprintf(&b,
			"\t%q: {ClassName: %q, DisplayName: %q, Ingredients: %s, Products: %s, "+
				"DurationSec: %v, ProducedIn: %s, Alternate: %v},\n",
			className, className, field(c, "mDisplayName"),
			itemAmountsGo(parseItemAmounts(field(c, "mIngredients"))),
			itemAmountsGo(parseItemAmounts(field(c, "mProduct"))),
			floatField(c, "mManufactoringDuration"),
			stringsGo(parseClassList(field(c, "mProducedIn"))),
			g.alternates[className])
		g.recipeCount++
	}
	b.WriteString("}\n")
	g.write("recipes_gen.go", b.String())
}

func (g *generator) items() {
	// Every descriptor family that can appear in inventories, recipes, or
	// as fuel.
	itemNatives := []string{
		"FGItemDescriptor", "FGResourceDescriptor", "FGItemDescriptorBiomass",
		"FGItemDescriptorNuclearFuel", "FGItemDescriptorPowerBoosterFuel",
		"FGEquipmentDescriptor", "FGConsumableDescriptor", "FGPowerShardDescriptor",
		"FGAmmoTypeProjectile", "FGAmmoTypeSpreadshot", "FGAmmoTypeInstantHit",
		"FGVehicleDescriptor", "FGConsumableEquipment", "FGEquipmentStunSpear",
		"FGEquipmentZipline",
	}
	raws := map[string]bool{}
	for _, c := range g.byNative["FGResourceDescriptor"] {
		raws[field(c, "ClassName")] = true
	}
	var all []map[string]json.RawMessage
	for _, native := range itemNatives {
		all = append(all, g.byNative[native]...)
	}
	var b strings.Builder
	b.WriteString("var Items = map[string]Item{\n")
	for _, c := range sortedByClassName(all) {
		className := field(c, "ClassName")
		extra := ""
		if waste := shortClassName(field(c, "mSpentFuelClass")); waste != "" {
			extra = fmt.Sprintf(", WasteClass: %q, WasteAmount: %d",
				waste, intField(c, "mAmountOfWaste"))
		}
		fmt.Fprintf(&b,
			"\t%q: {ClassName: %q, DisplayName: %q, Form: %q, StackSize: %q, "+
				"EnergyMJ: %v, SinkPoints: %d, Raw: %v%s},\n",
			className, className, field(c, "mDisplayName"), field(c, "mForm"),
			field(c, "mStackSize"), floatField(c, "mEnergyValue"),
			intField(c, "mResourceSinkPoints"), raws[className], extra)
		g.itemCount++
	}
	b.WriteString("}\n")
	g.write("items_gen.go", b.String())
}

type fuelEntry struct {
	MFuelClass string `json:"mFuelClass"`
}

func (g *generator) buildings() {
	type buildingNative struct {
		native string
		kind   string
	}
	natives := []buildingNative{
		{"FGBuildableManufacturer", "manufacturer"},
		{"FGBuildableManufacturerVariablePower", "manufacturerVariablePower"},
		{"FGBuildableResourceExtractor", "extractor"},
		{"FGBuildableWaterPump", "extractor"},
		{"FGBuildableFrackingExtractor", "extractor"},
		{"FGBuildableGeneratorFuel", "generator"},
		{"FGBuildableGeneratorNuclear", "generator"},
		{"FGBuildableGeneratorGeoThermal", "generator"},
	}

	var b strings.Builder
	b.WriteString("var Buildings = map[string]Building{\n")
	type row struct{ className, line string }
	var rows []row
	for _, n := range natives {
		for _, c := range g.byNative[n.native] {
			className := field(c, "ClassName")
			power := floatField(c, "mPowerConsumption")
			if n.kind == "manufacturerVariablePower" {
				power = floatField(c, "mEstimatedMaximumPowerConsumption")
			}
			var fuels []string
			var entries []fuelEntry
			if raw, ok := c["mFuel"]; ok {
				if err := json.Unmarshal(raw, &entries); err != nil {
					entries = nil
				}
			}
			for _, f := range entries {
				if f.MFuelClass != "" {
					fuels = append(fuels, shortClassName(f.MFuelClass))
				}
			}
			line := fmt.Sprintf(
				"\t%q: {ClassName: %q, DisplayName: %q, Kind: %q, PowerMW: %v, PowerProductionMW: %v, "+
					"FuelClasses: %s, SupplementalRatio: %v, ItemsPerCycle: %d, ExtractCycleSec: %v},\n",
				className, className, field(c, "mDisplayName"), n.kind, power,
				floatField(c, "mPowerProduction"), stringsGo(fuels),
				floatField(c, "mSupplementalToPowerRatio"),
				intField(c, "mItemsPerCycle"), floatField(c, "mExtractCycleTime"))
			rows = append(rows, row{className, line})
			g.buildingCount++
		}
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].className < rows[j].className })
	for _, r := range rows {
		b.WriteString(r.line)
	}
	b.WriteString("}\n")
	g.write("buildings_gen.go", b.String())
}
