// datagen generates Go data tables for the Satisfactory reference modules
// from the game-shipped CommunityResources/Docs/en-US.json (UTF-16LE).
//
// Usage:
//
//	go run ./tools/datagen/ [-docs path] [-out dir]
//
// Acquire the input from a game install, e.g.:
//
//	scp gnomon:~/.local/share/Steam/steamapps/common/Satisfactory/CommunityResources/Docs/en-US.json .reference/satisfactory-docs/
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/text/encoding/unicode"
)

type docEntry struct {
	NativeClass string                       `json:"NativeClass"` //nolint:tagliatelle // Docs.json uses PascalCase
	Classes     []map[string]json.RawMessage `json:"Classes"`     //nolint:tagliatelle // Docs.json uses PascalCase
}

// field reads a string-typed field from a Docs class entry.
func field(c map[string]json.RawMessage, name string) string {
	raw, ok := c[name]
	if !ok {
		return ""
	}
	var s string
	if err := json.Unmarshal(raw, &s); err != nil {
		return ""
	}
	return s
}

func floatField(c map[string]json.RawMessage, name string) float64 {
	v, err := strconv.ParseFloat(field(c, name), 64)
	if err != nil {
		return 0
	}
	return v
}

func intField(c map[string]json.RawMessage, name string) int {
	v, err := strconv.Atoi(field(c, name))
	if err != nil {
		return 0
	}
	return v
}

func main() {
	docsPath := flag.String(
		"docs",
		"../../.reference/satisfactory-docs/en-US.json",
		"path to en-US.json",
	)
	outDir := flag.String("out", "reference/data", "output directory")
	parserOut := flag.String(
		"parser-out",
		"parser",
		"output directory for the parser's canonical-name table",
	)
	flag.Parse()

	raw, err := os.ReadFile(*docsPath)
	if err != nil {
		log.Fatalf("read docs: %v", err)
	}
	decoded, err := unicode.UTF16(unicode.LittleEndian, unicode.UseBOM).NewDecoder().Bytes(raw)
	if err != nil {
		log.Fatalf("transcode UTF-16: %v", err)
	}
	var entries []docEntry
	if err := json.Unmarshal(decoded, &entries); err != nil {
		log.Fatalf("parse docs: %v", err)
	}

	byNative := map[string][]map[string]json.RawMessage{}
	for _, e := range entries {
		// NativeClass: "/Script/CoreUObject.Class'/Script/FactoryGame.FGRecipe'"
		name := shortClassName(e.NativeClass)
		byNative[name] = append(byNative[name], e.Classes...)
	}

	gen := &generator{byNative: byNative, outDir: *outDir}
	gen.schematics() // first: recipes need the alternate-unlock set
	gen.recipes()
	gen.items()
	gen.buildings()
	gen.buildingInfos()
	gen.parserNames(*parserOut)
	gen.parserMilestoneTiers(*parserOut)
	gen.parserProduction(*parserOut)
	gen.parserBelts(*parserOut)
	log.Printf(
		"generated %d recipes, %d items, %d buildings, %d building infos, %d schematics → %s; "+
			"%d canonical names, %d milestone tiers, %d recipe specs → %s",
		gen.recipeCount,
		gen.itemCount,
		gen.buildingCount,
		gen.buildingInfoCount,
		gen.schematicCount,
		*outDir,
		gen.nameCount,
		gen.milestoneTierCount,
		gen.productionCount,
		*parserOut,
	)
}

// schematicRef is the schematic that unlocks a recipe and its in-game tier.
type schematicRef struct {
	Display string
	Tier    int
}

type generator struct {
	byNative           map[string][]map[string]json.RawMessage
	outDir             string
	alternates         map[string]bool         // recipe class -> unlocked by EST_Alternate schematic
	recipeSchematic    map[string]schematicRef // recipe class -> earliest-tier unlocking schematic
	recipeCount        int
	itemCount          int
	buildingCount      int
	buildingInfoCount  int
	schematicCount     int
	nameCount          int
	milestoneTierCount int
	productionCount    int
}

// itemNatives lists every descriptor family that can appear in inventories,
// recipes, or as fuel. Shared by items() and parserNames().
var itemNatives = []string{
	"FGItemDescriptor", "FGResourceDescriptor", "FGItemDescriptorBiomass",
	"FGItemDescriptorNuclearFuel", "FGItemDescriptorPowerBoosterFuel",
	"FGEquipmentDescriptor", "FGConsumableDescriptor", "FGPowerShardDescriptor",
	"FGAmmoTypeProjectile", "FGAmmoTypeSpreadshot", "FGAmmoTypeInstantHit",
	"FGVehicleDescriptor", "FGConsumableEquipment", "FGEquipmentStunSpear",
	"FGEquipmentZipline",
}

// buildingNatives lists the buildable families whose display names the parser
// reports. Shared by buildings() and parserNames().
var buildingNatives = []string{
	"FGBuildableManufacturer", "FGBuildableManufacturerVariablePower",
	"FGBuildableResourceExtractor", "FGBuildableWaterPump",
	"FGBuildableFrackingExtractor", "FGBuildableGeneratorFuel",
	"FGBuildableGeneratorNuclear", "FGBuildableGeneratorGeoThermal",
}

func (g *generator) write(filename, body string) {
	header := "// Code generated by plugins/satisfactory/tools/datagen. DO NOT EDIT.\n" +
		"// Source: CommunityResources/Docs/en-US.json from the game install.\n\npackage data\n\n"
	src, err := format.Source([]byte(header + body))
	if err != nil {
		log.Fatalf("format %s: %v", filename, err)
	}
	if err := os.WriteFile(g.outDir+"/"+filename, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", filename, err)
	}
}

// sortedByClassName orders class entries deterministically.
func sortedByClassName(classes []map[string]json.RawMessage) []map[string]json.RawMessage {
	sort.Slice(classes, func(i, j int) bool {
		return field(classes[i], "ClassName") < field(classes[j], "ClassName")
	})
	return classes
}

func itemAmountsGo(pairs []pair) string {
	if len(pairs) == 0 {
		return "nil"
	}
	parts := make([]string, 0, len(pairs))
	for _, p := range pairs {
		parts = append(parts, fmt.Sprintf("{ItemClass: %q, Amount: %d}", p.class, p.amount))
	}
	return "[]ItemAmount{" + strings.Join(parts, ", ") + "}"
}

func stringsGo(list []string) string {
	if len(list) == 0 {
		return "nil"
	}
	quoted := make([]string, 0, len(list))
	for _, s := range list {
		quoted = append(quoted, strconv.Quote(s))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

type unlockEntry struct {
	Class    string `json:"Class"` //nolint:tagliatelle // Docs.json uses PascalCase
	MRecipes string `json:"mRecipes"`
}

func (g *generator) schematics() {
	g.alternates = map[string]bool{}
	g.recipeSchematic = map[string]schematicRef{}
	var b strings.Builder
	b.WriteString("var Schematics = map[string]Schematic{\n")
	for _, c := range sortedByClassName(g.byNative["FGSchematic"]) {
		className := field(c, "ClassName")
		schematicType := field(c, "mType")
		tier := intField(c, "mTechTier")

		var unlockRecipes []string
		var unlocks []unlockEntry
		if raw, ok := c["mUnlocks"]; ok {
			// mUnlocks is a real JSON array of objects; entries that fail to
			// decode (mixed unlock kinds) simply contribute no recipes.
			if err := json.Unmarshal(raw, &unlocks); err != nil {
				unlocks = nil
			}
		}
		for _, u := range unlocks {
			if u.Class == "BP_UnlockRecipe_C" {
				unlockRecipes = append(unlockRecipes, parseClassList(u.MRecipes)...)
			}
		}
		if schematicType == "EST_Alternate" {
			for _, r := range unlockRecipes {
				g.alternates[r] = true
			}
		}
		display := field(c, "mDisplayName")
		for _, r := range unlockRecipes {
			if ex, ok := g.recipeSchematic[r]; !ok || tier < ex.Tier {
				g.recipeSchematic[r] = schematicRef{Display: display, Tier: tier}
			}
		}

		fmt.Fprintf(
			&b,
			"\t%q: {ClassName: %q, DisplayName: %q, Type: %q, Tier: %d, Cost: %s, UnlockRecipes: %s},\n",
			className,
			className,
			display,
			schematicType,
			tier,
			itemAmountsGo(parseItemAmounts(field(c, "mCost"))),
			stringsGo(unlockRecipes),
		)
		g.schematicCount++
	}
	b.WriteString("}\n")
	g.write("schematics_gen.go", b.String())
}

func (g *generator) recipes() {
	var b strings.Builder
	b.WriteString("var Recipes = map[string]Recipe{\n")
	for _, c := range sortedByClassName(g.byNative["FGRecipe"]) {
		className := field(c, "ClassName")
		fmt.Fprintf(&b,
			"\t%q: {ClassName: %q, DisplayName: %q, Ingredients: %s, Products: %s, "+
				"DurationSec: %v, ProducedIn: %s, Alternate: %v},\n",
			className, className, field(c, "mDisplayName"),
			itemAmountsGo(parseItemAmounts(field(c, "mIngredients"))),
			itemAmountsGo(parseItemAmounts(field(c, "mProduct"))),
			floatField(c, "mManufactoringDuration"),
			stringsGo(parseClassList(field(c, "mProducedIn"))),
			g.alternates[className])
		g.recipeCount++
	}
	b.WriteString("}\n")
	g.write("recipes_gen.go", b.String())
}

func (g *generator) items() {
	raws := map[string]bool{}
	for _, c := range g.byNative["FGResourceDescriptor"] {
		raws[field(c, "ClassName")] = true
	}
	var all []map[string]json.RawMessage
	for _, native := range itemNatives {
		all = append(all, g.byNative[native]...)
	}
	var b strings.Builder
	b.WriteString("var Items = map[string]Item{\n")
	for _, c := range sortedByClassName(all) {
		className := field(c, "ClassName")
		extra := ""
		if waste := shortClassName(field(c, "mSpentFuelClass")); waste != "" {
			extra = fmt.Sprintf(", WasteClass: %q, WasteAmount: %d",
				waste, intField(c, "mAmountOfWaste"))
		}
		fmt.Fprintf(&b,
			"\t%q: {ClassName: %q, DisplayName: %q, Form: %q, StackSize: %q, "+
				"EnergyMJ: %v, SinkPoints: %d, Raw: %v%s},\n",
			className, className, field(c, "mDisplayName"), field(c, "mForm"),
			field(c, "mStackSize"), floatField(c, "mEnergyValue"),
			intField(c, "mResourceSinkPoints"), raws[className], extra)
		g.itemCount++
	}
	b.WriteString("}\n")
	g.write("items_gen.go", b.String())
}

type fuelEntry struct {
	MFuelClass string `json:"mFuelClass"`
}

func (g *generator) buildings() {
	type buildingNative struct {
		native string
		kind   string
	}
	natives := []buildingNative{
		{"FGBuildableManufacturer", "manufacturer"},
		{"FGBuildableManufacturerVariablePower", "manufacturerVariablePower"},
		{"FGBuildableResourceExtractor", "extractor"},
		{"FGBuildableWaterPump", "extractor"},
		{"FGBuildableFrackingExtractor", "extractor"},
		{"FGBuildableGeneratorFuel", "generator"},
		{"FGBuildableGeneratorNuclear", "generator"},
		{"FGBuildableGeneratorGeoThermal", "generator"},
	}

	var b strings.Builder
	b.WriteString("var Buildings = map[string]Building{\n")
	type row struct{ className, line string }
	var rows []row
	for _, n := range natives {
		for _, c := range g.byNative[n.native] {
			className := field(c, "ClassName")
			power := floatField(c, "mPowerConsumption")
			if n.kind == "manufacturerVariablePower" {
				power = floatField(c, "mEstimatedMaximumPowerConsumption")
			}
			var fuels []string
			var entries []fuelEntry
			if raw, ok := c["mFuel"]; ok {
				if err := json.Unmarshal(raw, &entries); err != nil {
					entries = nil
				}
			}
			for _, f := range entries {
				if f.MFuelClass != "" {
					fuels = append(fuels, shortClassName(f.MFuelClass))
				}
			}
			line := fmt.Sprintf(
				"\t%q: {ClassName: %q, DisplayName: %q, Kind: %q, PowerMW: %v, PowerProductionMW: %v, "+
					"FuelClasses: %s, SupplementalRatio: %v, ItemsPerCycle: %d, ExtractCycleSec: %v},\n",
				className,
				className,
				field(c, "mDisplayName"),
				n.kind,
				power,
				floatField(c, "mPowerProduction"),
				stringsGo(fuels),
				floatField(c, "mSupplementalToPowerRatio"),
				intField(c, "mItemsPerCycle"),
				floatField(c, "mExtractCycleTime"),
			)
			rows = append(rows, row{className, line})
			g.buildingCount++
		}
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].className < rows[j].className })
	for _, r := range rows {
		b.WriteString(r.line)
	}
	b.WriteString("}\n")
	g.write("buildings_gen.go", b.String())
}

// parserNames writes the parser package's canonical short-class-name →
// display-name table. The parser embeds no other reference data, so this is
// the single authoritative source it uses to render the in-game names that
// Coffee Stain's class paths famously disagree with (Desc_SteelPlate_C is
// "Steel Beam", not "Steel Plate"). Covers every class the parser turns into
// a user-facing name: items, recipes, buildings, and schematics.
func (g *generator) parserNames(parserOut string) {
	names := map[string]string{}
	add := func(natives ...string) {
		for _, native := range natives {
			for _, c := range g.byNative[native] {
				className := field(c, "ClassName")
				display := field(c, "mDisplayName")
				if className != "" && display != "" {
					names[className] = display
				}
			}
		}
	}
	add(itemNatives...)
	add(buildingNatives...)
	add("FGRecipe")
	add("FGSchematic")

	classes := make([]string, 0, len(names))
	for c := range names {
		classes = append(classes, c)
	}
	sort.Strings(classes)

	var b strings.Builder
	b.WriteString("// canonicalNames maps a short class name (with the trailing _C) to the\n")
	b.WriteString("// authoritative in-game display name from the shipped Docs.json. displayName\n")
	b.WriteString("// consults this before falling back to the class-path heuristic.\n")
	b.WriteString("var canonicalNames = map[string]string{\n")
	for _, c := range classes {
		fmt.Fprintf(&b, "\t%q: %q,\n", c, names[c])
	}
	b.WriteString("}\n")
	g.nameCount = len(classes)

	header := "// Code generated by plugins/satisfactory/tools/datagen. DO NOT EDIT.\n" +
		"// Source: CommunityResources/Docs/en-US.json from the game install.\n\npackage main\n\n"
	src, err := format.Source([]byte(header + b.String()))
	if err != nil {
		log.Fatalf("format names_gen.go: %v", err)
	}
	if err := os.WriteFile(parserOut+"/names_gen.go", src, 0o644); err != nil {
		log.Fatalf("write names_gen.go: %v", err)
	}
}

// parserMilestoneTiers writes the parser package's authoritative HUB-tier table
// for milestone schematics. Satisfactory's milestone class-name numbering
// (Schematic_5-3) is out of sync with the in-game tier (mTechTier) for several
// Tier 4-6 milestones — Schematic_5-3_C "Logistics Mk.3" is Tier 4, not 5 — so
// the parser must translate class to tier through this table rather than
// parsing the name.
func (g *generator) parserMilestoneTiers(parserOut string) {
	tiers := map[string]int{}
	for _, c := range g.byNative["FGSchematic"] {
		if field(c, "mType") != "EST_Milestone" {
			continue
		}
		if className := field(c, "ClassName"); className != "" {
			tiers[className] = intField(c, "mTechTier")
		}
	}

	classes := make([]string, 0, len(tiers))
	for c := range tiers {
		classes = append(classes, c)
	}
	sort.Strings(classes)

	var b strings.Builder
	b.WriteString("// milestoneTiers maps a HUB milestone schematic class (with the trailing _C)\n")
	b.WriteString(
		"// to its authoritative in-game tier (mTechTier). The class-name number is NOT\n",
	)
	b.WriteString("// a reliable tier — milestoneTier consults this table first.\n")
	b.WriteString("var milestoneTiers = map[string]int{\n")
	for _, c := range classes {
		fmt.Fprintf(&b, "\t%q: %d,\n", c, tiers[c])
	}
	b.WriteString("}\n")
	g.milestoneTierCount = len(classes)

	header := "// Code generated by plugins/satisfactory/tools/datagen. DO NOT EDIT.\n" +
		"// Source: CommunityResources/Docs/en-US.json from the game install.\n\npackage main\n\n"
	src, err := format.Source([]byte(header + b.String()))
	if err != nil {
		log.Fatalf("format milestones_gen.go: %v", err)
	}
	if err := os.WriteFile(parserOut+"/milestones_gen.go", src, 0o644); err != nil {
		log.Fatalf("write milestones_gen.go: %v", err)
	}
}

// stackSizeNumbers maps the game's mStackSize enum to its numeric maximum.
// SS_FLUID is the fluid-buffer capacity in m³-scaled units.
var stackSizeNumbers = map[string]int{
	"SS_ONE":    1,
	"SS_SMALL":  50,
	"SS_MEDIUM": 100,
	"SS_BIG":    200,
	"SS_HUGE":   500,
	"SS_FLUID":  50000,
}

// parserItemAmountsGo renders item/amount pairs as the parser's []itemAmount
// literal (distinct from the reference package's []ItemAmount).
func parserItemAmountsGo(pairs []pair) string {
	if len(pairs) == 0 {
		return "nil"
	}
	parts := make([]string, 0, len(pairs))
	for _, p := range pairs {
		parts = append(parts, fmt.Sprintf("{Class: %q, Amount: %d}", p.class, p.amount))
	}
	return "[]itemAmount{" + strings.Join(parts, ", ") + "}"
}

// parserRecipeIO is one recipe's parser-side data: its ingredient/product
// pairs and craft duration (seconds at 100% clock), used by the classifier and
// the flow-balance rate math.
type parserRecipeIO struct {
	ingredients []pair
	products    []pair
	durationSec float64
}

// parserProduction writes the parser package's item stack-size and recipe
// input/output tables, which the idle classifier uses to tell a blocked
// (output full) machine from a starved (input empty) one.
func (g *generator) parserProduction(parserOut string) {
	stacks := map[string]int{}
	var items []map[string]json.RawMessage
	for _, native := range itemNatives {
		items = append(items, g.byNative[native]...)
	}
	for _, c := range items {
		className := field(c, "ClassName")
		n, ok := stackSizeNumbers[field(c, "mStackSize")]
		if className == "" || !ok {
			continue
		}
		stacks[className] = n
	}

	recipes := map[string]parserRecipeIO{}
	for _, c := range g.byNative["FGRecipe"] {
		className := field(c, "ClassName")
		if className == "" {
			continue
		}
		recipes[className] = parserRecipeIO{
			ingredients: parseItemAmounts(field(c, "mIngredients")),
			products:    parseItemAmounts(field(c, "mProduct")),
			durationSec: floatField(c, "mManufactoringDuration"),
		}
	}

	stackClasses := make([]string, 0, len(stacks))
	for c := range stacks {
		stackClasses = append(stackClasses, c)
	}
	sort.Strings(stackClasses)
	recipeClasses := make([]string, 0, len(recipes))
	for c := range recipes {
		recipeClasses = append(recipeClasses, c)
	}
	sort.Strings(recipeClasses)

	var b strings.Builder
	b.WriteString("// itemStackSize maps an item class (with the trailing _C) to its maximum\n")
	b.WriteString("// stack size. Fluids (SS_FLUID) are in m³-scaled units.\n")
	b.WriteString("var itemStackSize = map[string]int{\n")
	for _, c := range stackClasses {
		fmt.Fprintf(&b, "\t%q: %d,\n", c, stacks[c])
	}
	b.WriteString("}\n\n")
	b.WriteString("// recipeIO maps a recipe class (with the trailing _C) to its ingredients,\n")
	b.WriteString("// products, and craft duration — for the idle classifier's starved/blocked\n")
	b.WriteString("// distinction and the flow-balance per-minute rate math.\n")
	b.WriteString("var recipeIO = map[string]recipeSpec{\n")
	for _, c := range recipeClasses {
		io := recipes[c]
		fmt.Fprintf(
			&b,
			"\t%q: {Ingredients: %s, Products: %s, DurationSec: %v},\n",
			c,
			parserItemAmountsGo(io.ingredients),
			parserItemAmountsGo(io.products),
			io.durationSec,
		)
	}
	b.WriteString("}\n")
	g.productionCount = len(recipeClasses)

	header := "// Code generated by plugins/satisfactory/tools/datagen. DO NOT EDIT.\n" +
		"// Source: CommunityResources/Docs/en-US.json from the game install.\n\npackage main\n\n"
	src, err := format.Source([]byte(header + b.String()))
	if err != nil {
		log.Fatalf("format production_gen.go: %v", err)
	}
	if err := os.WriteFile(parserOut+"/production_gen.go", src, 0o644); err != nil {
		log.Fatalf("write production_gen.go: %v", err)
	}
}

// parserBelts writes the parser package's belt/lift throughput table: each
// conveyor class's item throughput in items/min, derived from the game's
// mSpeed (items/min = mSpeed / 2).
func (g *generator) parserBelts(parserOut string) {
	type beltSpeed struct {
		class  string
		perMin float64
	}
	var belts []beltSpeed
	for _, native := range []string{"FGBuildableConveyorBelt", "FGBuildableConveyorLift"} {
		for _, c := range g.byNative[native] {
			class := field(c, "ClassName")
			if class == "" {
				continue
			}
			belts = append(belts, beltSpeed{class: class, perMin: floatField(c, "mSpeed") / 2})
		}
	}
	sort.Slice(belts, func(i, j int) bool { return belts[i].class < belts[j].class })

	var b strings.Builder
	b.WriteString("// beltThroughput maps a conveyor belt/lift class (with the trailing _C) to\n")
	b.WriteString("// its item throughput in items/min (the game's mSpeed / 2).\n")
	b.WriteString("var beltThroughput = map[string]float64{\n")
	for _, bs := range belts {
		fmt.Fprintf(&b, "\t%q: %v,\n", bs.class, bs.perMin)
	}
	b.WriteString("}\n")

	header := "// Code generated by plugins/satisfactory/tools/datagen. DO NOT EDIT.\n" +
		"// Source: CommunityResources/Docs/en-US.json from the game install.\n\npackage main\n\n"
	src, err := format.Source([]byte(header + b.String()))
	if err != nil {
		log.Fatalf("format belts_gen.go: %v", err)
	}
	if err := os.WriteFile(parserOut+"/belts_gen.go", src, 0o644); err != nil {
		log.Fatalf("write belts_gen.go: %v", err)
	}
}
