// Code generated by datagen; DO NOT EDIT.

package data

// Drugs is all drug items with their economy and addiction data.
var Drugs = []Drug{
	{DefName: "Beer", Label: "beer", MarketValue: 12.0, Category: "Social", WorkAmount: 0.0, Ingredients: nil, Addictiveness: 0.01, MinToleranceToAddict: 0.25, ExistingAddictionOffset: 0.2, NeedLevelOffset: 0.9, OverdoseSeverity: 0.0, LargeOverdoseChance: 0.0},
	{DefName: "Ambrosia", Label: "ambrosia", MarketValue: 15.0, Category: "Social", WorkAmount: 0.0, Ingredients: nil, Addictiveness: 0.01, MinToleranceToAddict: 0.15, ExistingAddictionOffset: 0.1, NeedLevelOffset: 0.9, OverdoseSeverity: 0.0, LargeOverdoseChance: 0.0},
	{DefName: "GoJuice", Label: "go-juice", MarketValue: 53.0, Category: "Hard", WorkAmount: 600.0, Ingredients: []string{"Neutroamine:2", "Yayo:1"}, Addictiveness: 0.026, MinToleranceToAddict: 0.0, ExistingAddictionOffset: 0.2, NeedLevelOffset: 0.9, OverdoseSeverity: 0.18, LargeOverdoseChance: 0.0},
	{DefName: "Luciferium", Label: "luciferium", MarketValue: 70.0, Category: "Medical", WorkAmount: 0.0, Ingredients: nil, Addictiveness: 1.0, MinToleranceToAddict: 0.0, ExistingAddictionOffset: 0.0, NeedLevelOffset: 0.9, OverdoseSeverity: 0.0, LargeOverdoseChance: 0.0},
	{DefName: "Penoxycyline", Label: "penoxycyline", MarketValue: 18.0, Category: "Medical", WorkAmount: 600.0, Ingredients: []string{"Neutroamine:2"}, Addictiveness: 0.0, MinToleranceToAddict: 0.0, ExistingAddictionOffset: 0.0, NeedLevelOffset: 0.0, OverdoseSeverity: 0.08, LargeOverdoseChance: 0.0},
	{DefName: "Flake", Label: "flake", MarketValue: 14.0, Category: "Hard", WorkAmount: 250.0, Ingredients: []string{"PsychoidLeaves:4"}, Addictiveness: 0.05, MinToleranceToAddict: 0.0, ExistingAddictionOffset: 0.3, NeedLevelOffset: 0.9, OverdoseSeverity: 0.18, LargeOverdoseChance: 0.0},
	{DefName: "PsychiteTea", Label: "psychite tea", MarketValue: 10.0, Category: "Social", WorkAmount: 400.0, Ingredients: []string{"PsychoidLeaves:4"}, Addictiveness: 0.02, MinToleranceToAddict: 0.1, ExistingAddictionOffset: 0.15, NeedLevelOffset: 0.9, OverdoseSeverity: 0.0, LargeOverdoseChance: 0.0},
	{DefName: "Yayo", Label: "yayo", MarketValue: 21.0, Category: "Hard", WorkAmount: 350.0, Ingredients: []string{"PsychoidLeaves:8"}, Addictiveness: 0.01, MinToleranceToAddict: 0.0, ExistingAddictionOffset: 0.2, NeedLevelOffset: 0.9, OverdoseSeverity: 0.18, LargeOverdoseChance: 0.0},
	{DefName: "SmokeleafJoint", Label: "smokeleaf joint", MarketValue: 11.0, Category: "Social", WorkAmount: 450.0, Ingredients: []string{"SmokeleafLeaves:4"}, Addictiveness: 0.02, MinToleranceToAddict: 0.15, ExistingAddictionOffset: 0.06, NeedLevelOffset: 0.9, OverdoseSeverity: 0.0, LargeOverdoseChance: 0.0},
	{DefName: "WakeUp", Label: "wake-up", MarketValue: 35.0, Category: "Hard", WorkAmount: 900.0, Ingredients: []string{"Neutroamine:2"}, Addictiveness: 0.02, MinToleranceToAddict: 0.0, ExistingAddictionOffset: 0.2, NeedLevelOffset: 0.9, OverdoseSeverity: 0.18, LargeOverdoseChance: 0.0},
	{DefName: "Drug_Psilocap", Label: "psilocap", MarketValue: 10.0, Category: "Social", WorkAmount: 0.0, Ingredients: nil, Addictiveness: 0.0, MinToleranceToAddict: 1.0, ExistingAddictionOffset: 0.0, NeedLevelOffset: 0.9, OverdoseSeverity: 0.18, LargeOverdoseChance: 0.0},
}
