// Code generated by datagen; DO NOT EDIT.

package data

// Medicines is all medicine items with their medical potency.
var Medicines = []Medicine{
	{DefName: "MedicineHerbal", Label: "herbal medicine", MedicalPotency: 0.60},
	{DefName: "MedicineIndustrial", Label: "medicine", MedicalPotency: 1.00},
	{DefName: "MedicineUltratech", Label: "glitterworld medicine", MedicalPotency: 1.60},
}

// Beds is all bed/sleeping items with their surgery success chance factor.
var Beds = []Bed{
	{DefName: "AncientBed", Label: "ancient bed", SurgerySuccessChanceFactor: 0.65},
	{DefName: "SleepingSpot", Label: "sleeping spot", SurgerySuccessChanceFactor: 0.7},
	{DefName: "DoubleSleepingSpot", Label: "double sleeping spot", SurgerySuccessChanceFactor: 0.7},
	{DefName: "Bed", Label: "bed", SurgerySuccessChanceFactor: 1},
	{DefName: "DoubleBed", Label: "double bed", SurgerySuccessChanceFactor: 1},
	{DefName: "RoyalBed", Label: "royal bed", SurgerySuccessChanceFactor: 1},
	{DefName: "HospitalBed", Label: "hospital bed", SurgerySuccessChanceFactor: 1.1},
	{DefName: "AnimalSleepingSpot", Label: "animal sleeping spot", SurgerySuccessChanceFactor: 0.7},
	{DefName: "AnimalSleepingBox", Label: "animal sleeping box", SurgerySuccessChanceFactor: 1},
	{DefName: "AnimalBed", Label: "animal bed", SurgerySuccessChanceFactor: 1},
	{DefName: "SlabBed", Label: "slab bed", SurgerySuccessChanceFactor: 1},
	{DefName: "SlabDoubleBed", Label: "slab double bed", SurgerySuccessChanceFactor: 1},
	{DefName: "DeathrestCasket", Label: "deathrest casket", SurgerySuccessChanceFactor: 1},
	{DefName: "BabySleepingSpot", Label: "baby sleeping spot", SurgerySuccessChanceFactor: 0.7},
	{DefName: "Crib", Label: "crib", SurgerySuccessChanceFactor: 1},
	{DefName: "AncientSingleBed", Label: "rusted bed", SurgerySuccessChanceFactor: 0.62},
	{DefName: "AncientDoubleBed", Label: "rusted double bed", SurgerySuccessChanceFactor: 0.62},
}
