// Code generated by plugins/songsofsyx/tools/datagen. DO NOT EDIT.
// Source: data/assets/init/race/*.txt + text/race/*.txt (game-shipped).

package data

// Races maps a species ID to its stats and description.
var Races = map[string]Race{
	"ARGONOSH": {
		ID:             "ARGONOSH",
		Name:           "Argonosh",
		Description:    "The Argonosh are a very ancient race, created by Aminion during the first war of the gods. They are heavy, fast and deadly. They do not need much, but should also be kept from work.",
		Playable:       false,
		SlavePrice:     1,
		PreferredFoods: []string{"MEAT", "FISH", "EGG"},
	},
	"CANTOR": {
		ID:             "CANTOR",
		Name:           "Cantor",
		Description:    "Cantors are mythical giants. The few of them that remain are primarily found in the north. They excel at battle, but are difficult to obtain and please.",
		Playable:       false,
		SlavePrice:     1,
		PreferredFoods: []string{"EGG", "MEAT", "FISH"},
	},
	"CRETONIAN": {
		ID:             "CRETONIAN",
		Name:           "Cretonian",
		Description:    "Cretonians excel at farming and thrive in temperate and warm climates, preferably close to water. They are vegetarians and prefer harmony and wooden structures.",
		Playable:       true,
		BabyDays:       8,
		ChildDays:      48,
		PreferredFoods: []string{"VEGETABLE", "BREAD", "FRUIT"},
	},
	"DONDORIAN": {
		ID:             "DONDORIAN",
		Name:           "Dondorian",
		Description:    "Dondorians are sturdy and stubborn. Don't care much for farming, but excel at mining, enjoy refinement, and are sturdy in battle.",
		Playable:       true,
		SlavePrice:     12,
		PreferredFoods: []string{"MEAT", "FISH", "MUSHROOM"},
	},
	"GARTHIMI": {
		ID:             "GARTHIMI",
		Name:           "Garthimi",
		Description:    "Garthimi love death and destruction while caring little for the finer things in life. High reproductive rate makes them perfect cannon fodder, but given the right training and equipment, they can become quite proficient.  Their ability to raise cavern Balticrawlers gives ample food to feed their hive.  They require humidifiers to reach an ideal environment.",
		Playable:       true,
		SlavePrice:     6,
		ChildDays:      16,
		PreferredFoods: []string{"MEAT", "FISH"},
	},
	"HUMAN": {
		ID:             "HUMAN",
		Name:           "Human",
		Description:    "Humans, said to be the last creation of the gods. Excel at intelligent jobs and are decent farmers. They can be a constant headache with insanity, criminal behavior, and demands for lavish surroundings.",
		Playable:       true,
		SlavePrice:     11,
		BabyDays:       12,
		ChildDays:      80,
		PreferredFoods: []string{"BREAD", "MEAT", "MUSHROOM", "EGG"},
	},
	"Q_AMEVIA": {
		ID:             "Q_AMEVIA",
		Name:           "Amevia",
		Description:    "Amevias love water and thrive when living surrounded by rivers and canals. They have an insatiable desire for fish. They are generally good-natured but they greatly prefer to be among their own kind. Amevia will fight against oppression and are not submissive. They are unique in their ability to handle Globdein ranching.",
		Playable:       true,
		SlavePrice:     11,
		BabyDays:       10,
		ChildDays:      80,
		PreferredFoods: []string{"FISH", "VEGETABLE", "EGG"},
	},
	"TILAPI": {
		ID:             "TILAPI",
		Name:           "Tilapi",
		Description:    "Tilapis, the territorial and bloodthirsty guardians of Syx' forests, are perfectly suited to tend to forestry, animal husbandry, and dispensing swift death alike. They are no strangers to cannibalism.",
		Playable:       true,
		SlavePrice:     10,
		BabyDays:       10,
		ChildDays:      64,
		PreferredFoods: []string{"MEAT", "FRUIT", "EGG"},
	},
}
