// Build-time manifest embedding for MCP tools.
//
// Reads plugins/*/manifest.json, strips deployment-specific fields,
// and generates worker/src/mcp/manifests.gen.ts with typed manifest
// data keyed by game_id.
//
// Usage: npx tsx scripts/build-manifests.ts

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PLUGINS_DIR = resolve(ROOT, "plugins");
const OUTPUT_FILE = resolve(ROOT, "worker/src/mcp/manifests.gen.ts");

// Fields to strip from the top-level manifest (daemon-only / deployment artifacts).
const STRIP_TOP_LEVEL = new Set([
  "sha256",
  "url",
  "version",
  "default_paths",
  "file_extensions",
  "file_patterns",
  "author",
  "homepage",
  "workshop_url",
  "adapter",
]);

// Fields to strip from reference (deployment artifacts for WASM binary).
const STRIP_REFERENCE = new Set(["sha256", "url"]);

interface ReferenceModule {
  name: string;
  description: string;
  parameters?: Record<string, unknown>;
  section_mappings?: Record<string, string>;
  attribution?: unknown;
  view_default?: string;
}

interface Manifest {
  game_id: string;
  name?: string;
  icon?: string;
  sources?: string[];
  description?: string;
  channel?: string;
  coverage?: string;
  limitations?: string[];
  reference?: {
    modules?: Record<string, ReferenceModule>;
  };
}

function discoverManifests(): Manifest[] {
  const manifests: Manifest[] = [];

  let plugins: string[];
  try {
    plugins = readdirSync(PLUGINS_DIR);
  } catch {
    throw new Error(`Cannot read plugins directory: ${PLUGINS_DIR}`);
  }

  for (const plugin of plugins.toSorted()) {
    const manifestPath = resolve(PLUGINS_DIR, plugin, "manifest.json");
    let raw: string;
    try {
      raw = readFileSync(manifestPath, "utf-8");
    } catch {
      continue; // No manifest in this plugin directory
    }

    const data = JSON.parse(raw) as Record<string, unknown>;

    if (!data.game_id || typeof data.game_id !== "string") {
      throw new Error(`${manifestPath}: missing or invalid game_id`);
    }

    // Strip deployment-specific top-level fields.
    const stripped: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(data)) {
      if (!STRIP_TOP_LEVEL.has(key)) {
        stripped[key] = value;
      }
    }

    // Strip deployment-specific reference fields (sha256, url for the WASM binary).
    if (stripped.reference && typeof stripped.reference === "object") {
      const ref = stripped.reference as Record<string, unknown>;
      const cleanRef: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(ref)) {
        if (!STRIP_REFERENCE.has(key)) {
          cleanRef[key] = value;
        }
      }
      stripped.reference = cleanRef;
    }

    manifests.push(stripped as unknown as Manifest);
  }

  return manifests;
}

function generate(manifests: Manifest[]): string {
  const lines: string[] = [
    "// Auto-generated by scripts/build-manifests.ts. Do not edit.",
    "// prettier-ignore",
    "",
    "export interface ManifestReferenceModule {",
    "  name: string;",
    "  description: string;",
    "  parameters?: Record<string, unknown>;",
    "  section_mappings?: Record<string, string>;",
    "  attribution?: unknown;",
    "  view_default?: string;",
    "}",
    "",
    "export interface ManifestData {",
    "  game_id: string;",
    "  name?: string;",
    "  icon?: string;",
    "  sources?: string[];",
    "  description?: string;",
    "  channel?: string;",
    "  coverage?: string;",
    "  limitations?: string[];",
    "  reference?: {",
    "    modules?: Record<string, ManifestReferenceModule>;",
    "  };",
    "}",
    "",
    `const DATA: ManifestData[] = ${JSON.stringify(manifests, null, 2)};`,
    "",
    "/** All game manifests indexed by game_id. O(1) lookup. */",
    "export const MANIFESTS: ReadonlyMap<string, ManifestData> = new Map(",
    '  DATA.map((m) => [m.game_id, m] as const),',
    ");",
    "",
    "/** All game manifests as an array, for iteration. */",
    "export const MANIFEST_LIST: readonly ManifestData[] = DATA;",
    "",
  ];

  return lines.join("\n");
}

function main(): void {
  const manifests = discoverManifests();

  if (manifests.length === 0) {
    throw new Error("No manifests found — expected at least one in plugins/*/manifest.json");
  }

  const output = generate(manifests);
  writeFileSync(OUTPUT_FILE, output);

  console.log(`Written to ${OUTPUT_FILE}`);
  console.log(`  ${String(manifests.length)} manifests: ${manifests.map((m) => m.game_id).join(", ")}`);
}

main();
