// Code generated by plugins/factorio/tools/datagen. DO NOT EDIT.
package data

var Spawners = map[string]Spawner{
	"biter-spawner": {Name: "biter-spawner", Units: []SpawnerUnit{
		{Name: "small-biter", Weights: []SpawnWeight{{Evolution: 0, Weight: 0.3}, {Evolution: 0.6, Weight: 0}}},
		{Name: "medium-biter", Weights: []SpawnWeight{{Evolution: 0.2, Weight: 0}, {Evolution: 0.6, Weight: 0.3}, {Evolution: 0.7, Weight: 0.1}}},
		{Name: "big-biter", Weights: []SpawnWeight{{Evolution: 0.5, Weight: 0}, {Evolution: 1, Weight: 0.4}}},
		{Name: "behemoth-biter", Weights: []SpawnWeight{{Evolution: 0.9, Weight: 0}, {Evolution: 1, Weight: 0.3}}},
	}},
	"gleba-spawner": {Name: "gleba-spawner", Units: []SpawnerUnit{
		{Name: "small-wriggler-pentapod", Weights: []SpawnWeight{{Evolution: 0, Weight: 0.4}, {Evolution: 0.1, Weight: 0.4}, {Evolution: 0.6, Weight: 0}}},
		{Name: "small-strafer-pentapod", Weights: []SpawnWeight{{Evolution: 0, Weight: 0.4}, {Evolution: 0.1, Weight: 0.4}, {Evolution: 0.6, Weight: 0}}},
		{Name: "small-stomper-pentapod", Weights: []SpawnWeight{{Evolution: 0, Weight: 0.2}, {Evolution: 0.1, Weight: 0.2}, {Evolution: 0.6, Weight: 0}}},
		{Name: "medium-wriggler-pentapod", Weights: []SpawnWeight{{Evolution: 0.1, Weight: 0}, {Evolution: 0.6, Weight: 0.4}, {Evolution: 0.95, Weight: 0}}},
		{Name: "medium-strafer-pentapod", Weights: []SpawnWeight{{Evolution: 0.1, Weight: 0}, {Evolution: 0.6, Weight: 0.4}, {Evolution: 0.95, Weight: 0}}},
		{Name: "medium-stomper-pentapod", Weights: []SpawnWeight{{Evolution: 0.1, Weight: 0}, {Evolution: 0.6, Weight: 0.2}, {Evolution: 0.95, Weight: 0}}},
		{Name: "big-wriggler-pentapod", Weights: []SpawnWeight{{Evolution: 0.6, Weight: 0}, {Evolution: 0.95, Weight: 0.4}, {Evolution: 1, Weight: 0.4}}},
		{Name: "big-strafer-pentapod", Weights: []SpawnWeight{{Evolution: 0.6, Weight: 0}, {Evolution: 0.95, Weight: 0.4}, {Evolution: 1, Weight: 0.4}}},
		{Name: "big-stomper-pentapod", Weights: []SpawnWeight{{Evolution: 0.6, Weight: 0}, {Evolution: 0.95, Weight: 0.2}, {Evolution: 1, Weight: 0.2}}},
	}},
	"gleba-spawner-small": {Name: "gleba-spawner-small", Units: []SpawnerUnit{
		{Name: "small-wriggler-pentapod", Weights: []SpawnWeight{{Evolution: 0, Weight: 0.9}, {Evolution: 0.1, Weight: 0.9}, {Evolution: 0.6, Weight: 0}}},
		{Name: "medium-wriggler-pentapod", Weights: []SpawnWeight{{Evolution: 0.1, Weight: 0}, {Evolution: 0.6, Weight: 0.9}, {Evolution: 0.95, Weight: 0}}},
		{Name: "big-wriggler-pentapod", Weights: []SpawnWeight{{Evolution: 0.6, Weight: 0}, {Evolution: 0.95, Weight: 0.9}, {Evolution: 1, Weight: 0.9}}},
	}},
	"spitter-spawner": {Name: "spitter-spawner", Units: []SpawnerUnit{
		{Name: "small-biter", Weights: []SpawnWeight{{Evolution: 0, Weight: 0.3}, {Evolution: 0.35, Weight: 0}}},
		{Name: "small-spitter", Weights: []SpawnWeight{{Evolution: 0.25, Weight: 0}, {Evolution: 0.5, Weight: 0.3}, {Evolution: 0.7, Weight: 0}}},
		{Name: "medium-spitter", Weights: []SpawnWeight{{Evolution: 0.4, Weight: 0}, {Evolution: 0.7, Weight: 0.3}, {Evolution: 0.9, Weight: 0.1}}},
		{Name: "big-spitter", Weights: []SpawnWeight{{Evolution: 0.5, Weight: 0}, {Evolution: 1, Weight: 0.4}}},
		{Name: "behemoth-spitter", Weights: []SpawnWeight{{Evolution: 0.9, Weight: 0}, {Evolution: 1, Weight: 0.3}}},
	}},
}

var EnemyTiers = []EnemyTier{
	{Name: "medium-worm-turret", Threshold: 0.3},
	{Name: "big-worm-turret", Threshold: 0.5},
	{Name: "behemoth-worm-turret", Threshold: 0.9},
}
