// Code generated by plugins/factorio/tools/datagen. DO NOT EDIT.
package data

var Modules = map[string]Module{
	"efficiency-module": {Name: "efficiency-module", Category: "efficiency", Tier: 1, Effects: ModuleEffects{Speed: 0, Consumption: -0.3, Productivity: 0, Pollution: 0, Quality: 0}},
	"efficiency-module-2": {Name: "efficiency-module-2", Category: "efficiency", Tier: 2, Effects: ModuleEffects{Speed: 0, Consumption: -0.4, Productivity: 0, Pollution: 0, Quality: 0}},
	"efficiency-module-3": {Name: "efficiency-module-3", Category: "efficiency", Tier: 3, Effects: ModuleEffects{Speed: 0, Consumption: -0.5, Productivity: 0, Pollution: 0, Quality: 0}},
	"productivity-module": {Name: "productivity-module", Category: "productivity", Tier: 1, Effects: ModuleEffects{Speed: -0.05, Consumption: 0.4, Productivity: 0.04, Pollution: 0.05, Quality: 0}},
	"productivity-module-2": {Name: "productivity-module-2", Category: "productivity", Tier: 2, Effects: ModuleEffects{Speed: -0.1, Consumption: 0.6, Productivity: 0.06, Pollution: 0.07, Quality: 0}},
	"productivity-module-3": {Name: "productivity-module-3", Category: "productivity", Tier: 3, Effects: ModuleEffects{Speed: -0.15, Consumption: 0.8, Productivity: 0.1, Pollution: 0.1, Quality: 0}},
	"quality-module": {Name: "quality-module", Category: "quality", Tier: 1, Effects: ModuleEffects{Speed: -0.05, Consumption: 0, Productivity: 0, Pollution: 0, Quality: 0.1}},
	"quality-module-2": {Name: "quality-module-2", Category: "quality", Tier: 2, Effects: ModuleEffects{Speed: -0.05, Consumption: 0, Productivity: 0, Pollution: 0, Quality: 0.2}},
	"quality-module-3": {Name: "quality-module-3", Category: "quality", Tier: 3, Effects: ModuleEffects{Speed: -0.05, Consumption: 0, Productivity: 0, Pollution: 0, Quality: 0.25}},
	"speed-module": {Name: "speed-module", Category: "speed", Tier: 1, Effects: ModuleEffects{Speed: 0.2, Consumption: 0.5, Productivity: 0, Pollution: 0, Quality: -0.1}},
	"speed-module-2": {Name: "speed-module-2", Category: "speed", Tier: 2, Effects: ModuleEffects{Speed: 0.3, Consumption: 0.6, Productivity: 0, Pollution: 0, Quality: -0.15}},
	"speed-module-3": {Name: "speed-module-3", Category: "speed", Tier: 3, Effects: ModuleEffects{Speed: 0.5, Consumption: 0.7, Productivity: 0, Pollution: 0, Quality: -0.25}},
}
