// Command datagen reads D2R game data TSV files and generates Go source files
// for the reference module's data package.
//
// The input TSV files (TreasureClassEx.txt, itemratio.txt, etc.) are extracted
// from D2R's CASC archives using the casc-extract tool. To regenerate:
//
//	cd plugins/d2r && just extract-gamedata   # extract TSVs from CASC
//	go run ./plugins/d2r/tools/datagen        # generate Go source
//
// Usage:
//
//	go run ./plugins/d2r/tools/datagen -input .reference/d2r-rotw-excel -output plugins/d2r/reference/data
package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	inputDir := ".reference/d2r-rotw-excel"
	outputDir := "plugins/d2r/reference/data"

	for i := 1; i < len(os.Args); i++ {
		switch os.Args[i] {
		case "-input":
			i++
			inputDir = os.Args[i]
		case "-output":
			i++
			outputDir = os.Args[i]
		}
	}

	generators := []struct {
		name string
		fn   func(string, string) error
	}{
		{"treasure_classes", genTreasureClasses},
		{"item_ratios", genItemRatios},
		{"base_items", genBaseItems},
		{"item_types", genItemTypes},
		{"monsters", genMonsters},
		{"areas", genAreas},
		{"item_aliases", genItemAliases},
	}

	for _, g := range generators {
		fmt.Printf("Generating %s...\n", g.name)
		if err := g.fn(inputDir, outputDir); err != nil {
			fmt.Fprintf(os.Stderr, "Error generating %s: %v\n", g.name, err)
			os.Exit(1)
		}
	}
	fmt.Println("Done.")
}

// readTSV reads a tab-separated file and returns rows as maps keyed by header.
func readTSV(path string) ([]map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.Comma = '\t'
	r.LazyQuotes = true
	r.FieldsPerRecord = -1 // variable-length rows

	headers, err := r.Read()
	if err != nil {
		return nil, fmt.Errorf("reading headers: %w", err)
	}

	var rows []map[string]string
	for {
		record, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		row := make(map[string]string, len(headers))
		for i, h := range headers {
			if i < len(record) {
				row[h] = strings.TrimSpace(record[i])
			}
		}
		rows = append(rows, row)
	}
	return rows, nil
}

func atoi(s string) int {
	n, _ := strconv.Atoi(s)
	return n
}

func goStr(s string) string {
	return strconv.Quote(s)
}

// genTreasureClasses generates treasure_classes_gen.go from TreasureClassEx.txt.
func genTreasureClasses(inputDir, outputDir string) error {
	rows, err := readTSV(filepath.Join(inputDir, "treasureclassex.txt"))
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by plugins/d2r/tools/datagen. DO NOT EDIT.\n\n")
	b.WriteString("package data\n\n")
	b.WriteString("// TreasureClasses contains all TC definitions from TreasureClassEx.txt.\n")
	b.WriteString("var TreasureClasses = []TreasureClass{\n")

	for _, row := range rows {
		name := row["Treasure Class"]
		if name == "" {
			continue
		}

		// Collect item/prob pairs.
		var items []struct {
			name string
			prob int
		}
		for i := 1; i <= 10; i++ {
			itemKey := fmt.Sprintf("Item%d", i)
			probKey := fmt.Sprintf("Prob%d", i)
			itemName := row[itemKey]
			if itemName == "" {
				continue
			}
			// Strip CSV quoting and ",mul=X" gold multiplier suffix.
			itemName = strings.TrimPrefix(itemName, "\"")
			if idx := strings.Index(itemName, ","); idx >= 0 {
				itemName = itemName[:idx]
			}
			itemName = strings.TrimSuffix(itemName, "\"")
			prob := atoi(row[probKey])
			items = append(items, struct {
				name string
				prob int
			}{itemName, prob})
		}

		b.WriteString("\t{")
		fmt.Fprintf(&b, "Name: %s", goStr(name))
		if g := atoi(row["group"]); g != 0 {
			fmt.Fprintf(&b, ", Group: %d", g)
		}
		if l := atoi(row["level"]); l != 0 {
			fmt.Fprintf(&b, ", Level: %d", l)
		}
		fmt.Fprintf(&b, ", Picks: %d", atoi(row["Picks"]))
		if nd := atoi(row["NoDrop"]); nd != 0 {
			fmt.Fprintf(&b, ", NoDrop: %d", nd)
		}

		u, s, r, m := atoi(row["Unique"]), atoi(row["Set"]), atoi(row["Rare"]), atoi(row["Magic"])
		if u != 0 || s != 0 || r != 0 || m != 0 {
			fmt.Fprintf(&b, ", Quality: QualityRatios{Unique: %d, Set: %d, Rare: %d, Magic: %d}", u, s, r, m)
		}

		if len(items) > 0 {
			b.WriteString(", Items: []TCOutcome{")
			for j, it := range items {
				if j > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "{%s, %d}", goStr(it.name), it.prob)
			}
			b.WriteString("}")
		}

		b.WriteString("},\n")
	}

	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(outputDir, "treasure_classes_gen.go"), []byte(b.String()), 0644)
}

// genItemRatios generates item_ratios_gen.go from itemratio.txt.
func genItemRatios(inputDir, outputDir string) error {
	rows, err := readTSV(filepath.Join(inputDir, "itemratio.txt"))
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by plugins/d2r/tools/datagen. DO NOT EDIT.\n\n")
	b.WriteString("package data\n\n")
	b.WriteString("// ItemRatios contains quality determination parameters from itemratio.txt.\n")
	b.WriteString("// Only version 1 (LoD/D2R) rows are included.\n")
	b.WriteString("var ItemRatios = []ItemRatioEntry{\n")

	for _, row := range rows {
		version := atoi(row["Version"])
		if version != 1 {
			continue
		}
		isUber := row["Uber"] == "1"
		isClassSpecific := row["Class Specific"] == "1"

		b.WriteString("\t{")
		if isUber {
			b.WriteString("IsUber: true, ")
		}
		if isClassSpecific {
			b.WriteString("IsClassSpecific: true, ")
		}
		fmt.Fprintf(&b, "Unique: QualityModifiers{%d, %d, %d}", atoi(row["Unique"]), atoi(row["UniqueDivisor"]), atoi(row["UniqueMin"]))
		fmt.Fprintf(&b, ", Set: QualityModifiers{%d, %d, %d}", atoi(row["Set"]), atoi(row["SetDivisor"]), atoi(row["SetMin"]))
		fmt.Fprintf(&b, ", Rare: QualityModifiers{%d, %d, %d}", atoi(row["Rare"]), atoi(row["RareDivisor"]), atoi(row["RareMin"]))
		fmt.Fprintf(&b, ", Magic: QualityModifiers{%d, %d, %d}", atoi(row["Magic"]), atoi(row["MagicDivisor"]), atoi(row["MagicMin"]))
		b.WriteString("},\n")
	}

	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(outputDir, "item_ratios_gen.go"), []byte(b.String()), 0644)
}

// genBaseItems generates base_items_gen.go from armor.txt, weapons.txt, misc.txt.
func genBaseItems(inputDir, outputDir string) error {
	var allItems []map[string]string

	for _, file := range []string{"armor.txt", "weapons.txt", "misc.txt"} {
		rows, err := readTSV(filepath.Join(inputDir, file))
		if err != nil {
			return fmt.Errorf("reading %s: %w", file, err)
		}
		allItems = append(allItems, rows...)
	}

	var b strings.Builder
	b.WriteString("// Code generated by plugins/d2r/tools/datagen. DO NOT EDIT.\n\n")
	b.WriteString("package data\n\n")
	b.WriteString("// BaseItems contains all armor, weapon, and misc items.\n")
	b.WriteString("var BaseItems = []BaseItem{\n")

	for _, row := range allItems {
		code := row["code"]
		name := row["name"]
		if code == "" || name == "" {
			continue
		}
		// Only spawnable items.
		if row["spawnable"] != "1" {
			continue
		}
		// Skip quest items.
		if row["type"] == "ques" {
			continue
		}

		level := atoi(row["level"])
		itemType := row["type"]
		normCode := row["normcode"]
		uberCode := row["ubercode"]
		ultraCode := row["ultracode"]

		b.WriteString("\t{")
		fmt.Fprintf(&b, "Name: %s, Code: %s, Type: %s, Level: %d",
			goStr(name), goStr(code), goStr(itemType), level)
		if normCode != "" {
			fmt.Fprintf(&b, ", NormCode: %s", goStr(normCode))
		}
		if uberCode != "" {
			fmt.Fprintf(&b, ", UberCode: %s", goStr(uberCode))
		}
		if ultraCode != "" {
			fmt.Fprintf(&b, ", UltraCode: %s", goStr(ultraCode))
		}
		b.WriteString("},\n")
	}

	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(outputDir, "base_items_gen.go"), []byte(b.String()), 0644)
}

// genItemTypes generates item_types_gen.go from ItemTypes.txt.
func genItemTypes(inputDir, outputDir string) error {
	rows, err := readTSV(filepath.Join(inputDir, "itemtypes.txt"))
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by plugins/d2r/tools/datagen. DO NOT EDIT.\n\n")
	b.WriteString("package data\n\n")
	b.WriteString("// ItemTypes contains item type metadata from ItemTypes.txt.\n")
	b.WriteString("var ItemTypes = []ItemType{\n")

	for _, row := range rows {
		code := row["Code"]
		if code == "" {
			continue
		}

		name := row["ItemType"]
		equiv1 := row["Equiv1"]
		equiv2 := row["Equiv2"]
		rarity := atoi(row["Rarity"])
		isClassSpecific := row["Class"] != ""
		canBeRare := row["Rare"] != "0" && row["Rare"] != ""
		// Normal column: 1 means only-normal (no magic). Inverted for canBeMagic.
		canBeMagic := row["Normal"] != "1"

		b.WriteString("\t{")
		fmt.Fprintf(&b, "Code: %s, Name: %s", goStr(code), goStr(name))
		if equiv1 != "" {
			fmt.Fprintf(&b, ", Equiv1: %s", goStr(equiv1))
		}
		if equiv2 != "" {
			fmt.Fprintf(&b, ", Equiv2: %s", goStr(equiv2))
		}
		fmt.Fprintf(&b, ", Rarity: %d", rarity)
		if isClassSpecific {
			b.WriteString(", IsClassSpecific: true")
		}
		if canBeRare {
			b.WriteString(", CanBeRare: true")
		}
		if canBeMagic {
			b.WriteString(", CanBeMagic: true")
		}
		b.WriteString("},\n")
	}

	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(outputDir, "item_types_gen.go"), []byte(b.String()), 0644)
}

// genMonsters generates monsters_gen.go from monstats.txt.
func genMonsters(inputDir, outputDir string) error {
	rows, err := readTSV(filepath.Join(inputDir, "monstats.txt"))
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by plugins/d2r/tools/datagen. DO NOT EDIT.\n\n")
	b.WriteString("package data\n\n")
	b.WriteString("// Monsters contains monster data relevant for drop calculations.\n")
	b.WriteString("var Monsters = []MonsterEntry{\n")

	// Override display names for monsters whose game-data NameStr is
	// ambiguous or misleading in a drop calculator context.
	monsterNameOverrides := map[string]string{
		"diabloclone": "Uber Diablo",
	}

	for _, row := range rows {
		id := row["Id"]
		if id == "" {
			continue
		}
		if row["enabled"] != "1" || row["killable"] != "1" {
			continue
		}

		// Need at least one TC assignment.
		tc := coalesce(row, "TreasureClass1", "TreasureClass")
		tcN := coalesce(row, "TreasureClass1(N)", "TreasureClass(N)")
		if tc == "" && tcN == "" {
			continue
		}

		name := row["NameStr"]
		if override, ok := monsterNameOverrides[id]; ok {
			name = override
		}
		isBoss := row["boss"] == "1"
		levelN := atoi(row["Level"])
		levelNM := atoi(row["Level(N)"])
		levelH := atoi(row["Level(H)"])

		tcChamp := coalesce(row, "TreasureClass2", "TreasureClassChamp")
		tcUnique := coalesce(row, "TreasureClass3", "TreasureClassUnique")
		tcQuest := coalesce(row, "TreasureClass4", "TreasureClassQuest")
		tcChampN := coalesce(row, "TreasureClass2(N)", "TreasureClassChamp(N)")
		tcUniqueN := coalesce(row, "TreasureClass3(N)", "TreasureClassUnique(N)")
		tcQuestN := coalesce(row, "TreasureClass4(N)", "TreasureClassQuest(N)")
		tcH := coalesce(row, "TreasureClass1(H)", "TreasureClass(H)")
		tcChampH := coalesce(row, "TreasureClass2(H)", "TreasureClassChamp(H)")
		tcUniqueH := coalesce(row, "TreasureClass3(H)", "TreasureClassUnique(H)")
		tcQuestH := coalesce(row, "TreasureClass4(H)", "TreasureClassQuest(H)")

		b.WriteString("\t{")
		fmt.Fprintf(&b, "ID: %s, Name: %s", goStr(id), goStr(name))
		if isBoss {
			b.WriteString(", IsBoss: true")
		}
		fmt.Fprintf(&b, ", Levels: [3]int{%d, %d, %d}", levelN, levelNM, levelH)
		fmt.Fprintf(&b, ", TCs: [3][4]string{{%s, %s, %s, %s}, {%s, %s, %s, %s}, {%s, %s, %s, %s}}",
			goStr(tc), goStr(tcChamp), goStr(tcUnique), goStr(tcQuest),
			goStr(tcN), goStr(tcChampN), goStr(tcUniqueN), goStr(tcQuestN),
			goStr(tcH), goStr(tcChampH), goStr(tcUniqueH), goStr(tcQuestH))
		b.WriteString("},\n")
	}

	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(outputDir, "monsters_gen.go"), []byte(b.String()), 0644)
}

// coalesce returns the first non-empty value from the row for the given keys.
func coalesce(row map[string]string, keys ...string) string {
	for _, k := range keys {
		if v := row[k]; v != "" {
			return v
		}
	}
	return ""
}

// genAreas generates areas_gen.go from levels.txt.
func genAreas(inputDir, outputDir string) error {
	rows, err := readTSV(filepath.Join(inputDir, "levels.txt"))
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by plugins/d2r/tools/datagen. DO NOT EDIT.\n\n")
	b.WriteString("package data\n\n")
	b.WriteString("// Areas contains area data from levels.txt.\n")
	b.WriteString("var Areas = []Area{\n")

	for _, row := range rows {
		id := row["Name"]
		if id == "" {
			continue
		}
		name := row["*StringName"]
		if name == "" {
			continue
		}
		// MonLvlEx columns (extended monster levels used for drop calc).
		lvlN := atoi(coalesce(row, "MonLvl1Ex", "MonLvlEx"))
		lvlNM := atoi(coalesce(row, "MonLvl2Ex", "MonLvlEx(N)"))
		lvlH := atoi(coalesce(row, "MonLvl3Ex", "MonLvlEx(H)"))
		if lvlN == 0 && lvlNM == 0 && lvlH == 0 {
			continue
		}

		// Collect monster IDs per difficulty (mon1-25, nmon1-25, umon1-25).
		// "mon" = normal, "nmon" = nightmare, "umon" = hell (confusingly named).
		// Actually: mon = all difficulties regular, nmon = nightmare additions,
		// umon = unique/champion. For drop calc, we use mon (regular spawns).
		monsN := collectMonsters(row, "mon", 25)
		monsNM := collectMonsters(row, "nmon", 25)
		if len(monsNM) == 0 {
			monsNM = monsN // NM falls back to normal monster list
		}

		b.WriteString("\t{")
		fmt.Fprintf(&b, "ID: %s, Name: %s", goStr(id), goStr(name))
		fmt.Fprintf(&b, ", Levels: [3]int{%d, %d, %d}", lvlN, lvlNM, lvlH)

		// Normal monsters
		b.WriteString(", Monsters: [3][]string{")
		writeStringSlice(&b, monsN)
		b.WriteString(", ")
		writeStringSlice(&b, monsNM)
		b.WriteString(", ")
		writeStringSlice(&b, monsN) // Hell uses same base monster list
		b.WriteString("}")

		b.WriteString("},\n")
	}

	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(outputDir, "areas_gen.go"), []byte(b.String()), 0644)
}

func collectMonsters(row map[string]string, prefix string, max int) []string {
	var result []string
	for i := 1; i <= max; i++ {
		key := fmt.Sprintf("%s%d", prefix, i)
		if v := row[key]; v != "" {
			result = append(result, v)
		}
	}
	return result
}

func writeStringSlice(b *strings.Builder, ss []string) {
	if len(ss) == 0 {
		b.WriteString("nil")
		return
	}
	b.WriteString("{")
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%s", goStr(s))
	}
	b.WriteString("}")
}

// genItemAliases generates item_aliases_gen.go from uniqueitems.txt and setitems.txt.
func genItemAliases(inputDir, outputDir string) error {
	var b strings.Builder
	b.WriteString("// Code generated by plugins/d2r/tools/datagen. DO NOT EDIT.\n\n")
	b.WriteString("package data\n\n")
	b.WriteString("// ItemAliases maps unique and set item names to their base item codes.\n")
	b.WriteString("var ItemAliases = []ItemAlias{\n")

	// Unique items: index = display name, code = base item code.
	uniqueRows, err := readTSV(filepath.Join(inputDir, "uniqueitems.txt"))
	if err != nil {
		return fmt.Errorf("reading uniqueitems.txt: %w", err)
	}
	for _, row := range uniqueRows {
		name := row["index"]
		code := row["code"]
		if name == "" || code == "" {
			continue
		}
		if row["spawnable"] != "1" {
			continue
		}
		fmt.Fprintf(&b, "\t{Name: %s, Code: %s},\n", goStr(name), goStr(code))
	}

	// Set items: index = display name, item = base item code.
	setRows, err := readTSV(filepath.Join(inputDir, "setitems.txt"))
	if err != nil {
		return fmt.Errorf("reading setitems.txt: %w", err)
	}
	for _, row := range setRows {
		name := row["index"]
		code := row["item"]
		if name == "" || code == "" {
			continue
		}
		if row["spawnable"] != "1" {
			continue
		}
		fmt.Fprintf(&b, "\t{Name: %s, Code: %s, IsSet: true},\n", goStr(name), goStr(code))
	}

	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(outputDir, "item_aliases_gen.go"), []byte(b.String()), 0644)
}
