// mtga-carddb extracts card data from MTGA's Raw_CardDatabase SQLite file,
// imports it to D1, and regenerates arena_cards_gen.go for the parser.
//
// Usage:
//
//	go run ./plugins/mtga/tools/mtga-carddb --card-db path/to/Raw_CardDatabase.mtga --d1-database-id X --cf-account-id Y --cf-api-token Z
//
// The MTGA client stores this file in MTGA_Data/Downloads/Raw/ after first launch.
// This gives 100% arena_id coverage — every card in Arena, including recent sets
// that Scryfall doesn't map (TMT, TLA, FIN, etc.).
//
// Generated files:
//   - plugins/mtga/parser/data/arena_cards_gen.go (arena_id → name/set/rarity)
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"text/template"
	"time"

	_ "github.com/mattn/go-sqlite3"
)

// ArenaCard holds the minimal card info needed for arena_cards_gen.go codegen.
type ArenaCard struct {
	GrpID  int
	Name   string
	Set    string
	Rarity string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	cardDBPath := flag.String("card-db", "", "Path to Raw_CardDatabase .mtga SQLite file (required)")
	d1DatabaseID := flag.String("d1-database-id", "", "Cloudflare D1 database ID (required)")
	cfAccountID := flag.String("cf-account-id", "", "Cloudflare account ID (required)")
	cfAPIToken := flag.String("cf-api-token", "", "Cloudflare API token (required)")
	flag.Parse()

	if *cardDBPath == "" || *d1DatabaseID == "" || *cfAccountID == "" || *cfAPIToken == "" {
		return fmt.Errorf("all flags required: --card-db, --d1-database-id, --cf-account-id, --cf-api-token")
	}

	_, thisFile, _, _ := runtime.Caller(0)
	pluginDir := filepath.Join(filepath.Dir(thisFile), "..", "..")

	// Extract full card data from the MTGA client database.
	cards, err := extractFullCards(*cardDBPath)
	if err != nil {
		return fmt.Errorf("extracting cards: %w", err)
	}
	fmt.Printf("Extracted %d cards from MTGA client database\n", len(cards))

	// Sort by arena_id for deterministic output.
	sort.Slice(cards, func(i, j int) bool {
		return cards[i].ArenaID < cards[j].ArenaID
	})

	// Import to D1.
	if err := importToD1(*cfAccountID, *d1DatabaseID, *cfAPIToken, cards); err != nil {
		return fmt.Errorf("D1 import: %w", err)
	}
	fmt.Printf("Imported %d cards to D1\n", len(cards))

	// Regenerate arena_cards_gen.go for the parser.
	arenaCards := fullToArenaCards(cards)
	outPath := filepath.Join(pluginDir, "parser", "data", "arena_cards_gen.go")
	if err := generateParserData(outPath, arenaCards); err != nil {
		return fmt.Errorf("generating parser data: %w", err)
	}
	fmt.Printf("Generated %s (%d cards)\n", outPath, len(arenaCards))

	return nil
}

// fullToArenaCards converts FullCard slice to ArenaCard slice for codegen.
func fullToArenaCards(cards []FullCard) []ArenaCard {
	result := make([]ArenaCard, len(cards))
	for i, c := range cards {
		result[i] = ArenaCard{
			GrpID:  c.ArenaID,
			Name:   c.Name,
			Set:    c.Set,
			Rarity: c.Rarity,
		}
	}
	return result
}

var (
	spriteRe = regexp.MustCompile(`<sprite=[^>]+>`)
	nobrRe   = regexp.MustCompile(`</?nobr>`)
)

// stripMarkup removes MTGA UI markup from card names.
// Sprite tags (used for Alchemy indicator) are replaced with "A-".
// <nobr> tags are simply removed (keeping inner text).
func stripMarkup(s string) string {
	s = spriteRe.ReplaceAllString(s, "A-")
	s = nobrRe.ReplaceAllString(s, "")
	return s
}

func mapRarity(r int) string {
	switch r {
	case 0:
		return "token"
	case 1:
		return "common"
	case 2:
		return "uncommon"
	case 3:
		return "rare"
	case 4, 5:
		return "mythic"
	default:
		return "unknown"
	}
}

func generateParserData(path string, cards []ArenaCard) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	return parserTmpl.Execute(f, templateData{
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Cards:     cards,
	})
}

type templateData struct {
	Timestamp string
	Cards     []ArenaCard
}

func goStr(s string) string {
	return fmt.Sprintf("%q", s)
}

var funcMap = template.FuncMap{
	"goStr": goStr,
}

var parserTmpl = template.Must(template.New("parser").Funcs(funcMap).Parse(`// Code generated by plugins/mtga/tools/mtga-carddb. DO NOT EDIT.
// Source: MTGA Raw_CardDatabase (includes Localizations_enUS)
// Card data copyright Wizards of the Coast, LLC.
// Generated: {{ .Timestamp }}

package data

// ArenaCard is the minimal card info needed by the parser for name resolution.
type ArenaCard struct {
	Name   string
	Set    string
	Rarity string
}

// ArenaCards maps MTGA arena_id to card info.
// {{ len .Cards }} cards from MTGA client data.
var ArenaCards = map[int]ArenaCard{
{{- range .Cards }}
	{{ .GrpID }}: {Name: {{ goStr .Name }}, Set: {{ goStr .Set }}, Rarity: {{ goStr .Rarity }}},
{{- end }}
}
`))
