// mtga-carddb generates the parser's arena_cards_gen.go from MTGA's own
// Raw_CardDatabase SQLite file.
//
// Usage: go run ./plugins/mtga/tools/mtga-carddb --card-db path/to/Raw_CardDatabase.mtga
//
// The MTGA client stores this file in MTGA_Data/Downloads/Raw/ after first launch.
// This gives 100% arena_id coverage — every card in Arena, including recent sets
// that Scryfall doesn't map (TMT, TLA, FIN, etc.).
//
// Generated files:
//   - plugins/mtga/parser/data/arena_cards_gen.go (arena_id → name/set/rarity)
package main

import (
	"database/sql"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
	"text/template"
	"time"

	_ "github.com/mattn/go-sqlite3"
)

// ArenaCard holds card data extracted from the MTGA database.
type ArenaCard struct {
	GrpID  int
	Name   string
	Set    string
	Rarity string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	cardDBPath := flag.String("card-db", "", "Path to Raw_CardDatabase .mtga SQLite file (required)")
	flag.Parse()

	if *cardDBPath == "" {
		return fmt.Errorf("--card-db is required")
	}

	_, thisFile, _, _ := runtime.Caller(0)
	pluginDir := filepath.Join(filepath.Dir(thisFile), "..", "..")

	cards, err := extractCards(*cardDBPath)
	if err != nil {
		return fmt.Errorf("extracting cards: %w", err)
	}

	sort.Slice(cards, func(i, j int) bool {
		return cards[i].GrpID < cards[j].GrpID
	})

	outPath := filepath.Join(pluginDir, "parser", "data", "arena_cards_gen.go")
	if err := generateParserData(outPath, cards); err != nil {
		return fmt.Errorf("generating parser data: %w", err)
	}
	fmt.Printf("Generated %s (%d cards)\n", outPath, len(cards))
	return nil
}

func extractCards(cardDBPath string) ([]ArenaCard, error) {
	db, err := sql.Open("sqlite3", cardDBPath+"?mode=ro")
	if err != nil {
		return nil, fmt.Errorf("opening card database: %w", err)
	}
	defer db.Close()

	// The card database has Localizations_enUS built in — no need for a
	// separate localization file. Join Cards → Localizations_enUS via TitleId.
	// Formatted=1 gives us the display-ready name with any markup.
	rows, err := db.Query(`
		SELECT c.GrpId, l.Loc, c.ExpansionCode, c.Rarity
		FROM Cards c
		JOIN Localizations_enUS l ON l.LocId = c.TitleId AND l.Formatted = 1
		WHERE l.Loc IS NOT NULL AND l.Loc != ''
	`)
	if err != nil {
		return nil, fmt.Errorf("querying cards: %w", err)
	}
	defer rows.Close()

	var cards []ArenaCard
	for rows.Next() {
		var grpID, rarity int
		var name, set string
		if err := rows.Scan(&grpID, &name, &set, &rarity); err != nil {
			return nil, fmt.Errorf("scanning row: %w", err)
		}

		name = stripMarkup(name)
		if name == "" {
			continue
		}

		cards = append(cards, ArenaCard{
			GrpID:  grpID,
			Name:   name,
			Set:    strings.ToLower(set),
			Rarity: mapRarity(rarity),
		})
	}
	return cards, rows.Err()
}

var (
	spriteRe = regexp.MustCompile(`<sprite=[^>]+>`)
	nobrRe   = regexp.MustCompile(`</?nobr>`)
)

// stripMarkup removes MTGA UI markup from card names.
// Sprite tags (used for Alchemy indicator) are replaced with "A-".
// <nobr> tags are simply removed (keeping inner text).
func stripMarkup(s string) string {
	s = spriteRe.ReplaceAllString(s, "A-")
	s = nobrRe.ReplaceAllString(s, "")
	return s
}

func mapRarity(r int) string {
	switch r {
	case 0:
		return "token"
	case 1:
		return "common"
	case 2:
		return "uncommon"
	case 3:
		return "rare"
	case 4, 5:
		return "mythic"
	default:
		return "unknown"
	}
}

func generateParserData(path string, cards []ArenaCard) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	return parserTmpl.Execute(f, templateData{
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Cards:     cards,
	})
}

type templateData struct {
	Timestamp string
	Cards     []ArenaCard
}

func goStr(s string) string {
	return fmt.Sprintf("%q", s)
}

var funcMap = template.FuncMap{
	"goStr": goStr,
}

var parserTmpl = template.Must(template.New("parser").Funcs(funcMap).Parse(`// Code generated by plugins/mtga/tools/mtga-carddb. DO NOT EDIT.
// Source: MTGA Raw_CardDatabase (includes Localizations_enUS)
// Card data copyright Wizards of the Coast, LLC.
// Generated: {{ .Timestamp }}

package data

// ArenaCard is the minimal card info needed by the parser for name resolution.
type ArenaCard struct {
	Name   string
	Set    string
	Rarity string
}

// ArenaCards maps MTGA arena_id to card info.
// {{ len .Cards }} cards from MTGA client data.
var ArenaCards = map[int]ArenaCard{
{{- range .Cards }}
	{{ .GrpID }}: {Name: {{ goStr .Name }}, Set: {{ goStr .Set }}, Rarity: {{ goStr .Rarity }}},
{{- end }}
}
`))
