package main

import (
	"bytes"
	"fmt"
	"go/format"
	"regexp"
	"strings"

	"github.com/joshsymonds/savecraft.gg/plugins/songsofsyx/reference/data"
	"github.com/joshsymonds/savecraft.gg/plugins/songsofsyx/tools/datagen/sosdata"
)

// crossLinkRe matches the in-guide cross-link markup <a KEY label> and captures
// the referenced LINK_KEY.
var crossLinkRe = regexp.MustCompile(`<a\s+(\w+)`)

// decodeGuideArticles reads a parsed GUIDE.txt/ROOMS.txt document (top-level
// WIKIS list) into guide articles, in source order. Articles without a LINK_KEY
// (ROOMS.txt) get a slug synthesized from their title.
func decodeGuideArticles(root *sosdata.Value) ([]data.GuideArticle, error) {
	wikis, ok := root.Get("WIKIS")
	if !ok || wikis.Kind != sosdata.KindList {
		return nil, fmt.Errorf("decodeGuideArticles: expected a WIKIS list at top level")
	}

	articles := make([]data.GuideArticle, 0, wikis.Len())
	for i := range wikis.Len() {
		entry := wikis.At(i)
		if entry == nil || entry.Kind != sosdata.KindObject {
			return nil, fmt.Errorf("decodeGuideArticles: WIKIS[%d] is not an object", i)
		}

		title := scalar(entry, "NAME")
		if title == "" {
			return nil, fmt.Errorf("decodeGuideArticles: WIKIS[%d] has no NAME", i)
		}
		text := scalar(entry, "TEXT")

		key := scalar(entry, "LINK_KEY")
		if key == "" {
			key = slugify(title)
		}

		articles = append(articles, data.GuideArticle{
			LinkKey:    key,
			Title:      title,
			Category:   scalar(entry, "CATEGORY"),
			Synopsis:   firstLine(text),
			Text:       text,
			CrossLinks: extractCrossLinks(text),
		})
	}
	return articles, nil
}

// scalar returns the string value of an object member, or "" if absent or not a
// scalar.
func scalar(obj *sosdata.Value, key string) string {
	v, ok := obj.Get(key)
	if !ok || v.Kind != sosdata.KindScalar {
		return ""
	}
	return v.Str
}

// slugify turns a title into a stable UPPER_SNAKE key: alphanumeric runs joined
// by underscores.
func slugify(name string) string {
	var sb strings.Builder
	prevUnderscore := true // suppress leading underscore
	for _, ch := range name {
		switch {
		case ch >= 'a' && ch <= 'z':
			sb.WriteRune(ch - 'a' + 'A')
			prevUnderscore = false
		case (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9'):
			sb.WriteRune(ch)
			prevUnderscore = false
		default:
			if !prevUnderscore {
				sb.WriteByte('_')
				prevUnderscore = true
			}
		}
	}
	return strings.TrimRight(sb.String(), "_")
}

// firstLine returns the first non-empty, trimmed line of the body — the TOC
// synopsis.
func firstLine(text string) string {
	for line := range strings.SplitSeq(text, "\n") {
		if trimmed := strings.TrimSpace(line); trimmed != "" {
			return trimmed
		}
	}
	return ""
}

// extractCrossLinks returns the LINK_KEYs referenced by <a KEY ...> markup,
// de-duplicated in first-appearance order.
func extractCrossLinks(text string) []string {
	matches := crossLinkRe.FindAllStringSubmatch(text, -1)
	if matches == nil {
		return nil
	}
	seen := make(map[string]bool, len(matches))
	var keys []string
	for _, m := range matches {
		if k := m[1]; !seen[k] {
			seen[k] = true
			keys = append(keys, k)
		}
	}
	return keys
}

// generateGuideSource renders the guide articles into gofmt'd Go source for
// reference/data/guide_gen.go.
func generateGuideSource(articles []data.GuideArticle) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by plugins/songsofsyx/tools/datagen. DO NOT EDIT.\n")
	buf.WriteString("// Source: data/assets/text/wiki/GUIDE.txt + ROOMS.txt (game-shipped).\n\n")
	buf.WriteString("package data\n\n")
	buf.WriteString("// GuideArticles is the in-game mechanics guide, in source order.\n")
	buf.WriteString("var GuideArticles = []GuideArticle{\n")
	for _, art := range articles {
		buf.WriteString("\t{\n")
		fmt.Fprintf(&buf, "\t\tLinkKey:  %q,\n", art.LinkKey)
		fmt.Fprintf(&buf, "\t\tTitle:    %q,\n", art.Title)
		fmt.Fprintf(&buf, "\t\tCategory: %q,\n", art.Category)
		fmt.Fprintf(&buf, "\t\tSynopsis: %q,\n", art.Synopsis)
		fmt.Fprintf(&buf, "\t\tText:     %q,\n", art.Text)
		if len(art.CrossLinks) > 0 {
			buf.WriteString("\t\tCrossLinks: []string{")
			for i, k := range art.CrossLinks {
				if i > 0 {
					buf.WriteString(", ")
				}
				fmt.Fprintf(&buf, "%q", k)
			}
			buf.WriteString("},\n")
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt guide source: %w", err)
	}
	return src, nil
}
