package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/joshsymonds/savecraft.gg/plugins/songsofsyx/reference/data"
	"github.com/joshsymonds/savecraft.gg/plugins/songsofsyx/tools/datagen/sosdata"
)

// decodeRace joins a race's top-level stats with its text name/description
// (textVal may be nil) into a data.Race.
func decodeRace(initVal, textVal *sosdata.Value, id string) data.Race {
	race := data.Race{
		ID:       id,
		Playable: scalar(initVal, "PLAYABLE") == "true",
	}

	if props, ok := initVal.Get("PROPERTIES"); ok {
		race.SlavePrice = intScalar(props, "SLAVE_PRICE")
		race.BabyDays = intScalar(props, "BABY_DAYS")
		race.ChildDays = intScalar(props, "CHILD_DAYS")
	}
	if pref, ok := initVal.Get("PREFERRED"); ok {
		race.PreferredFoods = stringList(pref, "FOOD")
	}
	if textVal != nil {
		race.Name = scalar(textVal, "NAME")
		// Race DESC blocks carry a redundant inner closing quote and a trailing
		// newline before the real terminator (a quirk of the shipped data);
		// trim trailing whitespace and quotes.
		race.Description = strings.Trim(scalar(textVal, "DESC"), " \r\n\t\"")
	}
	return race
}

// intScalar reads a scalar object member as an int, defaulting to 0.
func intScalar(obj *sosdata.Value, key string) int {
	n, err := strconv.Atoi(scalar(obj, key))
	if err != nil {
		return 0
	}
	return n
}

// stringList reads a list-valued member into a slice of its scalar elements,
// dropping the "*" wildcard.
func stringList(obj *sosdata.Value, key string) []string {
	list, ok := obj.Get(key)
	if !ok || list.Kind != sosdata.KindList {
		return nil
	}
	var out []string
	for i := range list.Len() {
		if s := list.At(i).Str; s != "" && s != "*" {
			out = append(out, s)
		}
	}
	return out
}

// generateRacesSource renders races into gofmt'd Go source for
// reference/data/races_gen.go, keyed by ID in sorted order.
func generateRacesSource(races []data.Race) ([]byte, error) {
	sorted := make([]data.Race, len(races))
	copy(sorted, races)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by plugins/songsofsyx/tools/datagen. DO NOT EDIT.\n")
	buf.WriteString("// Source: data/assets/init/race/*.txt + text/race/*.txt (game-shipped).\n\n")
	buf.WriteString("package data\n\n")
	buf.WriteString("// Races maps a species ID to its stats and description.\n")
	buf.WriteString("var Races = map[string]Race{\n")
	for _, race := range sorted {
		fmt.Fprintf(&buf, "\t%q: {\n", race.ID)
		fmt.Fprintf(&buf, "\t\tID:   %q,\n", race.ID)
		fmt.Fprintf(&buf, "\t\tName: %q,\n", race.Name)
		if race.Description != "" {
			fmt.Fprintf(&buf, "\t\tDescription: %q,\n", race.Description)
		}
		fmt.Fprintf(&buf, "\t\tPlayable: %t,\n", race.Playable)
		if race.SlavePrice != 0 {
			fmt.Fprintf(&buf, "\t\tSlavePrice: %d,\n", race.SlavePrice)
		}
		if race.BabyDays != 0 {
			fmt.Fprintf(&buf, "\t\tBabyDays: %d,\n", race.BabyDays)
		}
		if race.ChildDays != 0 {
			fmt.Fprintf(&buf, "\t\tChildDays: %d,\n", race.ChildDays)
		}
		if len(race.PreferredFoods) > 0 {
			buf.WriteString("\t\tPreferredFoods: []string{")
			for i, food := range race.PreferredFoods {
				if i > 0 {
					buf.WriteString(", ")
				}
				fmt.Fprintf(&buf, "%q", food)
			}
			buf.WriteString("},\n")
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt races source: %w", err)
	}
	return src, nil
}
