package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"

	"github.com/joshsymonds/savecraft.gg/plugins/songsofsyx/reference/data"
	"github.com/joshsymonds/savecraft.gg/plugins/songsofsyx/tools/datagen/sosdata"
)

// decodeResource joins a resource's top-level stats with its text name/desc
// (textVal may be nil) and its roles into a data.Resource.
func decodeResource(initVal, textVal *sosdata.Value, id string, roles []string) data.Resource {
	res := data.Resource{
		ID:          id,
		DegradeRate: floatScalar(initVal, "DEGRADE_RATE"),
	}
	if len(roles) > 0 {
		sorted := append([]string(nil), roles...)
		sort.Strings(sorted)
		res.Roles = sorted
	}
	if textVal != nil {
		res.Name = scalar(textVal, "NAME")
		res.Description = scalar(textVal, "DESC")
	}
	return res
}

// floatScalar reads a scalar object member as a float, defaulting to 0.
func floatScalar(obj *sosdata.Value, key string) float64 {
	s := scalar(obj, key)
	if s == "" {
		return 0
	}
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0
	}
	return f
}

// generateResourcesSource renders resources into gofmt'd Go source for
// reference/data/resources_gen.go, keyed by ID in sorted order.
func generateResourcesSource(resources []data.Resource) ([]byte, error) {
	sorted := make([]data.Resource, len(resources))
	copy(sorted, resources)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by plugins/songsofsyx/tools/datagen. DO NOT EDIT.\n")
	buf.WriteString("// Source: data/assets/init/resource/**.txt + text/resource/*.txt (game-shipped).\n\n")
	buf.WriteString("package data\n\n")
	buf.WriteString("// Resources maps a resource ID to its stats, roles, and description.\n")
	buf.WriteString("var Resources = map[string]Resource{\n")
	for _, res := range sorted {
		fmt.Fprintf(&buf, "\t%q: {\n", res.ID)
		fmt.Fprintf(&buf, "\t\tID:   %q,\n", res.ID)
		fmt.Fprintf(&buf, "\t\tName: %q,\n", res.Name)
		if res.Description != "" {
			fmt.Fprintf(&buf, "\t\tDescription: %q,\n", res.Description)
		}
		if len(res.Roles) > 0 {
			buf.WriteString("\t\tRoles: []string{")
			for i, role := range res.Roles {
				if i > 0 {
					buf.WriteString(", ")
				}
				fmt.Fprintf(&buf, "%q", role)
			}
			buf.WriteString("},\n")
		}
		if res.DegradeRate != 0 {
			fmt.Fprintf(&buf, "\t\tDegradeRate: %s,\n", strconv.FormatFloat(res.DegradeRate, 'g', -1, 64))
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt resources source: %w", err)
	}
	return src, nil
}
