package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"

	"github.com/joshsymonds/savecraft.gg/plugins/songsofsyx/reference/data"
	"github.com/joshsymonds/savecraft.gg/plugins/songsofsyx/tools/datagen/sosdata"
)

// decodeRoom joins a room's init stats with its text name/description (textVal
// may be nil) into a data.Room. Industry and build cost reflect the base tier.
func decodeRoom(initVal, textVal *sosdata.Value, id string) data.Room {
	room := data.Room{
		ID:        id,
		BuildCost: buildCost(initVal),
		UsesTool:  workUsesTool(initVal),
		Growable:  scalar(initVal, "GROWABLE"),
	}
	if _, ok := initVal.Get("SERVICE"); ok {
		room.IsService = true
	}

	if ind := industryBlock(initVal); ind != nil {
		room.Produces = rateMap(ind, "OUT")
		room.Consumes = rateMap(ind, "IN")
	}

	if textVal != nil {
		if info, ok := textVal.Get("INFO"); ok {
			room.Name = scalar(info, "NAME")
			room.Description = scalar(info, "DESC")
			if wiki, okWiki := info.Get("WIKI"); okWiki {
				room.Category = scalar(wiki, "CATEGORY")
			}
		}
	}
	return room
}

// buildCost zips RESOURCES with ITEMS[0].COSTS (base tier), dropping zero costs.
func buildCost(initVal *sosdata.Value) map[string]int {
	resources, ok := initVal.Get("RESOURCES")
	if !ok || resources.Kind != sosdata.KindList {
		return nil
	}
	items, ok := initVal.Get("ITEMS")
	if !ok || items.Len() == 0 {
		return nil
	}
	costs, ok := items.At(0).Get("COSTS")
	if !ok || costs.Kind != sosdata.KindList {
		return nil
	}

	cost := make(map[string]int)
	for i := range resources.Len() {
		if i >= costs.Len() {
			break
		}
		qty, err := strconv.Atoi(costs.At(i).Str)
		if err != nil || qty == 0 {
			continue
		}
		cost[resources.At(i).Str] = qty
	}
	if len(cost) == 0 {
		return nil
	}
	return cost
}

// industryBlock returns the base-tier INDUSTRY object. Farms/canteens carry it
// at the top level; workshops/refiners carry it as INDUSTRIES[0].INDUSTRY.
func industryBlock(initVal *sosdata.Value) *sosdata.Value {
	if ind, ok := initVal.Get("INDUSTRY"); ok {
		return ind
	}
	list, hasList := initVal.Get("INDUSTRIES")
	if !hasList || list.Len() == 0 {
		return nil
	}
	if ind, ok := list.At(0).Get("INDUSTRY"); ok {
		return ind
	}
	return nil
}

// rateMap reads INDUSTRY.<dir> (IN or OUT) into a resource→rate map. Each entry
// is either a scalar rate or an object whose PLAYER field holds the rate.
func rateMap(industry *sosdata.Value, dir string) map[string]float64 {
	block, ok := industry.Get(dir)
	if !ok || block.Kind != sosdata.KindObject {
		return nil
	}
	rates := make(map[string]float64)
	for _, member := range block.Members {
		if rate, okRate := playerRate(member.Value); okRate {
			rates[member.Key] = rate
		}
	}
	if len(rates) == 0 {
		return nil
	}
	return rates
}

// playerRate extracts a production rate: a bare scalar, or the PLAYER field of
// an object.
func playerRate(val *sosdata.Value) (float64, bool) {
	switch val.Kind {
	case sosdata.KindScalar:
		f, err := strconv.ParseFloat(val.Str, 64)
		return f, err == nil
	case sosdata.KindObject:
		if p, ok := val.Get("PLAYER"); ok && p.Kind == sosdata.KindScalar {
			f, err := strconv.ParseFloat(p.Str, 64)
			return f, err == nil
		}
	case sosdata.KindList:
		// Lists carry no production rate.
	}
	return 0, false
}

// workUsesTool reads WORK.USES_TOOL.
func workUsesTool(initVal *sosdata.Value) bool {
	if work, ok := initVal.Get("WORK"); ok {
		return scalar(work, "USES_TOOL") == "true"
	}
	return false
}

// generateRoomsSource renders rooms into gofmt'd Go source for
// reference/data/rooms_gen.go, keyed by ID in sorted order.
func generateRoomsSource(rooms []data.Room) ([]byte, error) {
	sorted := make([]data.Room, len(rooms))
	copy(sorted, rooms)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by plugins/songsofsyx/tools/datagen. DO NOT EDIT.\n")
	buf.WriteString("// Source: data/assets/init/room/*.txt + text/room/*.txt (game-shipped).\n\n")
	buf.WriteString("package data\n\n")
	buf.WriteString("// Rooms maps a room/building ID to its base-tier stats and description.\n")
	buf.WriteString("var Rooms = map[string]Room{\n")
	for _, room := range sorted {
		fmt.Fprintf(&buf, "\t%q: {\n", room.ID)
		fmt.Fprintf(&buf, "\t\tID:   %q,\n", room.ID)
		fmt.Fprintf(&buf, "\t\tName: %q,\n", room.Name)
		fmt.Fprintf(&buf, "\t\tDescription: %q,\n", room.Description)
		fmt.Fprintf(&buf, "\t\tCategory:    %q,\n", room.Category)
		writeIntMap(&buf, "BuildCost", room.BuildCost)
		writeFloatMap(&buf, "Produces", room.Produces)
		writeFloatMap(&buf, "Consumes", room.Consumes)
		if room.UsesTool {
			buf.WriteString("\t\tUsesTool: true,\n")
		}
		if room.IsService {
			buf.WriteString("\t\tIsService: true,\n")
		}
		if room.Growable != "" {
			fmt.Fprintf(&buf, "\t\tGrowable: %q,\n", room.Growable)
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt rooms source: %w", err)
	}
	return src, nil
}

func writeIntMap(buf *bytes.Buffer, field string, vals map[string]int) {
	if len(vals) == 0 {
		return
	}
	fmt.Fprintf(buf, "\t\t%s: map[string]int{", field)
	for _, k := range sortedKeysInt(vals) {
		fmt.Fprintf(buf, "%q: %d, ", k, vals[k])
	}
	buf.WriteString("},\n")
}

func writeFloatMap(buf *bytes.Buffer, field string, vals map[string]float64) {
	if len(vals) == 0 {
		return
	}
	fmt.Fprintf(buf, "\t\t%s: map[string]float64{", field)
	for _, k := range sortedKeysFloat(vals) {
		fmt.Fprintf(buf, "%q: %s, ", k, strconv.FormatFloat(vals[k], 'g', -1, 64))
	}
	buf.WriteString("},\n")
}

func sortedKeysInt(vals map[string]int) []string {
	keys := make([]string, 0, len(vals))
	for k := range vals {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedKeysFloat(vals map[string]float64) []string {
	keys := make([]string, 0, len(vals))
	for k := range vals {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
