package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"

	"github.com/joshsymonds/savecraft.gg/plugins/songsofsyx/reference/data"
	"github.com/joshsymonds/savecraft.gg/plugins/songsofsyx/tools/datagen/sosdata"
)

// decodeTech reads one TECHS node (and its optional text node) into a data.Tech.
func decodeTech(node, textNode *sosdata.Value, id, category string) data.Tech {
	tech := data.Tech{
		ID:       id,
		Category: category,
		Costs:    floatMap(node, "COSTS"),
	}

	if req, ok := node.Get("REQUIRES"); ok {
		if greater, okG := req.Get("GREATER"); okG {
			tech.RequiresPopulation = intScalar(greater, "POPULATION")
		}
	}
	tech.RequiresTech = intMap(node, "REQUIRES_TECH_LEVEL")
	tech.Unlocks = stringList(node, "UNLOCKS_FACTION")

	if textNode != nil {
		tech.Name = scalar(textNode, "NAME")
		tech.Description = scalar(textNode, "DESC")
	}
	return tech
}

// floatMap reads an object member whose value is an object of name→number.
func floatMap(obj *sosdata.Value, key string) map[string]float64 {
	block, ok := obj.Get(key)
	if !ok || block.Kind != sosdata.KindObject {
		return nil
	}
	out := make(map[string]float64)
	for _, m := range block.Members {
		if f, err := strconv.ParseFloat(m.Value.Str, 64); err == nil {
			out[m.Key] = f
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// intMap reads an object member whose value is an object of name→integer.
func intMap(obj *sosdata.Value, key string) map[string]int {
	block, ok := obj.Get(key)
	if !ok || block.Kind != sosdata.KindObject {
		return nil
	}
	out := make(map[string]int)
	for _, m := range block.Members {
		if n, err := strconv.Atoi(m.Value.Str); err == nil {
			out[m.Key] = n
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// generateTechSource renders techs into gofmt'd Go source for
// reference/data/techs_gen.go, keyed by ID in sorted order.
func generateTechSource(techs []data.Tech) ([]byte, error) {
	sorted := make([]data.Tech, len(techs))
	copy(sorted, techs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by plugins/songsofsyx/tools/datagen. DO NOT EDIT.\n")
	buf.WriteString("// Source: data/assets/init/tech/*.txt + text/tech/*.txt (game-shipped).\n\n")
	buf.WriteString("package data\n\n")
	buf.WriteString("// Techs maps a knowledge-tree node ID to its costs, requirements, and unlocks.\n")
	buf.WriteString("var Techs = map[string]Tech{\n")
	for _, tech := range sorted {
		fmt.Fprintf(&buf, "\t%q: {\n", tech.ID)
		fmt.Fprintf(&buf, "\t\tID:   %q,\n", tech.ID)
		fmt.Fprintf(&buf, "\t\tName: %q,\n", tech.Name)
		if tech.Description != "" {
			fmt.Fprintf(&buf, "\t\tDescription: %q,\n", tech.Description)
		}
		fmt.Fprintf(&buf, "\t\tCategory: %q,\n", tech.Category)
		writeFloatMap(&buf, "Costs", tech.Costs)
		if tech.RequiresPopulation != 0 {
			fmt.Fprintf(&buf, "\t\tRequiresPopulation: %d,\n", tech.RequiresPopulation)
		}
		if len(tech.RequiresTech) > 0 {
			fmt.Fprintf(&buf, "\t\tRequiresTech: map[string]int{")
			for _, k := range sortedKeysInt(tech.RequiresTech) {
				fmt.Fprintf(&buf, "%q: %d, ", k, tech.RequiresTech[k])
			}
			buf.WriteString("},\n")
		}
		if len(tech.Unlocks) > 0 {
			buf.WriteString("\t\tUnlocks: []string{")
			for i, u := range tech.Unlocks {
				if i > 0 {
					buf.WriteString(", ")
				}
				fmt.Fprintf(&buf, "%q", u)
			}
			buf.WriteString("},\n")
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt tech source: %w", err)
	}
	return src, nil
}
