// Code generated by plugins/satisfactory/tools/datagen. DO NOT EDIT.
// Source: CommunityResources/Docs/en-US.json from the game install.

package data

var Buildings = map[string]Building{
	"Build_AssemblerMk1_C": {ClassName: "Build_AssemblerMk1_C", DisplayName: "Assembler", Kind: "manufacturer", PowerMW: 15, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_Blender_C": {ClassName: "Build_Blender_C", DisplayName: "Blender", Kind: "manufacturer", PowerMW: 75, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_ConstructorMk1_C": {ClassName: "Build_ConstructorMk1_C", DisplayName: "Constructor", Kind: "manufacturer", PowerMW: 4, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_Converter_C": {ClassName: "Build_Converter_C", DisplayName: "Converter", Kind: "manufacturerVariablePower", PowerMW: 400, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_FoundryMk1_C": {ClassName: "Build_FoundryMk1_C", DisplayName: "Foundry", Kind: "manufacturer", PowerMW: 16, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_FrackingExtractor_C": {ClassName: "Build_FrackingExtractor_C", DisplayName: "Resource Well Extractor", Kind: "extractor", PowerMW: 0, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 1000, ExtractCycleSec: 1},
	"Build_GeneratorBiomass_Automated_C": {ClassName: "Build_GeneratorBiomass_Automated_C", DisplayName: "Biomass Burner", Kind: "generator", PowerMW: 0, PowerProductionMW: 30, FuelClasses: []string{"Desc_Leaves_C", "Desc_Wood_C", "Desc_Mycelia_C", "Desc_GenericBiomass_C", "Desc_Biofuel_C", "Desc_PackagedBiofuel_C"}, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_GeneratorCoal_C": {ClassName: "Build_GeneratorCoal_C", DisplayName: "Coal-Powered Generator", Kind: "generator", PowerMW: 0, PowerProductionMW: 75, FuelClasses: []string{"Desc_Coal_C", "Desc_CompactedCoal_C", "Desc_PetroleumCoke_C"}, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_GeneratorFuel_C": {ClassName: "Build_GeneratorFuel_C", DisplayName: "Fuel-Powered Generator", Kind: "generator", PowerMW: 0, PowerProductionMW: 250, FuelClasses: []string{"Desc_LiquidFuel_C", "Desc_LiquidTurboFuel_C", "Desc_LiquidBiofuel_C", "Desc_RocketFuel_C", "Desc_IonizedFuel_C"}, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_GeneratorGeoThermal_C": {ClassName: "Build_GeneratorGeoThermal_C", DisplayName: "Geothermal Generator", Kind: "generator", PowerMW: 0, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_GeneratorNuclear_C": {ClassName: "Build_GeneratorNuclear_C", DisplayName: "Nuclear Power Plant", Kind: "generator", PowerMW: 0, PowerProductionMW: 2500, FuelClasses: []string{"Desc_NuclearFuelRod_C", "Desc_PlutoniumFuelRod_C", "Desc_FicsoniumFuelRod_C"}, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_HadronCollider_C": {ClassName: "Build_HadronCollider_C", DisplayName: "Particle Accelerator", Kind: "manufacturerVariablePower", PowerMW: 1500, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_ManufacturerMk1_C": {ClassName: "Build_ManufacturerMk1_C", DisplayName: "Manufacturer", Kind: "manufacturer", PowerMW: 55, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_MinerMk1_C": {ClassName: "Build_MinerMk1_C", DisplayName: "Miner Mk.1", Kind: "extractor", PowerMW: 5, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 1, ExtractCycleSec: 1},
	"Build_MinerMk2_C": {ClassName: "Build_MinerMk2_C", DisplayName: "Miner Mk.2", Kind: "extractor", PowerMW: 15, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 1, ExtractCycleSec: 0.5},
	"Build_MinerMk3_C": {ClassName: "Build_MinerMk3_C", DisplayName: "Miner Mk.3", Kind: "extractor", PowerMW: 45, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 1, ExtractCycleSec: 0.25},
	"Build_OilPump_C": {ClassName: "Build_OilPump_C", DisplayName: "Oil Extractor", Kind: "extractor", PowerMW: 40, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 2000, ExtractCycleSec: 1},
	"Build_OilRefinery_C": {ClassName: "Build_OilRefinery_C", DisplayName: "Refinery", Kind: "manufacturer", PowerMW: 30, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_Packager_C": {ClassName: "Build_Packager_C", DisplayName: "Packager", Kind: "manufacturer", PowerMW: 10, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_QuantumEncoder_C": {ClassName: "Build_QuantumEncoder_C", DisplayName: "Quantum Encoder", Kind: "manufacturerVariablePower", PowerMW: 2000, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_SmelterMk1_C": {ClassName: "Build_SmelterMk1_C", DisplayName: "Smelter", Kind: "manufacturer", PowerMW: 4, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 0, ExtractCycleSec: 0},
	"Build_WaterPump_C": {ClassName: "Build_WaterPump_C", DisplayName: "Water Extractor", Kind: "extractor", PowerMW: 20, PowerProductionMW: 0, FuelClasses: nil, ItemsPerCycle: 2000, ExtractCycleSec: 1},
}
