use jomini::TextTape;
use std::collections::HashMap;
use std::path::Path;

use crate::variables;

pub struct Building {
    pub key: String,
    pub category: String,
    pub base_buildtime: i32,
    pub is_capital: bool,
}

/// Parse all building files in the given directory.
pub fn parse_buildings(dir: &Path, vars: &HashMap<String, String>) -> Vec<Building> {
    let mut buildings = Vec::new();
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return buildings,
    };

    let mut files: Vec<_> = entries.flatten().map(|e| e.path()).collect();
    files.sort();

    for path in files {
        if path.extension().and_then(|e| e.to_str()) != Some("txt") {
            continue;
        }
        if let Ok(data) = std::fs::read(&path) {
            parse_building_file(&data, vars, &mut buildings);
        }
    }

    buildings.sort_by(|a, b| a.key.cmp(&b.key));
    buildings
}

fn parse_building_file(data: &[u8], vars: &HashMap<String, String>, buildings: &mut Vec<Building>) {
    let tape = match TextTape::from_slice(data) {
        Ok(t) => t,
        Err(_) => return,
    };
    let reader = tape.windows1252_reader();

    for (key, _op, value) in reader.fields() {
        let key_str = key.read_str();
        // Skip variable definitions
        if key_str.starts_with('@') {
            continue;
        }

        let obj = match value.read_object() {
            Ok(o) => o,
            Err(_) => continue,
        };

        let mut building = Building {
            key: key_str.into_owned(),
            category: String::new(),
            base_buildtime: 0,
            is_capital: false,
        };

        for (field_key, _fop, field_val) in obj.fields() {
            let fk = field_key.read_str();
            match fk.as_ref() {
                "category" => {
                    if let Ok(v) = field_val.read_str() {
                        building.category = v.into_owned();
                    }
                }
                "base_buildtime" => {
                    if let Ok(v) = field_val.read_str() {
                        building.base_buildtime = variables::resolve_i32(&v, vars);
                    }
                }
                "capital" => {
                    if let Ok(v) = field_val.read_str() {
                        building.is_capital = v.as_ref() == "yes";
                    }
                }
                _ => {}
            }
        }

        buildings.push(building);
    }
}

/// Generate Rust source code for the building data.
pub fn generate_rust(buildings: &[Building]) -> String {
    let mut out = String::from(
        "// AUTO-GENERATED by stellaris-datagen — do not edit.\n\
         #![allow(clippy::all)]\n\
         use super::types::*;\n\n\
         pub static BUILDINGS: &[Building] = &[\n",
    );

    for b in buildings {
        out.push_str(&format!(
            "    Building {{ key: \"{}\", category: \"{}\", base_buildtime: {}, is_capital: {} }},\n",
            b.key, b.category, b.base_buildtime, b.is_capital,
        ));
    }

    out.push_str("];\n");
    out
}
