use jomini::TextTape;
use std::collections::HashMap;
use std::path::Path;

use crate::variables;

pub struct Component {
    pub key: String,
    pub size: String,
    pub power: i32,
    pub component_set: String,
    pub prerequisites: Vec<String>,
}

pub fn parse_components(dir: &Path, vars: &HashMap<String, String>) -> Vec<Component> {
    let mut components = Vec::new();
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return components,
    };

    let mut files: Vec<_> = entries.flatten().map(|e| e.path()).collect();
    files.sort();

    for path in files {
        if path.extension().and_then(|e| e.to_str()) != Some("txt") {
            continue;
        }
        if let Ok(data) = std::fs::read(&path) {
            parse_component_file(&data, vars, &mut components);
        }
    }
    components.sort_by(|a, b| a.key.cmp(&b.key));
    components
}

fn parse_component_file(data: &[u8], vars: &HashMap<String, String>, components: &mut Vec<Component>) {
    let tape = match TextTape::from_slice(data) {
        Ok(t) => t,
        Err(_) => return,
    };
    let reader = tape.windows1252_reader();

    for (key, _op, value) in reader.fields() {
        let key_str = key.read_str();
        if key_str.starts_with('@') {
            continue;
        }
        // Components use wrapper keys like utility_component_template/weapon_component_template
        if !key_str.contains("component_template") {
            continue;
        }

        let obj = match value.read_object() {
            Ok(o) => o,
            Err(_) => continue,
        };

        let mut comp = Component {
            key: String::new(),
            size: String::new(),
            power: 0,
            component_set: String::new(),
            prerequisites: Vec::new(),
        };

        for (fk, _fop, fv) in obj.fields() {
            match fk.read_str().as_ref() {
                "key" => { if let Ok(v) = fv.read_str() { comp.key = v.into_owned(); } }
                "size" => { if let Ok(v) = fv.read_str() { comp.size = v.into_owned(); } }
                "power" => { if let Ok(v) = fv.read_str() { comp.power = variables::resolve_i32(&v, vars); } }
                "component_set" => { if let Ok(v) = fv.read_str() { comp.component_set = v.into_owned(); } }
                "prerequisites" => {
                    if let Ok(arr) = fv.read_array() {
                        for item in arr.values() {
                            if let Ok(s) = item.read_str() { comp.prerequisites.push(s.into_owned()); }
                        }
                    }
                }
                _ => {}
            }
        }

        if !comp.key.is_empty() {
            components.push(comp);
        }
    }
}

pub fn generate_rust(items: &[Component]) -> String {
    let mut out = String::from(
        "// AUTO-GENERATED by stellaris-datagen — do not edit.\n#![allow(clippy::all)]\nuse super::types::*;\n\npub static COMPONENTS: &[Component] = &[\n",
    );
    for c in items {
        let prereqs: Vec<String> = c.prerequisites.iter().map(|p| format!("\"{}\"", crate::variables::escape_rust_str(p))).collect();
        out.push_str(&format!(
            "    Component {{ key: \"{}\", size: \"{}\", power: {}, component_set: \"{}\", prerequisites: &[{}] }},\n",
            crate::variables::escape_rust_str(&c.key),
            crate::variables::escape_rust_str(&c.size),
            c.power,
            crate::variables::escape_rust_str(&c.component_set),
            prereqs.join(", "),
        ));
    }
    out.push_str("];\n");
    out
}
