mod buildings;
mod components;
mod simple;
mod techs;
mod variables;

use std::collections::HashMap;
use std::path::PathBuf;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let (input_dir, output_dir) = parse_args(&args);

    // Step 1: Resolve scripted variables
    eprintln!("Resolving scripted variables...");
    let mut vars = HashMap::new();
    let scripted_vars_dir = input_dir.join("scripted_variables");
    if scripted_vars_dir.exists() {
        variables::load_variables(&scripted_vars_dir, &mut vars);
    }
    // Also load inline variables from relevant directories
    for subdir in &["technology", "buildings", "component_templates", "edicts", "traditions", "pop_jobs"] {
        variables::load_variables_from_dir(&input_dir.join(subdir), &mut vars);
    }
    eprintln!("  {} variables loaded", vars.len());

    // Step 2: Parse all data types
    eprintln!("Parsing technologies...");
    let techs = techs::parse_techs(&input_dir.join("technology"), &vars);
    eprintln!("  {} techs", techs.len());

    eprintln!("Parsing buildings...");
    let buildings = buildings::parse_buildings(&input_dir.join("buildings"), &vars);
    eprintln!("  {} buildings", buildings.len());

    eprintln!("Parsing components...");
    let components = components::parse_components(&input_dir.join("component_templates"), &vars);
    eprintln!("  {} components", components.len());

    eprintln!("Parsing traditions...");
    let traditions = simple::parse_entries_multi(
        &[&input_dir.join("traditions"), &input_dir.join("ascension_perks")],
        &vars,
    );
    eprintln!("  {} traditions + ascension perks", traditions.len());

    eprintln!("Parsing traits...");
    let traits = simple::parse_entries(&input_dir.join("traits"), &vars);
    eprintln!("  {} traits", traits.len());

    eprintln!("Parsing civics...");
    let civics = simple::parse_entries(&input_dir.join("governments").join("civics"), &vars);
    eprintln!("  {} civics + origins", civics.len());

    eprintln!("Parsing edicts...");
    let edicts = simple::parse_entries(&input_dir.join("edicts"), &vars);
    eprintln!("  {} edicts", edicts.len());

    eprintln!("Parsing jobs...");
    let jobs = simple::parse_entries(&input_dir.join("pop_jobs"), &vars);
    eprintln!("  {} jobs", jobs.len());

    // Step 3: Generate output
    std::fs::create_dir_all(&output_dir).expect("failed to create output directory");

    let types_content = generate_types();
    std::fs::write(output_dir.join("types.rs"), types_content).expect("failed to write types.rs");

    std::fs::write(output_dir.join("techs_gen.rs"), techs::generate_rust(&techs))
        .expect("failed to write techs_gen.rs");
    std::fs::write(output_dir.join("buildings_gen.rs"), buildings::generate_rust(&buildings))
        .expect("failed to write buildings_gen.rs");
    std::fs::write(output_dir.join("components_gen.rs"), components::generate_rust(&components))
        .expect("failed to write components_gen.rs");
    std::fs::write(output_dir.join("traditions_gen.rs"), simple::generate_rust("Tradition", "TRADITIONS", &traditions))
        .expect("failed to write traditions_gen.rs");
    std::fs::write(output_dir.join("traits_gen.rs"), simple::generate_rust("Trait", "TRAITS", &traits))
        .expect("failed to write traits_gen.rs");
    std::fs::write(output_dir.join("civics_gen.rs"), simple::generate_rust("Civic", "CIVICS", &civics))
        .expect("failed to write civics_gen.rs");
    std::fs::write(output_dir.join("edicts_gen.rs"), simple::generate_rust("Edict", "EDICTS", &edicts))
        .expect("failed to write edicts_gen.rs");
    std::fs::write(output_dir.join("jobs_gen.rs"), simple::generate_rust("Job", "JOBS", &jobs))
        .expect("failed to write jobs_gen.rs");

    eprintln!("Done. Output written to {}", output_dir.display());
}

fn parse_args(args: &[String]) -> (PathBuf, PathBuf) {
    let mut input = None;
    let mut output = None;
    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--input" => { i += 1; input = Some(PathBuf::from(&args[i])); }
            "--output" => { i += 1; output = Some(PathBuf::from(&args[i])); }
            _ => { eprintln!("unknown argument: {}", args[i]); std::process::exit(1); }
        }
        i += 1;
    }
    let input = input.unwrap_or_else(|| { eprintln!("usage: stellaris-datagen --input <common-dir> --output <output-dir>"); std::process::exit(1); });
    let output = output.unwrap_or_else(|| { eprintln!("usage: stellaris-datagen --input <common-dir> --output <output-dir>"); std::process::exit(1); });
    (input, output)
}

fn generate_types() -> String {
    r#"// AUTO-GENERATED by stellaris-datagen — do not edit.

/// A Stellaris technology definition.
#[derive(Debug, Clone)]
pub struct Tech {
    pub key: &'static str,
    pub area: &'static str,
    pub tier: i32,
    pub cost: i32,
    pub category: &'static str,
    pub prerequisites: &'static [&'static str],
    pub is_start_tech: bool,
    pub is_repeatable: bool,
    pub weight: i32,
}

/// A Stellaris building definition.
#[derive(Debug, Clone)]
pub struct Building {
    pub key: &'static str,
    pub category: &'static str,
    pub base_buildtime: i32,
    pub is_capital: bool,
}

/// A ship component (weapon, utility, combat computer, etc.).
#[derive(Debug, Clone)]
pub struct Component {
    pub key: &'static str,
    pub size: &'static str,
    pub power: i32,
    pub component_set: &'static str,
    pub prerequisites: &'static [&'static str],
}

/// A tradition or ascension perk.
#[derive(Debug, Clone)]
pub struct Tradition {
    pub key: &'static str,
    pub category: &'static str,
    pub cost: i32,
    pub is_origin: bool,
}

/// A species or leader trait.
#[derive(Debug, Clone)]
pub struct Trait {
    pub key: &'static str,
    pub category: &'static str,
    pub cost: i32,
    pub is_origin: bool,
}

/// A civic or origin.
#[derive(Debug, Clone)]
pub struct Civic {
    pub key: &'static str,
    pub category: &'static str,
    pub cost: i32,
    pub is_origin: bool,
}

/// An edict or policy.
#[derive(Debug, Clone)]
pub struct Edict {
    pub key: &'static str,
    pub category: &'static str,
    pub cost: i32,
    pub is_origin: bool,
}

/// A pop job.
#[derive(Debug, Clone)]
pub struct Job {
    pub key: &'static str,
    pub category: &'static str,
    pub cost: i32,
    pub is_origin: bool,
}
"#
    .to_string()
}
