use jomini::TextTape;
use std::collections::HashMap;
use std::path::Path;

use crate::variables;

/// A simple game data entry with just a key and optional extracted fields.
pub struct SimpleEntry {
    pub key: String,
    pub category: String,
    pub cost: i32,
    pub is_origin: bool,
}

/// Parse all .txt files in a directory, extracting top-level keys as entries.
/// Optionally extracts `category`, `cost`, and `is_origin` fields.
pub fn parse_entries(dir: &Path, vars: &HashMap<String, String>) -> Vec<SimpleEntry> {
    let mut entries = Vec::new();
    let read_entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return entries,
    };

    let mut files: Vec<_> = read_entries.flatten().map(|e| e.path()).collect();
    files.sort();

    for path in files {
        if path.extension().and_then(|e| e.to_str()) != Some("txt") {
            continue;
        }
        if let Ok(data) = std::fs::read(&path) {
            parse_file(&data, vars, &mut entries);
        }
    }
    entries.sort_by(|a, b| a.key.cmp(&b.key));
    entries
}

/// Parse multiple directories and merge results.
pub fn parse_entries_multi(dirs: &[&Path], vars: &HashMap<String, String>) -> Vec<SimpleEntry> {
    let mut entries = Vec::new();
    for dir in dirs {
        entries.extend(parse_entries(dir, vars));
    }
    entries.sort_by(|a, b| a.key.cmp(&b.key));
    entries
}

fn parse_file(data: &[u8], vars: &HashMap<String, String>, entries: &mut Vec<SimpleEntry>) {
    let tape = match TextTape::from_slice(data) {
        Ok(t) => t,
        Err(_) => return,
    };
    let reader = tape.windows1252_reader();

    for (key, _op, value) in reader.fields() {
        let key_str = key.read_str();
        if key_str.starts_with('@') {
            continue;
        }

        let obj = match value.read_object() {
            Ok(o) => o,
            Err(_) => continue,
        };

        let mut entry = SimpleEntry {
            key: key_str.into_owned(),
            category: String::new(),
            cost: 0,
            is_origin: false,
        };

        for (fk, _fop, fv) in obj.fields() {
            match fk.read_str().as_ref() {
                "category" => {
                    if let Ok(v) = fv.read_str() {
                        entry.category = v.into_owned();
                    }
                }
                "cost" => {
                    if let Ok(v) = fv.read_str() {
                        entry.cost = variables::resolve_i32(&v, vars);
                    }
                }
                "is_origin" => {
                    if let Ok(v) = fv.read_str() {
                        entry.is_origin = v.as_ref() == "yes";
                    }
                }
                _ => {}
            }
        }

        entries.push(entry);
    }
}

/// Generate Rust source for a named static array of SimpleEntry data.
pub fn generate_rust(type_name: &str, array_name: &str, items: &[SimpleEntry]) -> String {
    let mut out = format!(
        "// AUTO-GENERATED by stellaris-datagen — do not edit.\n\
         #![allow(clippy::all)]\n\
         use super::types::*;\n\n\
         pub static {array_name}: &[{type_name}] = &[\n"
    );
    for e in items {
        out.push_str(&format!(
            "    {type_name} {{ key: \"{}\", category: \"{}\", cost: {}, is_origin: {} }},\n",
            e.key, e.category, e.cost, e.is_origin,
        ));
    }
    out.push_str("];\n");
    out
}
