use jomini::TextTape;
use std::collections::HashMap;
use std::path::Path;

use crate::variables;

pub struct Tech {
    pub key: String,
    pub area: String,
    pub tier: i32,
    pub cost: i32,
    pub category: String,
    pub prerequisites: Vec<String>,
    pub is_start_tech: bool,
    pub is_repeatable: bool,
    pub weight: i32,
}

/// Parse all technology files in the given directory.
pub fn parse_techs(dir: &Path, vars: &HashMap<String, String>) -> Vec<Tech> {
    let mut techs = Vec::new();
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return techs,
    };

    let mut files: Vec<_> = entries.flatten().map(|e| e.path()).collect();
    files.sort();

    for path in files {
        if path.extension().and_then(|e| e.to_str()) != Some("txt") {
            continue;
        }
        if let Ok(data) = std::fs::read(&path) {
            parse_tech_file(&data, vars, &mut techs);
        }
    }

    techs.sort_by(|a, b| a.key.cmp(&b.key));
    techs
}

fn parse_tech_file(data: &[u8], vars: &HashMap<String, String>, techs: &mut Vec<Tech>) {
    let tape = match TextTape::from_slice(data) {
        Ok(t) => t,
        Err(_) => return,
    };
    let reader = tape.windows1252_reader();

    for (key, _op, value) in reader.fields() {
        let key_str = key.read_str();
        // Skip variable definitions (start with @)
        if key_str.starts_with('@') {
            continue;
        }

        let obj = match value.read_object() {
            Ok(o) => o,
            Err(_) => continue,
        };

        let mut tech = Tech {
            key: key_str.into_owned(),
            area: String::new(),
            tier: 0,
            cost: 0,
            category: String::new(),
            prerequisites: Vec::new(),
            is_start_tech: false,
            is_repeatable: false,
            weight: 0,
        };

        for (field_key, _fop, field_val) in obj.fields() {
            let fk = field_key.read_str();
            match fk.as_ref() {
                "area" => {
                    if let Ok(v) = field_val.read_str() {
                        tech.area = v.into_owned();
                    }
                }
                "tier" => {
                    if let Ok(v) = field_val.read_str() {
                        tech.tier = variables::resolve_i32(&v, vars);
                    }
                }
                "cost" => {
                    if let Ok(v) = field_val.read_str() {
                        tech.cost = variables::resolve_i32(&v, vars);
                    }
                }
                "category" => {
                    // category = { particles } — array with one element
                    if let Ok(arr) = field_val.read_array() {
                        for item in arr.values() {
                            if let Ok(s) = item.read_str() {
                                tech.category = s.into_owned();
                                break;
                            }
                        }
                    }
                }
                "prerequisites" => {
                    if let Ok(arr) = field_val.read_array() {
                        for item in arr.values() {
                            if let Ok(s) = item.read_str() {
                                tech.prerequisites.push(s.into_owned());
                            }
                        }
                    }
                }
                "start_tech" => {
                    if let Ok(v) = field_val.read_str() {
                        tech.is_start_tech = v.as_ref() == "yes";
                    }
                }
                "levels" => {
                    // Repeatable techs have levels > 0
                    if let Ok(v) = field_val.read_str() {
                        if let Ok(n) = v.parse::<i32>() {
                            if n > 1 || n == -1 {
                                tech.is_repeatable = true;
                            }
                        }
                    }
                }
                "weight" => {
                    if let Ok(v) = field_val.read_str() {
                        tech.weight = variables::resolve_i32(&v, vars);
                    }
                }
                _ => {}
            }
        }

        // Only include entries that have an area (skip non-tech entries)
        if !tech.area.is_empty() {
            techs.push(tech);
        }
    }
}

/// Generate Rust source code for the tech data.
pub fn generate_rust(techs: &[Tech]) -> String {
    let mut out = String::from(
        "// AUTO-GENERATED by stellaris-datagen — do not edit.\n\
         #![allow(clippy::all)]\n\
         use super::types::*;\n\n\
         pub static TECHS: &[Tech] = &[\n",
    );

    for tech in techs {
        let prereqs: Vec<String> = tech.prerequisites.iter().map(|p| format!("\"{p}\"")).collect();
        out.push_str(&format!(
            "    Tech {{ key: \"{}\", area: \"{}\", tier: {}, cost: {}, category: \"{}\", \
             prerequisites: &[{}], is_start_tech: {}, is_repeatable: {}, weight: {} }},\n",
            tech.key,
            tech.area,
            tech.tier,
            tech.cost,
            tech.category,
            prereqs.join(", "),
            tech.is_start_tech,
            tech.is_repeatable,
            tech.weight,
        ));
    }

    out.push_str("];\n");
    out
}
